/**
 * Live / Final 試合スタッツプレビュー用モック。
 * 本番の型・正規化は lib/games/liveGameStats.ts。
 */

import type {
  LiveGamePhase,
  LiveGameStatsReport,
} from "@/lib/games/liveGameStats";

export type {
  LiveGamePhase,
  LiveGameTeamSide,
  LiveGameTeamStatRow,
  LiveGameBoxPlayer,
  LiveGameBoxTeam,
  LiveGameStatsReport,
} from "@/lib/games/liveGameStats";
export { formatLiveTeamStatValue } from "@/lib/games/liveGameStats";

const LIVE_REPORT: LiveGameStatsReport = {
  gameId: "nba-preview-live-lal-bos",
  phase: "live",
  periodLabel: "Q3",
  clock: "4:12",
  home: {
    teamId: "nba-lakers",
    teamName: "Los Angeles Lakers",
    abbr: "LAL",
    score: 78,
  },
  away: {
    teamId: "nba-celtics",
    teamName: "Boston Celtics",
    abbr: "BOS",
    score: 81,
  },
  teamStats: [
    { key: "fg", label: "FG%", home: 46.2, away: 48.1, format: "pct" },
    { key: "fg3", label: "3P%", home: 34.8, away: 41.2, format: "pct" },
    { key: "ft", label: "FT%", home: 82.4, away: 78.6, format: "pct" },
    { key: "reb", label: "REB", home: 28, away: 31, format: "int" },
    { key: "ast", label: "AST", home: 16, away: 19, format: "int" },
    { key: "stl", label: "STL", home: 5, away: 4, format: "int" },
    { key: "blk", label: "BLK", home: 3, away: 2, format: "int" },
    { key: "tov", label: "TO", home: 9, away: 7, format: "int", lowerIsBetter: true },
    { key: "paint", label: "PAINT", home: 34, away: 30, format: "int" },
    { key: "fb", label: "FB PTS", home: 8, away: 12, format: "int" },
  ],
  box: {
    home: {
      teamId: "nba-lakers",
      teamName: "Los Angeles Lakers",
      side: "home",
      players: [
        {
          playerId: "15",
          firstName: "Anthony",
          lastName: "Davis",
          position: "F-C",
          jerseyNumber: "3",
          starter: true,
          min: 28,
          pts: 24,
          reb: 11,
          ast: 2,
          stl: 1,
          blk: 3,
          tov: 2,
          fg: "9-16",
          fg3: "0-1",
          ft: "6-7",
          plusMinus: 4,
        },
        {
          playerId: "237",
          firstName: "LeBron",
          lastName: "James",
          position: "F",
          jerseyNumber: "23",
          starter: true,
          min: 27,
          pts: 18,
          reb: 6,
          ast: 8,
          stl: 1,
          blk: 0,
          tov: 3,
          fg: "7-14",
          fg3: "1-4",
          ft: "3-4",
          plusMinus: 1,
        },
        {
          playerId: "88",
          firstName: "Austin",
          lastName: "Reaves",
          position: "G",
          jerseyNumber: "15",
          starter: true,
          min: 24,
          pts: 14,
          reb: 3,
          ast: 4,
          stl: 1,
          blk: 0,
          tov: 1,
          fg: "5-11",
          fg3: "2-6",
          ft: "2-2",
          plusMinus: -2,
        },
        {
          playerId: "12",
          firstName: "D'Angelo",
          lastName: "Russell",
          position: "G",
          jerseyNumber: "1",
          starter: true,
          min: 22,
          pts: 11,
          reb: 2,
          ast: 3,
          stl: 0,
          blk: 0,
          tov: 2,
          fg: "4-9",
          fg3: "2-5",
          ft: "1-1",
          plusMinus: -5,
        },
        {
          playerId: "44",
          firstName: "Rui",
          lastName: "Hachimura",
          position: "F",
          jerseyNumber: "28",
          starter: true,
          min: 20,
          pts: 8,
          reb: 4,
          ast: 1,
          stl: 1,
          blk: 0,
          tov: 0,
          fg: "3-7",
          fg3: "1-3",
          ft: "1-2",
          plusMinus: 0,
        },
        {
          playerId: "5",
          firstName: "Gabe",
          lastName: "Vincent",
          position: "G",
          jerseyNumber: "7",
          starter: false,
          min: 11,
          pts: 3,
          reb: 1,
          ast: 1,
          stl: 1,
          blk: 0,
          tov: 1,
          fg: "1-3",
          fg3: "1-2",
          ft: "0-0",
          plusMinus: -3,
        },
      ],
    },
    away: {
      teamId: "nba-celtics",
      teamName: "Boston Celtics",
      side: "away",
      players: [
        {
          playerId: "406",
          firstName: "Jayson",
          lastName: "Tatum",
          position: "F",
          jerseyNumber: "0",
          starter: true,
          min: 29,
          pts: 22,
          reb: 7,
          ast: 5,
          stl: 1,
          blk: 1,
          tov: 2,
          fg: "8-17",
          fg3: "3-8",
          ft: "3-3",
          plusMinus: 6,
        },
        {
          playerId: "434",
          firstName: "Jaylen",
          lastName: "Brown",
          position: "G-F",
          jerseyNumber: "7",
          starter: true,
          min: 26,
          pts: 19,
          reb: 5,
          ast: 3,
          stl: 1,
          blk: 0,
          tov: 1,
          fg: "7-13",
          fg3: "2-5",
          ft: "3-4",
          plusMinus: 3,
        },
        {
          playerId: "178",
          firstName: "Derrick",
          lastName: "White",
          position: "G",
          jerseyNumber: "9",
          starter: true,
          min: 25,
          pts: 14,
          reb: 3,
          ast: 4,
          stl: 2,
          blk: 1,
          tov: 1,
          fg: "5-10",
          fg3: "3-6",
          ft: "1-1",
          plusMinus: 5,
        },
        {
          playerId: "70",
          firstName: "Kristaps",
          lastName: "Porzingis",
          position: "C",
          jerseyNumber: "8",
          starter: true,
          min: 21,
          pts: 12,
          reb: 8,
          ast: 1,
          stl: 0,
          blk: 2,
          tov: 1,
          fg: "4-8",
          fg3: "1-3",
          ft: "3-4",
          plusMinus: 2,
        },
        {
          playerId: "90",
          firstName: "Jrue",
          lastName: "Holiday",
          position: "G",
          jerseyNumber: "4",
          starter: true,
          min: 23,
          pts: 9,
          reb: 4,
          ast: 6,
          stl: 1,
          blk: 0,
          tov: 2,
          fg: "3-7",
          fg3: "1-3",
          ft: "2-2",
          plusMinus: 4,
        },
        {
          playerId: "55",
          firstName: "Payton",
          lastName: "Pritchard",
          position: "G",
          jerseyNumber: "11",
          starter: false,
          min: 12,
          pts: 5,
          reb: 1,
          ast: 2,
          stl: 0,
          blk: 0,
          tov: 0,
          fg: "2-4",
          fg3: "1-3",
          ft: "0-0",
          plusMinus: -1,
        },
      ],
    },
  },
};

const FINAL_REPORT: LiveGameStatsReport = {
  ...LIVE_REPORT,
  gameId: "nba-preview-final-lal-bos",
  phase: "final",
  periodLabel: "FINAL",
  clock: null,
  home: { ...LIVE_REPORT.home, score: 108 },
  away: { ...LIVE_REPORT.away, score: 112 },
  teamStats: [
    { key: "fg", label: "FG%", home: 45.1, away: 47.8, format: "pct" },
    { key: "fg3", label: "3P%", home: 33.3, away: 39.5, format: "pct" },
    { key: "ft", label: "FT%", home: 81.0, away: 84.2, format: "pct" },
    { key: "reb", label: "REB", home: 42, away: 45, format: "int" },
    { key: "ast", label: "AST", home: 24, away: 28, format: "int" },
    { key: "stl", label: "STL", home: 7, away: 8, format: "int" },
    { key: "blk", label: "BLK", home: 5, away: 4, format: "int" },
    { key: "tov", label: "TO", home: 13, away: 11, format: "int", lowerIsBetter: true },
    { key: "paint", label: "PAINT", home: 48, away: 44, format: "int" },
    { key: "fb", label: "FB PTS", home: 14, away: 18, format: "int" },
  ],
  box: {
    home: {
      ...LIVE_REPORT.box.home,
      players: LIVE_REPORT.box.home.players.map((p) => ({
        ...p,
        min: Math.min(38, p.min + 8),
        pts: p.pts + Math.round(p.pts * 0.35),
        reb: p.reb + 2,
        ast: p.ast + 1,
      })),
    },
    away: {
      ...LIVE_REPORT.box.away,
      players: LIVE_REPORT.box.away.players.map((p) => ({
        ...p,
        min: Math.min(39, p.min + 8),
        pts: p.pts + Math.round(p.pts * 0.38),
        reb: p.reb + 2,
        ast: p.ast + 1,
      })),
    },
  },
};

export function liveGameStatsPreviewReport(
  phase: LiveGamePhase
): LiveGameStatsReport {
  return phase === "live" ? LIVE_REPORT : FINAL_REPORT;
}
