import { Platform, StyleSheet } from "react-native";
import { METRIC_FONT, RANK_DISPLAY_FONT, RANKING_SCORE_FONT, rankingNameFont } from "./rankingsUiTheme";

const GOLD = "#FFD65A";

export const rankingsUiStyles = StyleSheet.create({
  avatarWrap: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    overflow: "hidden",
  },
  avatarSquare: {
    borderRadius: 4,
  },
  avatarInitial: {
    color: "rgba(248,250,252,0.92)",
    fontWeight: "700",
    fontFamily: RANKING_SCORE_FONT,
  },
  tabGrid2: {
    flexDirection: "row",
    gap: 6,
  },
  tabGrid5: {
    flexDirection: "row",
    gap: 6,
  },
  tabChip: {
    flex: 1,
    minHeight: 36,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.62)",
    backgroundColor: "rgba(2,6,16,0.86)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 5,
    transform: [{ skewX: "-16deg" }],
  },
  roundChip: {
    flex: 1,
    minHeight: 34,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.62)",
    backgroundColor: "rgba(2,6,16,0.86)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    paddingVertical: 4,
    transform: [{ skewX: "-16deg" }],
  },
  tabChipActive: {
    borderColor: "rgba(34,211,238,0.9)",
    backgroundColor: "rgba(28,236,255,0.92)",
  },
  tabChipText: {
    color: "rgba(170,242,255,0.9)",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: METRIC_FONT,
    letterSpacing: 1.3,
    textTransform: "uppercase",
    transform: [{ skewX: "16deg" }],
  },
  roundChipText: {
    color: "rgba(170,242,255,0.9)",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: METRIC_FONT,
    letterSpacing: 1.1,
    textTransform: "uppercase",
    transform: [{ skewX: "16deg" }],
  },
  tabChipTextActive: {
    color: "rgba(2,16,26,0.96)",
    fontWeight: "800",
  },
  /** Web `RankingsMetricRowMobile`：3スロット（左右は perspective+rotateY） */
  metricCarouselWrap: {
    width: "100%",
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  metricCarouselInner: {
    width: "100%",
    maxWidth: 340,
    height: 50,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  metricCarouselSideAbs: {
    position: "absolute",
    top: 7,
    zIndex: 0,
    minHeight: 34,
    minWidth: 72,
    maxWidth: "30%",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
    backgroundColor: "transparent",
    opacity: 0.72,
    alignItems: "center",
    justifyContent: "center",
  },
  metricCarouselSideAbsLeft: {
    left: 0,
    transform: [{ perspective: 800 }, { rotateY: "26deg" }],
  },
  metricCarouselSideAbsRight: {
    right: 0,
    transform: [{ perspective: 800 }, { rotateY: "-26deg" }],
  },
  metricCarouselSidePressed: {
    borderColor: "rgba(0,140,255,0.85)",
  },
  /** Web 中央ピル（緑枠・大） */
  metricCarouselCenter: {
    zIndex: 10,
    minHeight: 40,
    minWidth: 108,
    maxWidth: "54%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(57,255,136,0.72)",
    backgroundColor: "rgba(255,255,255,0.07)",
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      ios: {
        shadowColor: "rgba(57,255,136,0.5)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.85,
        shadowRadius: 12,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  metricCarouselSideText: {
    fontSize: 10,
    fontWeight: "600",
    color: "rgba(255,255,255,0.5)",
    textAlign: "center",
    fontFamily: METRIC_FONT,
    lineHeight: 13,
  },
  metricCarouselCenterText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.45,
    color: "rgba(255,255,255,0.98)",
    textAlign: "center",
    fontFamily: METRIC_FONT,
    lineHeight: 15,
    ...Platform.select({
      ios: {
        textShadowColor: "rgba(57,255,136,0.35)",
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 8,
      },
      default: {},
    }),
  },
  podiumWrap: {
    marginTop: 0,
    gap: 0,
    paddingTop: 12,
  },
  myRankOuter: {
    marginBottom: 0,
    marginTop: 2,
  },
  myRankOuterWide: {
    marginHorizontal: -4,
    width: "100%",
  },
  myRankFreeLoading: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 16,
    alignItems: "center",
  },
  myRankFreeLoadingText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    fontFamily: METRIC_FONT,
  },
  myRankCaptureWrap: {
    position: "relative",
  },
  myRankShareBtn: {
    position: "absolute",
    top: 10,
    right: 86,
    zIndex: 4,
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  myRankShareBtnInner: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.35)",
    backgroundColor: "rgba(34,211,238,0.08)",
  },
  myRankCard: {
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.44)",
    overflow: "hidden",
  },
  myRankForeground: {
    zIndex: 2,
  },
  myRankTowerGrid: {
    flexDirection: "row",
    minHeight: 108,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  myRankTopBand: {
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 4,
  },
  myRankFreeBody: {
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  /** Pro: 上段2列 + 下段 Progress */
  myRankProStack: {
    gap: 0,
  },
  /** Pro 上段: ユーザー | 順位+スタッツ */
  myRankProThreeCol: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 6,
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
    minHeight: 96,
  },
  myRankProUserCol: {
    width: 92,
    alignItems: "center",
    gap: 5,
    paddingTop: 2,
  },
  myRankProAvatarFrame: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 4,
    overflow: "hidden",
  },
  myRankProUserNameBlock: {
    width: "100%",
    alignItems: "center",
    gap: 3,
  },
  myRankProUserBadgeWrap: {
    marginTop: 1,
  },
  myRankProHeroName: {
    flexShrink: 1,
    color: "rgba(248,250,252,1)",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "900",
    textAlign: "center",
  },
  myRankProMidCol: {
    flex: 1.15,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "stretch",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderRadius: 4,
    /** 得点 Alfa Slab の上端を切らない */
    overflow: "visible",
  },
  myRankProMidColWide: {
    flex: 1.6,
  },
  myRankProRankHalf: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRightWidth: 1,
    borderRightColor: "rgba(245,215,142,0.2)",
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  myRankProRankCluster: {
    alignItems: "center",
    gap: 0,
  },
  myRankProHashRankRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
  },
  myRankProHash: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 18,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    marginTop: 2,
  },
  myRankProEntriesTight: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
    fontFamily: METRIC_FONT,
    marginTop: -3,
  },
  myRankProStatsHalf: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 3,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  myRankProVolAvgRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 6,
  },
  myRankProVolText: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.2,
    fontFamily: METRIC_FONT,
    textTransform: "uppercase",
  },
  myRankProAvgText: {
    flexShrink: 1,
    color: "rgba(0,245,255,0.55)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    fontFamily: METRIC_FONT,
    textTransform: "uppercase",
  },
  myRankProMetaGold: {
    color: "#FFD65A",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    fontFamily: METRIC_FONT,
    textAlign: "center",
  },
  myRankProMetaMuted: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 0.3,
    fontFamily: METRIC_FONT,
    textAlign: "center",
  },
  myRankProNameBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  myRankProProgressBand: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 6,
    minHeight: 64,
  },
  myRankTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  myRankStatsRight: {
    flexShrink: 0,
    alignItems: "flex-end",
    paddingTop: 2,
  },
  myRankProgressPane: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  myRankTowerLeft: {
    width: 100,
    borderRightWidth: 1,
    borderRightColor: "rgba(34,211,238,0.22)",
    backgroundColor: "rgba(0,245,255,0.04)",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 6,
    paddingVertical: 10,
    gap: 4,
  },
  myRankTowerRight: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 10,
    justifyContent: "flex-start",
    gap: 8,
  },
  myRankAvatarSquare: {
    borderWidth: 1,
    borderRadius: 4,
    overflow: "hidden",
  },
  myRankHudCol: {
    marginLeft: "auto",
    alignItems: "flex-end",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.08)",
    paddingLeft: 10,
    minWidth: 72,
  },
  myRankHudUnderAvatar: {
    marginTop: 6,
    alignItems: "flex-start",
  },
  myRankHudMetaRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  myRankHudValueCluster: {
    flexGrow: 0,
    flexShrink: 0,
    alignItems: "flex-end",
    gap: 0,
    overflow: "visible",
    paddingTop: 2,
  },
  myRankMetaBesideStats: {
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  myRankHudValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    overflow: "visible",
  },
  myRankHudDeltaRight: {
    textAlign: "right",
  },
  myRankHudLabel: {
    fontSize: 7,
    fontWeight: "600",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    fontFamily: METRIC_FONT,
  },
  myRankHudValue: {
    marginTop: 4,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
    fontFamily: RANKING_SCORE_FONT,
  },
  myRankHudValueLarge: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
    fontFamily: RANKING_SCORE_FONT,
  },
  myRankHudUnit: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.45)",
    fontFamily: METRIC_FONT,
  },
  myRankHudUnitLarge: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.45)",
    fontFamily: METRIC_FONT,
  },
  myRankHudDelta: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: METRIC_FONT,
  },
  myRankHudDeltaAbove: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
    fontFamily: METRIC_FONT,
    marginBottom: 0,
  },
  myRankMetaStrip: {
    alignSelf: "stretch",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
    marginTop: 2,
  },
  myRankMetaStripBeside: {
    marginTop: 4,
    flexShrink: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
  },
  myRankTopPercentBadge: {
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(255,214,90,0.08)",
  },
  myRankTopPercentText: {
    color: GOLD,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    fontFamily: METRIC_FONT,
    textTransform: "uppercase",
  },
  myRankMetaVol: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    fontFamily: METRIC_FONT,
    textTransform: "uppercase",
    textAlign: "right",
  },
  myRankMetaAvg: {
    color: "rgba(0,245,255,0.55)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    fontFamily: METRIC_FONT,
    textTransform: "uppercase",
    flexShrink: 1,
    textAlign: "right",
  },
  myRankSegWrap: {
    marginTop: 2,
  },
  myRankFooter: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  myRankFooterText: {
    color: "rgba(255,255,255,0.26)",
    fontSize: 7,
    fontWeight: "500",
    letterSpacing: 1.8,
    textTransform: "uppercase",
    fontFamily: METRIC_FONT,
  },
  myRankTopSheen: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 0,
    height: 1,
    zIndex: 3,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  myRankNameCol: {
    flex: 1,
    minWidth: 0,
    paddingTop: 4,
  },
  myRankHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  myRankNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  myRankNameWeb: {
    flexShrink: 1,
    color: "rgba(248,250,252,1)",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "900",
  },
  proBadgeWrap: {
    borderWidth: 1,
    borderColor: "rgba(103,232,249,0.45)",
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
    backgroundColor: "rgba(8,18,28,0.75)",
  },
  /** Free — ProCyberBadgeNative premium 相当の invisible spacer */
  proBadgeSpacer: {
    width: 40,
    height: 22,
    flexShrink: 0,
    opacity: 0,
  },
  proBadgeInner: {
    color: "rgba(248,250,252,0.95)",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.6,
    fontFamily: METRIC_FONT,
  },
  myRankMetricValueLarge: {
    color: "rgba(255,255,255,0.96)",
    fontSize: 24,
    lineHeight: 26,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  myRankYourRankLabel: {
    color: "rgba(160,235,255,0.72)",
    fontSize: 7.5,
    fontWeight: "600",
    letterSpacing: 2.2,
    textTransform: "uppercase",
    fontFamily: METRIC_FONT,
    textAlign: "center",
    marginBottom: 2,
  },
  myRankTowerRankBlock: {
    alignItems: "center",
    gap: 2,
  },
  myRankTowerHash: {
    fontSize: 34,
    lineHeight: 36,
    fontWeight: "400",
    fontFamily: RANK_DISPLAY_FONT,
    letterSpacing: 1,
    transform: [{ skewX: "-12deg" }],
    textAlign: "center",
  },
  myRankEntries: {
    color: "rgba(255,255,255,0.38)",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: METRIC_FONT,
    textAlign: "center",
  },
  rankDeltaInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  rankDeltaInlineMd: {
    gap: 2,
  },
  rankDeltaInlineAmount: {
    fontWeight: "700",
    lineHeight: 16,
    fontFamily: METRIC_FONT,
    marginTop: Platform.OS === "ios" ? 0 : 1,
  },
  myRankStreakRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 3,
    justifyContent: "flex-end",
  },
  myRankStreakSuffix: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  myRankWinPosts: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(255,255,255,0.4)",
    fontFamily: METRIC_FONT,
    textAlign: "right",
  },
  listCardOuter: {
    borderRadius: 0,
    borderWidth: 1,
    overflow: "hidden",
    position: "relative",
  },
  listCardDims: {
    minHeight: 56,
  },
  podiumCardDims: {
    minHeight: 66,
  },
  podiumCardRoot: {
    position: "relative",
    marginBottom: 0,
  },
  podiumCrownWrap: {
    position: "absolute",
    left: 50,
    top: -10,
    zIndex: 40,
    pointerEvents: "none",
  },
  listCardForeground: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    zIndex: 2,
  },
  listRank: {
    width: 32,
    textAlign: "center",
    fontWeight: "400",
    fontFamily: RANK_DISPLAY_FONT,
    transform: [{ skewX: "-12deg" }],
  },
  listMain: {
    flex: 1,
    minWidth: 0,
  },
  listNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  listName: {
    flexShrink: 1,
    color: "rgba(248,250,252,0.94)",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    ...Platform.select({
      ios: {
        textShadowColor: "rgba(0,0,0,0.35)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 12,
      },
      default: {},
    }),
  },
  listNamePodium: {
    fontSize: 16,
  },
  listValueOuter: {
    flexShrink: 0,
    minWidth: 96,
    /** Web のスコア列 `auto` に寄せ、右約34〜38%の国旗エリアがスコアに隠れないようにする */
    maxWidth: "34%",
    paddingLeft: 4,
    justifyContent: "center",
  },
  listValueOuterPodium: {
    minWidth: 84,
    maxWidth: "34%",
    alignItems: "flex-end",
  },
  listValueCol: {
    alignItems: "flex-end",
    gap: 3,
    width: "100%",
  },
  listValueColPodium: {
    alignItems: "flex-end",
  },
  listScoreRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "nowrap",
    justifyContent: "flex-end",
    gap: 2,
  },
  listScoreRowPodium: {
    justifyContent: "flex-end",
  },
  listScoreMain: {
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  listScoreSuffix: {
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    marginLeft: 1,
  },
  listSubRight: {
    fontSize: 10,
    lineHeight: 13,
    color: "rgba(148,163,184,0.9)",
    fontFamily: METRIC_FONT,
    textAlign: "right",
    maxWidth: "100%",
  },
  listSubRightPodium: {
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(255,255,255,0.4)",
  },
});
