import { Platform, StyleSheet } from "react-native";
import { METRIC_FONT } from "./rankingsUiTheme";

export const rankingsUiStyles = StyleSheet.create({
  avatarWrap: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    overflow: "hidden",
  },
  avatarInitial: {
    color: "rgba(248,250,252,0.92)",
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  tabGrid2: {
    flexDirection: "row",
    gap: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 3,
  },
  tabGrid5: {
    flexDirection: "row",
    gap: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 3,
  },
  tabChip: {
    flex: 1,
    minHeight: 26,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  roundChip: {
    flex: 1,
    minHeight: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  tabChipActive: {
    borderColor: "rgba(57,255,136,0.55)",
    backgroundColor: "rgba(57,255,136,0.12)",
  },
  tabChipText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: METRIC_FONT,
  },
  roundChipText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: METRIC_FONT,
  },
  tabChipTextActive: {
    color: "rgba(207,250,254,0.96)",
  },
  /** Web `RankingsMetricRowMobile`：3スロット（左右は perspective+rotateY） */
  metricCarouselWrap: {
    width: "100%",
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  metricCarouselInner: {
    width: "100%",
    maxWidth: 340,
    height: 50,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  metricCarouselSideAbs: {
    position: "absolute",
    top: 7,
    zIndex: 0,
    minHeight: 34,
    minWidth: 72,
    maxWidth: "30%",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
    backgroundColor: "transparent",
    opacity: 0.72,
    alignItems: "center",
    justifyContent: "center",
  },
  metricCarouselSideAbsLeft: {
    left: 0,
    transform: [{ perspective: 800 }, { rotateY: "26deg" }],
  },
  metricCarouselSideAbsRight: {
    right: 0,
    transform: [{ perspective: 800 }, { rotateY: "-26deg" }],
  },
  metricCarouselSidePressed: {
    borderColor: "rgba(0,140,255,0.85)",
  },
  /** Web 中央ピル（緑枠・大） */
  metricCarouselCenter: {
    zIndex: 10,
    minHeight: 40,
    minWidth: 108,
    maxWidth: "54%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(57,255,136,0.72)",
    backgroundColor: "rgba(255,255,255,0.07)",
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      ios: {
        shadowColor: "rgba(57,255,136,0.5)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.85,
        shadowRadius: 12,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  metricCarouselSideText: {
    fontSize: 10,
    fontWeight: "600",
    color: "rgba(255,255,255,0.5)",
    textAlign: "center",
    fontFamily: METRIC_FONT,
    lineHeight: 13,
  },
  metricCarouselCenterText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.45,
    color: "rgba(255,255,255,0.98)",
    textAlign: "center",
    fontFamily: METRIC_FONT,
    lineHeight: 15,
    ...Platform.select({
      ios: {
        textShadowColor: "rgba(57,255,136,0.35)",
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 8,
      },
      default: {},
    }),
  },
  podiumWrap: {
    marginHorizontal: -4,
    marginTop: 2,
    gap: 12,
    paddingTop: 16,
    paddingHorizontal: 4,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 14,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  myRankOuter: {
    marginBottom: 10,
  },
  myRankCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    overflow: "hidden",
  },
  myRankForeground: {
    zIndex: 2,
  },
  myRankRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  myRankLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
    marginLeft: -4,
  },
  myRankNameCol: {
    flex: 1,
    minWidth: 0,
    marginTop: -2,
  },
  myRankNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  myRankNameWeb: {
    flexShrink: 1,
    color: "rgba(248,250,252,1)",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "900",
    fontFamily: METRIC_FONT,
  },
  proBadgeWrap: {
    borderWidth: 1,
    borderColor: "rgba(103,232,249,0.45)",
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
    backgroundColor: "rgba(8,18,28,0.75)",
  },
  proBadgeInner: {
    color: "rgba(248,250,252,0.95)",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.6,
    fontFamily: METRIC_FONT,
  },
  myRankCenter: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    minWidth: 88,
  },
  myRankYourRankLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 2.2,
    textTransform: "uppercase",
    fontFamily: METRIC_FONT,
    marginBottom: 4,
  },
  myRankCenterNums: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  myRankHash: {
    fontSize: 21,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  rankDeltaInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 1,
  },
  rankDeltaInlineMd: {
    gap: 2,
  },
  rankDeltaInlineAmount: {
    fontWeight: "700",
    lineHeight: 16,
    fontFamily: METRIC_FONT,
    marginTop: Platform.OS === "ios" ? 0 : 1,
  },
  myRankRightCol: {
    alignItems: "flex-end",
    justifyContent: "center",
    minWidth: 76,
    maxWidth: "34%",
  },
  myRankMetricValueLarge: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 19,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    textAlign: "right",
  },
  myRankStreakRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 3,
    justifyContent: "flex-end",
  },
  myRankStreakSuffix: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  myRankWinPosts: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(255,255,255,0.4)",
    fontFamily: METRIC_FONT,
    textAlign: "right",
  },
  /** 一覧行の PRO（自分カードは proBadgeWrap） */
  proBadge: {
    color: "rgba(252,211,77,0.95)",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.8,
    fontFamily: METRIC_FONT,
  },
  listCardOuter: {
    borderRadius: 0,
    borderWidth: 1,
    overflow: "hidden",
    position: "relative",
  },
  listCardDims: {
    minHeight: 50,
  },
  podiumCardDims: {
    minHeight: 66,
  },
  podiumCardRoot: {
    position: "relative",
    marginBottom: 0,
  },
  podiumCrownWrap: {
    position: "absolute",
    left: 50,
    top: -10,
    zIndex: 40,
    pointerEvents: "none",
  },
  listCardForeground: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    zIndex: 2,
  },
  listRank: {
    width: 32,
    textAlign: "center",
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  listMain: {
    flex: 1,
    minWidth: 0,
  },
  listNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  listName: {
    flexShrink: 1,
    color: "rgba(248,250,252,0.94)",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    ...Platform.select({
      ios: {
        textShadowColor: "rgba(0,0,0,0.35)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 12,
      },
      default: {},
    }),
  },
  listNamePodium: {
    fontSize: 16,
  },
  listValueOuter: {
    flexShrink: 0,
    minWidth: 96,
    /** Web のスコア列 `auto` に寄せ、右約34〜38%の国旗エリアがスコアに隠れないようにする */
    maxWidth: "34%",
    paddingLeft: 4,
    justifyContent: "center",
  },
  listValueOuterPodium: {
    minWidth: 84,
    maxWidth: "34%",
    alignItems: "flex-end",
  },
  listValueCol: {
    alignItems: "flex-end",
    gap: 3,
    width: "100%",
  },
  listValueColPodium: {
    alignItems: "flex-end",
  },
  listScoreRow: {
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "nowrap",
    justifyContent: "flex-end",
    gap: 2,
  },
  listScoreRowPodium: {
    justifyContent: "flex-end",
  },
  listScoreMain: {
    fontWeight: "700",
    fontFamily: METRIC_FONT,
  },
  listScoreSuffix: {
    fontWeight: "700",
    fontFamily: METRIC_FONT,
    marginLeft: 1,
  },
  listSubRight: {
    fontSize: 10,
    lineHeight: 13,
    color: "rgba(148,163,184,0.9)",
    fontFamily: METRIC_FONT,
    textAlign: "right",
    maxWidth: "100%",
  },
  listSubRightPodium: {
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(255,255,255,0.4)",
  },
});
