/**
 * コミュニティガイドライン（7言語）。
 */
import { L, Ls, resolveLocalizedLang } from "../../../../../lib/i18n/localize";

export function communityGuidelinesCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    description: L(lang, {
      ja: "スポーツ予想ファンタジーゲームを健全に楽しむために",
      en: "To enjoy this sports-prediction fantasy game in a healthy and fair way.",
      ko: "스포츠 예상 판타지 게임을 건전하게 즐기기 위해",
      zh: "为了健康、公平地享受体育预测幻想游戏",
      es: "Para disfrutar este fantasy de predicción deportiva de forma sana y justa.",
      pt: "Para aproveitar este fantasy de palpites esportivos de forma saudável e justa.",
      fr: "Pour profiter de ce fantasy de tips sportifs de façon saine et équitable.",
    }),
    lastUpdatedLabel: L(lang, {
      ja: "最終更新: ",
      en: "Last updated: ",
      ko: "최종 업데이트: ",
      zh: "最后更新：",
      es: "Última actualización: ",
      pt: "Última atualização: ",
      fr: "Dernière mise à jour : ",
    }),
    s1Title: L(lang, {
      ja: "1. Uniterz について",
      en: "1. About Uniterz",
      ko: "1. Uniterz 소개",
      zh: "1. 关于 Uniterz",
      es: "1. Sobre Uniterz",
      pt: "1. Sobre o Uniterz",
      fr: "1. À propos d’Uniterz",
    }),
    s1Paragraphs: Ls(lang, [
      {
        ja: "Uniterz はスポーツ試合の結果を予想し、スコアを競い合うファンタジーゲームです。試合ごとに勝敗・スコアを予想して投稿すると、結果に応じてポイントが付与され、ランキングやプロフィールに反映されます。",
        en: "Uniterz is a fantasy sports game where you predict match results and compete with scores.",
        ko: "Uniterz는 경기 결과를 예상하고 점수로 경쟁하는 판타지 게임입니다.",
        zh: "Uniterz 是一款预测比赛结果并以分数竞争的幻想体育游戏。",
        es: "Uniterz es un fantasy donde predices resultados y compites con puntuaciones.",
        pt: "Uniterz é um fantasy em que você palpite resultados e compete por pontos.",
        fr: "Uniterz est un fantasy où vous tippez les résultats et rivalisez au score.",
      },
      {
        ja: "金銭的リターンを目的としたサービスではなく、ゲーム内のポイントのみで競います。",
        en: "This is not for financial gain—only in-game points matter.",
        ko: "금전적 수익이 목적이 아니며 게임 내 포인트로만 경쟁합니다.",
        zh: "不以金钱回报为目的，仅以游戏内积分竞争。",
        es: "No busca ganancias económicas: solo importan los puntos del juego.",
        pt: "Não é para ganho financeiro — só importam os pontos do jogo.",
        fr: "Pas de gain financier — seuls les points in-game comptent.",
      },
    ]),
    s2Title: L(lang, {
      ja: "2. 公平なプレイ",
      en: "2. Fair Play",
      ko: "2. 공정한 플레이",
      zh: "2. 公平竞赛",
      es: "2. Juego limpio",
      pt: "2. Jogo limpo",
      fr: "2. Fair-play",
    }),
    s2Bullets: Ls(lang, [
      {
        ja: "1試合につき1回まで予想を投稿できます（試合開始後の投稿は無効）",
        en: "One prediction per match (submissions after tip-off are invalid).",
        ko: "경기당 예상 1회（시작 후 게시는 무효）",
        zh: "每场比赛仅可提交一次预测（开赛后提交无效）",
        es: "Una predicción por partido (tras el tip-off no cuenta).",
        pt: "Um palpite por partida (após o tip-off é inválido).",
        fr: "Un tip par match (après tip-off : invalide).",
      },
      {
        ja: "複数アカウントを用いた不正なスコア稼ぎは禁止です",
        en: "No score farming with multiple accounts.",
        ko: "다중 계정으로 점수 부풀리기 금지",
        zh: "禁止用多账户刷分",
        es: "Prohibido farmear puntos con varias cuentas.",
        pt: "Proibido farmar pontos com várias contas.",
        fr: "Interdit de farmer des points avec plusieurs comptes.",
      },
      {
        ja: "他人のアカウントを使用したり、なりすましたりすることは禁止です",
        en: "No impersonation or using others' accounts.",
        ko: "타인 계정 사용·사칭 금지",
        zh: "禁止冒用或使用他人账户",
        es: "Prohibido suplantar o usar cuentas ajenas.",
        pt: "Proibido se passar por outros ou usar contas alheias.",
        fr: "Interdit d’usurper ou d’utiliser le compte d’autrui.",
      },
      {
        ja: "システムの不具合を意図的に利用する行為は禁止です",
        en: "No intentional abuse of bugs.",
        ko: "시스템 버그 고의 악용 금지",
        zh: "禁止故意利用系统漏洞",
        es: "Prohibido abusar de bugs a propósito.",
        pt: "Proibido abusar de bugs de propósito.",
        fr: "Interdit d’abuser volontairement des bugs.",
      },
    ]),
    s3Title: L(lang, {
      ja: "3. プロフィール・表示名について",
      en: "3. Profiles / Display Names",
      ko: "3. 프로필·표시 이름",
      zh: "3. 资料 / 显示名",
      es: "3. Perfiles / nombres",
      pt: "3. Perfis / nomes",
      fr: "3. Profils / noms",
    }),
    s3Paragraphs: Ls(lang, [
      {
        ja: "プロフィールの表示名・ハンドル・自己紹介文は、他のユーザーに公開されます。以下の内容を含めることは禁止です。",
        en: "Display name, handle, and bio are public. Do not include:",
        ko: "표시 이름·핸들·소개는 공개됩니다. 다음에 해당하는 내용은 금지입니다.",
        zh: "显示名、句柄和简介公开可见。禁止包含：",
        es: "Nombre, handle y bio son públicos. No incluyas:",
        pt: "Nome, handle e bio são públicos. Não inclua:",
        fr: "Nom, handle et bio sont publics. N’incluez pas :",
      },
    ]),
    s3Bullets: Ls(lang, [
      {
        ja: "他者を攻撃・侮辱・差別する表現",
        en: "Attacks, insults, or discrimination.",
        ko: "타인 공격·모욕·차별 표현",
        zh: "攻击、侮辱或歧视言论",
        es: "Ataques, insultos o discriminación.",
        pt: "Ataques, insultos ou discriminação.",
        fr: "Attaques, insultes ou discrimination.",
      },
      {
        ja: "虚偽の肩書き・所属の詐称",
        en: "False titles or affiliations.",
        ko: "허위 직함·소속 사칭",
        zh: "虚假头衔或隶属关系",
        es: "Títulos o afiliaciones falsas.",
        pt: "Títulos ou afiliações falsas.",
        fr: "Titres ou affiliations faux.",
      },
      {
        ja: "外部サービスへの誘導（URL・連絡先の掲示など）",
        en: "Promoting external services (URLs, contact info).",
        ko: "외부 서비스 유도（URL·연락처 등）",
        zh: "引流到外部服务（URL、联系方式等）",
        es: "Promoción de servicios externos (URLs, contacto).",
        pt: "Promoção de serviços externos (URLs, contato).",
        fr: "Promotion de services externes (URLs, contact).",
      },
      {
        ja: "スパム・宣伝目的の文言",
        en: "Spam or ads.",
        ko: "스팸·광고 문구",
        zh: "垃圾信息或广告",
        es: "Spam o anuncios.",
        pt: "Spam ou anúncios.",
        fr: "Spam ou pubs.",
      },
    ]),
    s4Title: L(lang, {
      ja: "4. 禁止される行為",
      en: "4. Prohibited Acts",
      ko: "4. 금지 행위",
      zh: "4. 禁止行为",
      es: "4. Actos prohibidos",
      pt: "4. Atos proibidos",
      fr: "4. Actes interdits",
    }),
    s4Bullets: Ls(lang, [
      {
        ja: "他者や運営になりすます行為",
        en: "Impersonating users or staff.",
        ko: "타인·운영진 사칭",
        zh: "冒充用户或工作人员",
        es: "Suplantar usuarios o staff.",
        pt: "Se passar por usuários ou staff.",
        fr: "Usurper des utilisateurs ou le staff.",
      },
      {
        ja: "サービスの動作を妨害・悪用する行為（自動化アクセス、過剰リクエスト等）",
        en: "Disrupting the service (bots, excessive requests, etc.).",
        ko: "서비스 방해·악용（봇, 과도 요청 등）",
        zh: "干扰或滥用服务（自动化访问、过量请求等）",
        es: "Alterar el servicio (bots, peticiones excesivas, etc.).",
        pt: "Interromper o serviço (bots, pedidos excessivos, etc.).",
        fr: "Perturber le service (bots, requêtes excessives, etc.).",
      },
      {
        ja: "不正アクセスその他、法令に違反する行為",
        en: "Unauthorized access or anything illegal.",
        ko: "무단 접근 등 불법 행위",
        zh: "未经授权访问或其他违法行为",
        es: "Acceso no autorizado u otras ilegalidades.",
        pt: "Acesso não autorizado ou ilegalidades.",
        fr: "Accès non autorisé ou actes illégaux.",
      },
    ]),
    s5Title: L(lang, {
      ja: "5. 違反時の対応",
      en: "5. If Rules Are Broken",
      ko: "5. 위반 시 조치",
      zh: "5. 违规处理",
      es: "5. Si se rompen las reglas",
      pt: "5. Se as regras forem quebradas",
      fr: "5. En cas d’infraction",
    }),
    s5Paragraphs: Ls(lang, [
      {
        ja: "ガイドライン違反が確認された場合、以下のいずれかの対応を行うことがあります。",
        en: "If a violation is confirmed, we may:",
        ko: "가이드라인 위반이 확인되면 다음 조치를 할 수 있습니다.",
        zh: "若确认违反指南，我们可能采取以下措施：",
        es: "Si se confirma una infracción, podemos:",
        pt: "Se uma violação for confirmada, podemos:",
        fr: "Si une infraction est confirmée, nous pouvons :",
      },
    ]),
    s5Bullets: Ls(lang, [
      {
        ja: "軽度：警告・内容の修正依頼",
        en: "Mild: warning / request to fix.",
        ko: "경미: 경고·수정 요청",
        zh: "轻微：警告 / 要求修改",
        es: "Leve: aviso / pedir corrección.",
        pt: "Leve: aviso / pedido de correção.",
        fr: "Léger : avertissement / demande de correction.",
      },
      {
        ja: "中度：一時的な利用制限",
        en: "Moderate: temporary restriction.",
        ko: "중간: 일시 이용 제한",
        zh: "中度：临时限制使用",
        es: "Media: restricción temporal.",
        pt: "Média: restrição temporária.",
        fr: "Moyen : restriction temporaire.",
      },
      {
        ja: "重大：アカウント停止または永久BAN",
        en: "Severe: suspension or permanent ban.",
        ko: "중대: 계정 정지 또는 영구 BAN",
        zh: "严重：停用账户或永久封禁",
        es: "Grave: suspensión o ban permanente.",
        pt: "Grave: suspensão ou ban permanente.",
        fr: "Grave : suspension ou ban permanent.",
      },
    ]),
    s5After: Ls(lang, [
      {
        ja: "対応の内容・程度は、当社の判断により決定します。",
        en: "Severity and response are at our discretion.",
        ko: "조치 내용·정도는 당사 판단에 따릅니다.",
        zh: "处理内容与程度由本公司酌情决定。",
        es: "La gravedad y la respuesta quedan a nuestra discreción.",
        pt: "A gravidade e a resposta ficam a nosso critério.",
        fr: "La gravité et la réponse sont à notre discrétion.",
      },
    ]),
    s6Title: L(lang, {
      ja: "6. サービスについて",
      en: "6. About the Service",
      ko: "6. 서비스 안내",
      zh: "6. 关于服务",
      es: "6. Sobre el servicio",
      pt: "6. Sobre o serviço",
      fr: "6. À propos du service",
    }),
    s6Paragraphs: Ls(lang, [
      {
        ja: "Uniterz のサービス内容・仕様は予告なく変更される場合があります。掲載されている試合情報・ランキング・ポイント計算などについて、正確性・完全性を保証するものではありません。",
        en: "Specs may change without notice. We don't guarantee accuracy of schedules, rankings, or points.",
        ko: "서비스·사양은 예고 없이 변경될 수 있으며, 일정·랭킹·포인트의 정확성을 보장하지 않습니다.",
        zh: "服务内容与规格可能变更且不另行通知。不保证赛程、排名或积分的准确性。",
        es: "Las specs pueden cambiar sin aviso. No garantizamos exactitud de calendarios, rankings o puntos.",
        pt: "As specs podem mudar sem aviso. Não garantimos precisão de agendas, rankings ou pontos.",
        fr: "Les specs peuvent changer sans préavis. Pas de garantie d’exactitude des calendriers, classements ou points.",
      },
      {
        ja: "すべてのユーザーが健全にゲームを楽しめるよう、本ガイドラインの遵守にご協力ください。",
        en: "Please follow these guidelines so everyone can enjoy the game.",
        ko: "모두가 건전하게 즐길 수 있도록 가이드라인을 지켜 주세요.",
        zh: "请遵守本指南，让所有人都能健康地享受游戏。",
        es: "Sigue estas guías para que todos disfruten el juego.",
        pt: "Siga estas diretrizes para que todos aproveitem o jogo.",
        fr: "Respectez ces règles pour que chacun puisse profiter du jeu.",
      },
    ]),
  };
}
