/**
 * 通知設定画面文言（7言語）。
 */
import type { PushNotificationPrefKey } from "@/lib/notifications/pushNotificationPrefs";
import { L, resolveLocalizedLang, type LocalizedLang } from "@/lib/i18n/localize";

export type NotificationSettingsLang = LocalizedLang;

type PrefRowCopy = {
  key: PushNotificationPrefKey;
  title: string;
  desc: string;
};

export function notificationSettingsCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    title: L(lang, {
      ja: "通知設定",
      en: "Notifications",
      ko: "알림 설정",
      zh: "通知设置",
      es: "Notificaciones",
      pt: "Notificações",
      fr: "Notifications",
    }),
    description: L(lang, {
      ja: "受け取る通知の種類を選べます。端末の通知がオフの場合は届きません。",
      en: "Choose which notifications you receive. They won't arrive if system notifications are off.",
      ko: "받을 알림 종류를 선택할 수 있습니다. 기기 알림이 꺼져 있으면 오지 않습니다.",
      zh: "可选择接收的通知类型。系统通知关闭时不会送达。",
      es: "Elige qué notificaciones recibir. No llegarán si las del sistema están off.",
      pt: "Escolha quais notificações receber. Não chegam se as do sistema estiverem off.",
      fr: "Choisissez les notifications. Elles n’arrivent pas si le système est désactivé.",
    }),
    osSection: L(lang, {
      ja: "端末の通知",
      en: "Device notifications",
      ko: "기기 알림",
      zh: "设备通知",
      es: "Notificaciones del dispositivo",
      pt: "Notificações do dispositivo",
      fr: "Notifications de l’appareil",
    }),
    osGranted: L(lang, {
      ja: "許可済み",
      en: "Allowed",
      ko: "허용됨",
      zh: "已允许",
      es: "Permitido",
      pt: "Permitido",
      fr: "Autorisé",
    }),
    osDenied: L(lang, {
      ja: "オフ（システム設定で変更）",
      en: "Off (change in system settings)",
      ko: "꺼짐（시스템 설정에서 변경）",
      zh: "关闭（在系统设置中更改）",
      es: "Off (cámbialo en ajustes del sistema)",
      pt: "Off (altere nas configurações do sistema)",
      fr: "Off (changez dans les réglages système)",
    }),
    osUnknown: L(lang, {
      ja: "未設定",
      en: "Not set",
      ko: "미설정",
      zh: "未设置",
      es: "Sin configurar",
      pt: "Não definido",
      fr: "Non défini",
    }),
    osUnavailable: L(lang, {
      ja: "このビルドでは利用できません",
      en: "Unavailable in this build",
      ko: "이 빌드에서는 사용할 수 없습니다",
      zh: "此构建不可用",
      es: "No disponible en esta build",
      pt: "Indisponível nesta build",
      fr: "Indisponible dans cette build",
    }),
    allowBtn: L(lang, {
      ja: "通知を許可",
      en: "Allow notifications",
      ko: "알림 허용",
      zh: "允许通知",
      es: "Permitir notificaciones",
      pt: "Permitir notificações",
      fr: "Autoriser les notifications",
    }),
    openSettingsBtn: L(lang, {
      ja: "システム設定を開く",
      en: "Open system settings",
      ko: "시스템 설정 열기",
      zh: "打开系统设置",
      es: "Abrir ajustes del sistema",
      pt: "Abrir configurações do sistema",
      fr: "Ouvrir les réglages système",
    }),
    matchSection: L(lang, {
      ja: "試合の進行",
      en: "Match progress",
      ko: "경기 진행",
      zh: "比赛进程",
      es: "Progreso del partido",
      pt: "Andamento da partida",
      fr: "Déroulement du match",
    }),
    matchHint: L(lang, {
      ja: "予想した試合の開始・結果・ランキングと、未予想の締切。",
      en: "Start, result, and rankings for matches you predicted — plus deadlines you haven't entered.",
      ko: "예약한 경기의 시작·결과·랭킹과, 미예상 마감.",
      zh: "你已预测比赛的开始、结果、排名，以及未预测的截止提醒。",
      es: "Inicio, resultado y ranking de partidos que predijiste — más plazos sin tip.",
      pt: "Início, resultado e ranking das partidas que você palpitou — e prazos sem tip.",
      fr: "Début, résultat et classement des matchs tippés — plus les deadlines manquantes.",
    }),
    deadlineSection: L(lang, {
      ja: "締切の何分前",
      en: "Minutes before deadline",
      ko: "마감 몇 분 전",
      zh: "截止前几分钟",
      es: "Minutos antes del plazo",
      pt: "Minutos antes do prazo",
      fr: "Minutes avant la deadline",
    }),
    deadlineFreeHint: L(lang, {
      ja: "Free は 30 分前。60 / 10 分前は Pro。",
      en: "Free is 30 min. Pro unlocks 60 / 10.",
      ko: "Free는 30분 전. 60 / 10분은 Pro.",
      zh: "Free 为 30 分钟。60 / 10 分钟需 Pro。",
      es: "Free: 30 min. Pro desbloquea 60 / 10.",
      pt: "Free: 30 min. Pro libera 60 / 10.",
      fr: "Free : 30 min. Pro débloque 60 / 10.",
    }),
    reviewSection: L(lang, {
      ja: "予想を見直す",
      en: "Recheck alerts",
      ko: "예상 재확인",
      zh: "复查提醒",
      es: "Alertas de revisión",
      pt: "Alertas de revisão",
      fr: "Alertes de relecture",
    }),
    reviewHintPro: L(lang, {
      ja: "欠場・先発など、予想を直すべき変化だけ。",
      en: "Only changes that warrant editing a prediction.",
      ko: "결장·선발 등 예상을 고쳐야 할 변화만.",
      zh: "仅在缺阵/首发等需要改预测时通知。",
      es: "Solo cambios que justifiquen editar una predicción.",
      pt: "Apenas mudanças que justifiquem editar um palpite.",
      fr: "Uniquement les changements qui justifient d’éditer un tip.",
    }),
    reviewHintFree: L(lang, {
      ja: "欠場・先発・Insight・月次レポートは Pro で届きます。",
      en: "Availability, lineup, Insight, and monthly report are Pro.",
      ko: "결장·선발·Insight·월간 리포트는 Pro.",
      zh: "缺阵、首发、Insight、月报为 Pro。",
      es: "Disponibilidad, alineación, Insight e informe mensual son Pro.",
      pt: "Disponibilidade, escalação, Insight e relatório mensal são Pro.",
      fr: "Disponibilité, composition, Insight et rapport mensuel sont Pro.",
    }),
    requesting: L(lang, {
      ja: "確認中…",
      en: "Checking…",
      ko: "확인 중…",
      zh: "确认中…",
      es: "Comprobando…",
      pt: "Verificando…",
      fr: "Vérification…",
    }),
    openSettingsFail: L(lang, {
      ja: "設定アプリを開けませんでした。",
      en: "Could not open settings.",
      ko: "설정 앱을 열 수 없습니다.",
      zh: "无法打开设置。",
      es: "No se pudieron abrir los ajustes.",
      pt: "Não foi possível abrir as configurações.",
      fr: "Impossible d’ouvrir les réglages.",
    }),
    minutesShort: L(lang, {
      ja: "分前",
      en: "m",
      ko: "분 전",
      zh: "分钟前",
      es: "m",
      pt: "m",
      fr: "m",
    }),
    matchRows: matchPrefRows(lang),
    proRows: proPrefRows(lang),
  };
}

function matchPrefRows(lang: LocalizedLang): PrefRowCopy[] {
  return [
    {
      key: "gameStart",
      title: L(lang, {
        ja: "試合開始（15分前）",
        en: "Match start (15 min before)",
        ko: "경기 시작（15분 전）",
        zh: "比赛开始（15分钟前）",
        es: "Inicio del partido (15 min antes)",
        pt: "Início da partida (15 min antes)",
        fr: "Début du match (15 min avant)",
      }),
      desc: L(lang, {
        ja: "予想した試合が始まる前にお知らせ",
        en: "Before a match you predicted is about to start",
        ko: "예약한 경기가 시작되기 전 알림",
        zh: "你预测的比赛即将开始时通知",
        es: "Antes de que empiece un partido que predijiste",
        pt: "Antes de começar uma partida que você palpitou",
        fr: "Avant le début d’un match que vous avez tippé",
      }),
    },
    {
      key: "gameFinal",
      title: L(lang, {
        ja: "結果確定",
        en: "Result confirmed",
        ko: "결과 확정",
        zh: "结果确认",
        es: "Resultado confirmado",
        pt: "Resultado confirmado",
        fr: "Résultat confirmé",
      }),
      desc: L(lang, {
        ja: "予想した試合の結果が確定したとき",
        en: "When a match you predicted is finalized",
        ko: "예약한 경기 결과가 확정될 때",
        zh: "你预测的比赛结果确定时",
        es: "Cuando se finaliza un partido que predijiste",
        pt: "Quando uma partida que você palpitou é finalizada",
        fr: "Quand un match tippé est finalisé",
      }),
    },
    {
      key: "rankingUpdated",
      title: L(lang, {
        ja: "ランキング更新",
        en: "Rankings updated",
        ko: "랭킹 업데이트",
        zh: "排名更新",
        es: "Rankings actualizados",
        pt: "Rankings atualizados",
        fr: "Classements mis à jour",
      }),
      desc: L(lang, {
        ja: "本日予想した日の累積ランキング更新（16:00頃）",
        en: "Daily ranking update on days you predicted (~4pm JST)",
        ko: "예약한 날의 누적 랭킹 업데이트（약 16:00 JST）",
        zh: "你有预测当日的累计排名更新（约 16:00 JST）",
        es: "Actualización diaria de ranking los días que predijiste (~16:00 JST)",
        pt: "Atualização diária de ranking nos dias que você palpitou (~16:00 JST)",
        fr: "Maj quotidienne du classement les jours tippés (~16h JST)",
      }),
    },
    {
      key: "predictionDeadline",
      title: L(lang, {
        ja: "予想締切",
        en: "Prediction deadline",
        ko: "예상 마감",
        zh: "预测截止",
        es: "Plazo de predicción",
        pt: "Prazo de palpite",
        fr: "Deadline de tip",
      }),
      desc: L(lang, {
        ja: "未予想の試合だけ。締切前にお知らせ",
        en: "Unpredicted matches only — before the deadline",
        ko: "미예상 경기만. 마감 전 알림",
        zh: "仅未预测的比赛 — 截止前通知",
        es: "Solo partidos sin tip — antes del plazo",
        pt: "Apenas partidas sem tip — antes do prazo",
        fr: "Matchs non tippés seulement — avant la deadline",
      }),
    },
  ];
}

function proPrefRows(lang: LocalizedLang): PrefRowCopy[] {
  return [
    {
      key: "injuryStatus",
      title: L(lang, {
        ja: "出場ステータス変更",
        en: "Availability change",
        ko: "출전 상태 변경",
        zh: "出场状态变更",
        es: "Cambio de disponibilidad",
        pt: "Mudança de disponibilidade",
        fr: "Changement de disponibilité",
      }),
      desc: L(lang, {
        ja: "欠場・復帰など、予想を見直すべき変化",
        en: "Out / return — changes that warrant a recheck",
        ko: "결장·복귀 등 예상을 재확인할 변화",
        zh: "缺阵/复出等需复查预测的变化",
        es: "Baja / regreso — cambios que merecen revisar",
        pt: "Fora / retorno — mudanças que pedem revisão",
        fr: "Absent / retour — changements à revérifier",
      }),
    },
    {
      key: "starterChange",
      title: L(lang, {
        ja: "重要な先発変更",
        en: "High-impact lineup change",
        ko: "중요 선발 변경",
        zh: "重要首发变更",
        es: "Cambio de alineación relevante",
        pt: "Mudança de escalação relevante",
        fr: "Changement de composition important",
      }),
      desc: L(lang, {
        ja: "主力落ち・控え先発。通常の先発発表は送らない",
        en: "Starters dropped / bench starts — not every lineup",
        ko: "주전 제외·벤치 선발. 일반 선발 발표는 보내지 않음",
        zh: "主力落选/替补首发 — 非每次首发公告",
        es: "Titulares caídos / banquillo — no cada alineación",
        pt: "Titulares fora / banco — não toda escalação",
        fr: "Titulaires sortis / banc — pas chaque composition",
      }),
    },
    {
      key: "pregameDigest",
      title: L(lang, {
        ja: "複数変化のまとめ",
        en: "Pregame digest",
        ko: "여러 변화 요약",
        zh: "赛前汇总",
        es: "Resumen prepartido",
        pt: "Resumo pré-jogo",
        fr: "Digest pré-match",
      }),
      desc: L(lang, {
        ja: "短時間の更新を1通にまとめる",
        en: "Bundle several updates into one notification",
        ko: "짧은 시간 업데이트를 1통으로 묶음",
        zh: "将短时间内的更新合并为一则",
        es: "Agrupa varias actualizaciones en una",
        pt: "Agrupa várias atualizações em uma",
        fr: "Regroupe plusieurs mises à jour en une",
      }),
    },
    {
      key: "proInsightUpdate",
      title: L(lang, {
        ja: "PRO INSIGHT 重要更新",
        en: "PRO INSIGHT update",
        ko: "PRO INSIGHT 중요 업데이트",
        zh: "PRO INSIGHT 重要更新",
        es: "Actualización PRO INSIGHT",
        pt: "Atualização PRO INSIGHT",
        fr: "Mise à jour PRO INSIGHT",
      }),
      desc: L(lang, {
        ja: "結論が変わったときだけ",
        en: "Only when the conclusion changes",
        ko: "결론이 바뀔 때만",
        zh: "仅在结论变化时",
        es: "Solo cuando cambia la conclusión",
        pt: "Somente quando a conclusão muda",
        fr: "Seulement si la conclusion change",
      }),
    },
    {
      key: "monthlyReport",
      title: L(lang, {
        ja: "月次レポート",
        en: "Monthly report",
        ko: "월간 리포트",
        zh: "月度报告",
        es: "Informe mensual",
        pt: "Relatório mensal",
        fr: "Rapport mensuel",
      }),
      desc: L(lang, {
        ja: "月次レポートが確定したとき",
        en: "When your monthly report is ready",
        ko: "월간 리포트가 준비됐을 때",
        zh: "月度报告就绪时",
        es: "Cuando tu informe mensual esté listo",
        pt: "Quando seu relatório mensal estiver pronto",
        fr: "Quand votre rapport mensuel est prêt",
      }),
    },
  ];
}
