/**
 * Native プロフィール設定シートの高可視文言（7言語）。
 */
import { L, resolveLocalizedLang, type LocalizedLang } from "../../../../../lib/i18n/localize";

export type ProfileSettingsSheetLang = LocalizedLang;
export const resolveProfileSettingsSheetLang = resolveLocalizedLang;

export function profileSettingsSheetCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    settingsTitle: L(lang, {
      ja: "プロフィール設定",
      en: "Profile Settings",
      ko: "프로필 설정",
      zh: "个人资料设置",
      es: "Ajustes de perfil",
      pt: "Configurações do perfil",
      fr: "Paramètres du profil",
    }),
    settingsSubtitle: L(lang, {
      ja: "アイコン・名前・自己紹介・使用言語・国を編集できます",
      en: "Edit your icon, name, bio, language, and country.",
      ko: "아이콘·이름·소개·언어·국가를 편집할 수 있습니다.",
      zh: "可编辑头像、名称、简介、语言和国家。",
      es: "Edita icono, nombre, bio, idioma y país.",
      pt: "Edite ícone, nome, bio, idioma e país.",
      fr: "Modifiez icône, nom, bio, langue et pays.",
    }),
    settingsClose: L(lang, {
      ja: "閉じる",
      en: "Close",
      ko: "닫기",
      zh: "关闭",
      es: "Cerrar",
      pt: "Fechar",
      fr: "Fermer",
    }),
    nameLabel: L(lang, {
      ja: "名前",
      en: "Name",
      ko: "이름",
      zh: "名称",
      es: "Nombre",
      pt: "Nome",
      fr: "Nom",
    }),
    namePlaceholder: L(lang, {
      ja: "名前",
      en: "Name",
      ko: "이름",
      zh: "名称",
      es: "Nombre",
      pt: "Nome",
      fr: "Nom",
    }),
    bio: L(lang, {
      ja: "自己紹介",
      en: "Bio",
      ko: "소개",
      zh: "简介",
      es: "Bio",
      pt: "Bio",
      fr: "Bio",
    }),
    bioPlaceholder: L(lang, {
      ja: "自己紹介",
      en: "Bio",
      ko: "소개",
      zh: "简介",
      es: "Bio",
      pt: "Bio",
      fr: "Bio",
    }),
    langLabel: L(lang, {
      ja: "使用言語",
      en: "App Language",
      ko: "앱 언어",
      zh: "应用语言",
      es: "Idioma de la app",
      pt: "Idioma do app",
      fr: "Langue de l’app",
    }),
    countryLabel: L(lang, {
      ja: "住んでいる国（任意）",
      en: "Country (optional)",
      ko: "거주 국가(선택)",
      zh: "所在国家（可选）",
      es: "País (opcional)",
      pt: "País (opcional)",
      fr: "Pays (facultatif)",
    }),
    countryNotSet: L(lang, {
      ja: "未設定",
      en: "Not set",
      ko: "미설정",
      zh: "未设置",
      es: "Sin definir",
      pt: "Não definido",
      fr: "Non défini",
    }),
    save: L(lang, {
      ja: "変更を保存",
      en: "Save Changes",
      ko: "변경 저장",
      zh: "保存更改",
      es: "Guardar cambios",
      pt: "Salvar alterações",
      fr: "Enregistrer",
    }),
    saving: L(lang, {
      ja: "保存中…",
      en: "Saving…",
      ko: "저장 중…",
      zh: "保存中…",
      es: "Guardando…",
      pt: "Salvando…",
      fr: "Enregistrement…",
    }),
    logout: L(lang, {
      ja: "ログアウト",
      en: "Log out",
      ko: "로그아웃",
      zh: "退出登录",
      es: "Cerrar sesión",
      pt: "Sair",
      fr: "Se déconnecter",
    }),
    invalidTitle: L(lang, {
      ja: "入力不正",
      en: "Invalid input",
      ko: "잘못된 입력",
      zh: "输入无效",
      es: "Entrada no válida",
      pt: "Entrada inválida",
      fr: "Saisie invalide",
    }),
    invalidName: L(lang, {
      ja: "名前は50文字以内で入力してください。",
      en: "Name must be 50 characters or fewer.",
      ko: "이름은 50자 이내로 입력하세요.",
      zh: "名称请控制在 50 个字符以内。",
      es: "El nombre debe tener 50 caracteres o menos.",
      pt: "O nome deve ter no máximo 50 caracteres.",
      fr: "Le nom doit comporter 50 caractères ou moins.",
    }),
    savedTitle: L(lang, {
      ja: "保存完了",
      en: "Saved",
      ko: "저장 완료",
      zh: "已保存",
      es: "Guardado",
      pt: "Salvo",
      fr: "Enregistré",
    }),
    savedBody: L(lang, {
      ja: "プロフィールを更新しました。",
      en: "Profile has been updated.",
      ko: "프로필이 업데이트되었습니다.",
      zh: "个人资料已更新。",
      es: "El perfil se ha actualizado.",
      pt: "O perfil foi atualizado.",
      fr: "Le profil a été mis à jour.",
    }),
    saveErrorTitle: L(lang, {
      ja: "保存エラー",
      en: "Save error",
      ko: "저장 오류",
      zh: "保存错误",
      es: "Error al guardar",
      pt: "Erro ao salvar",
      fr: "Erreur d’enregistrement",
    }),
    saveErrorBody: L(lang, {
      ja: "プロフィール更新に失敗しました。",
      en: "Failed to update profile.",
      ko: "프로필 업데이트에 실패했습니다.",
      zh: "更新个人资料失败。",
      es: "No se pudo actualizar el perfil.",
      pt: "Falha ao atualizar o perfil.",
      fr: "Échec de la mise à jour du profil.",
    }),
    pickPhotoTitle: L(lang, {
      ja: "写真へのアクセス",
      en: "Photo access",
      ko: "사진 접근",
      zh: "照片访问",
      es: "Acceso a fotos",
      pt: "Acesso a fotos",
      fr: "Accès aux photos",
    }),
    pickPhotoDenied: L(lang, {
      ja: "プロフィール写真を選ぶには、写真ライブラリへのアクセスを許可してください。",
      en: "Allow photo library access to choose a profile picture.",
      ko: "프로필 사진을 선택하려면 사진 라이브러리 접근을 허용하세요.",
      zh: "请允许访问照片库以选择头像。",
      es: "Permite el acceso a la biblioteca para elegir una foto de perfil.",
      pt: "Permita o acesso à biblioteca para escolher uma foto de perfil.",
      fr: "Autorisez l’accès à la photothèque pour choisir une photo de profil.",
    }),
    uploadAvatarFail: L(lang, {
      ja: "画像のアップロードに失敗しました。通信状況を確認して再度お試しください。",
      en: "Could not upload the image. Check your connection and try again.",
      ko: "이미지 업로드에 실패했습니다. 연결을 확인한 뒤 다시 시도하세요.",
      zh: "图片上传失败。请检查网络后重试。",
      es: "No se pudo subir la imagen. Revisa la conexión e inténtalo de nuevo.",
      pt: "Não foi possível enviar a imagem. Verifique a conexão e tente de novo.",
      fr: "Échec du téléversement. Vérifiez la connexion et réessayez.",
    }),
    imagePickerNativeTitle: L(lang, {
      ja: "写真の選択を使えません",
      en: "Photo picker unavailable",
      ko: "사진 선택 사용 불가",
      zh: "无法使用照片选择器",
      es: "Selector de fotos no disponible",
      pt: "Seletor de fotos indisponível",
      fr: "Sélecteur de photos indisponible",
    }),
    imagePickerNativeHint: L(lang, {
      ja: "expo-image-picker を組み込んだ開発ビルドが必要です。apps/native で `npx expo run:ios` または `npx expo run:android` を実行してアプリを再ビルドしてください。",
      en: "Rebuild the native app with expo-image-picker linked. From apps/native run `npx expo run:ios` or `npx expo run:android`.",
      ko: "expo-image-picker가 포함된 개발 빌드가 필요합니다. apps/native에서 `npx expo run:ios` 또는 `npx expo run:android`로 다시 빌드하세요.",
      zh: "需要包含 expo-image-picker 的开发构建。在 apps/native 运行 `npx expo run:ios` 或 `npx expo run:android`。",
      es: "Necesitas un build nativo con expo-image-picker. Desde apps/native ejecuta `npx expo run:ios` o `npx expo run:android`.",
      pt: "É preciso um build nativo com expo-image-picker. Em apps/native rode `npx expo run:ios` ou `npx expo run:android`.",
      fr: "Un build natif avec expo-image-picker est requis. Depuis apps/native lancez `npx expo run:ios` ou `npx expo run:android`.",
    }),
    changePhotoA11y: L(lang, {
      ja: "プロフィール写真を変更",
      en: "Change profile photo",
      ko: "프로필 사진 변경",
      zh: "更改头像",
      es: "Cambiar foto de perfil",
      pt: "Alterar foto do perfil",
      fr: "Changer la photo de profil",
    }),
    proBadge: "PRO",
    streakLabel: L(lang, {
      ja: "連勝",
      en: "Streak",
      ko: "연승",
      zh: "连胜",
      es: "Racha",
      pt: "Sequência",
      fr: "Série",
    }),
    playoffsTitle: "2026 NBA PLAYOFFS STATS",
    apiMissing: L(lang, {
      ja: "EXPO_PUBLIC_UNITERZ_API_BASE_URL を .env に設定し、Next.js を起動してください。",
      en: "Set EXPO_PUBLIC_UNITERZ_API_BASE_URL and run the Next.js app.",
      ko: "EXPO_PUBLIC_UNITERZ_API_BASE_URL을 .env에 설정하고 Next.js를 실행하세요.",
      zh: "请在 .env 设置 EXPO_PUBLIC_UNITERZ_API_BASE_URL 并启动 Next.js。",
      es: "Configura EXPO_PUBLIC_UNITERZ_API_BASE_URL y ejecuta la app Next.js.",
      pt: "Defina EXPO_PUBLIC_UNITERZ_API_BASE_URL e rode o app Next.js.",
      fr: "Définissez EXPO_PUBLIC_UNITERZ_API_BASE_URL et lancez l’app Next.js.",
    }),
    bracketSoon: L(lang, {
      ja: "プレーオフブラケットは Web 版と同様の表示を順次対応します。",
      en: "Playoff bracket view will match the web app in a future update.",
      ko: "플레이오프 브래킷은 웹과 동일한 표시를 순차 지원합니다.",
      zh: "季后赛对阵图将逐步对齐 Web 版显示。",
      es: "El bracket de playoffs coincidirá con la web en una actualización futura.",
      pt: "O bracket dos playoffs acompanhará o web em uma atualização futura.",
      fr: "Le bracket playoffs rejoindra le web dans une future mise à jour.",
    }),
    statsSoon: L(lang, {
      ja: "詳細分析（Pro）は Web 版でご利用いただけます。",
      en: "Pro analysis is available on the web app.",
      ko: "상세 분석(Pro)은 웹 앱에서 이용할 수 있습니다.",
      zh: "详细分析（Pro）可在 Web 版使用。",
      es: "El análisis Pro está disponible en la web.",
      pt: "A análise Pro está disponível no web.",
      fr: "L’analyse Pro est disponible sur le web.",
    }),
    userNotFound: L(lang, {
      ja: "ユーザーが見つかりません",
      en: "User not found",
      ko: "사용자를 찾을 수 없습니다",
      zh: "未找到用户",
      es: "Usuario no encontrado",
      pt: "Usuário não encontrado",
      fr: "Utilisateur introuvable",
    }),
    back: L(lang, {
      ja: "戻る",
      en: "Back",
      ko: "뒤로",
      zh: "返回",
      es: "Atrás",
      pt: "Voltar",
      fr: "Retour",
    }),
    backToMarkList: L(lang, {
      ja: "マークリストに戻る",
      en: "Back to MARK LIST",
      ko: "마크 리스트로 돌아가기",
      zh: "返回标记列表",
      es: "Volver a MARK LIST",
      pt: "Voltar à MARK LIST",
      fr: "Retour à MARK LIST",
    }),
    backToUserSearch: L(lang, {
      ja: "ユーザー検索に戻る",
      en: "Back to User Search",
      ko: "사용자 검색으로 돌아가기",
      zh: "返回用户搜索",
      es: "Volver a la búsqueda",
      pt: "Voltar à busca",
      fr: "Retour à la recherche",
    }),
  };
}
