/**
 * 予想採点ルール（BASE / BONUS / UPSET）— Web / Native 共有。
 */
import { L, resolveLocalizedLang, type LocalizedLang } from "@/lib/i18n/localize";

export type ScoringRulesLang = LocalizedLang;
export const resolveScoringRulesLang = resolveLocalizedLang;

export function scoringRulesCopy(lang: ScoringRulesLang) {
  return {
    headerHint: L(lang, {
      ja: "採点ルール",
      en: "How points are scored",
      ko: "채점 규칙",
      zh: "计分规则",
      es: "Cómo se puntúa",
      pt: "Como pontua",
      fr: "Comment ça compte",
    }),
    perGame: L(lang, {
      ja: "試合ごとのメイン点",
      en: "Per game",
      ko: "경기별 기본점",
      zh: "每场主分",
      es: "Por partido",
      pt: "Por jogo",
      fr: "Par match",
    }),
    addedOnTop: L(lang, {
      ja: "基本点に上乗せ",
      en: "Added on top",
      ko: "기본점에 가산",
      zh: "在基础分上叠加",
      es: "Sumado al base",
      pt: "Somado à base",
      fr: "Ajouté au base",
    }),
    separateMetric: L(lang, {
      ja: "別指標",
      en: "Separate metric",
      ko: "별도 지표",
      zh: "单独指标",
      es: "Métrica aparte",
      pt: "Métrica separada",
      fr: "Indicateur séparé",
    }),
    pts0: L(lang, {
      ja: "0点",
      en: "0",
      ko: "0점",
      zh: "0分",
      es: "0",
      pt: "0",
      fr: "0",
    }),
    upTo4: L(lang, {
      ja: "最大 +4",
      en: "up to +4",
      ko: "최대 +4",
      zh: "最高 +4",
      es: "hasta +4",
      pt: "até +4",
      fr: "jusqu’à +4",
    }),
    upTo2: L(lang, {
      ja: "最大 +2",
      en: "up to +2",
      ko: "최대 +2",
      zh: "最高 +2",
      es: "hasta +2",
      pt: "até +2",
      fr: "jusqu’à +2",
    }),
    ifHit: L(lang, {
      ja: "条件達成で加算",
      en: "if hit",
      ko: "적중 시 가산",
      zh: "命中时加算",
      es: "si aciertas",
      pt: "se acertar",
      fr: "si réussi",
    }),

    // --- Basketball BASE ---
    bbBaseIntro: L(lang, {
      ja: "勝者が当たったときだけ基本点が入ります。外すとその試合は0点です。",
      en: "Base points only apply when the winner is correct. Miss it and the game is 0.",
      ko: "승자를 맞힐 때만 기본점이 들어갑니다. 틀리면 해당 경기는 0점입니다.",
      zh: "仅在猜对胜者时计入基础分。猜错则本场为 0 分。",
      es: "Los puntos base solo aplican si aciertas el ganador. Si fallas, el partido vale 0.",
      pt: "Pontos base só valem se o vencedor estiver certo. Errar zera o jogo.",
      fr: "Les points de base ne s’appliquent que si le vainqueur est juste. Sinon, le match vaut 0.",
    }),
    bbWinnerMissHint: L(lang, {
      ja: "勝者を外すと連勝・アップセットのボーナスもつきません。",
      en: "No streak or upset bonuses on a missed winner.",
      ko: "승자를 틀리면 연승·업셋 보너스도 없습니다.",
      zh: "猜错胜者时，连胜与冷门加分也不计。",
      es: "Sin bonus de racha ni upset si fallas el ganador.",
      pt: "Sem bônus de sequência ou upset se errar o vencedor.",
      fr: "Pas de bonus de série ni d’upset si le vainqueur est raté.",
    }),
    bbWinnerHint: L(lang, {
      ja: "ホーム勝 / アウェイ勝",
      en: "Home or away winner",
      ko: "홈 승 / 원정 승",
      zh: "主队胜 / 客队胜",
      es: "Ganador local o visitante",
      pt: "Vencedor mandante ou visitante",
      fr: "Vainqueur domicile ou extérieur",
    }),
    bbMarginHint: L(lang, {
      ja: "得失点差のズレが小さいほど高い。誤差0で満点、15以上で0点（小数あり）。",
      en: "Closer margin → more points. Exact = max. Error 15+ → 0.",
      ko: "득실차 오차가 작을수록 높음. 오차 0이면 만점, 15 이상이면 0점.",
      zh: "分差误差越小分越高。误差 0 满分，15 以上为 0。",
      es: "Cuanto más cerca el margen, más puntos. Exacto = máx. Error 15+ → 0.",
      pt: "Quanto mais perto a margem, mais pontos. Exato = máx. Erro 15+ → 0.",
      fr: "Plus l’écart est proche, plus de points. Exact = max. Erreur 15+ → 0.",
    }),
    bbTotalHint: L(lang, {
      ja: "両チーム合計のズレが小さいほど高い。誤差0で満点、11以上で0点（小数あり）。",
      en: "Combined points. Exact = max. Error 11+ → 0.",
      ko: "양 팀 합계 오차가 작을수록 높음. 오차 0이면 만점, 11 이상이면 0점.",
      zh: "两队总分误差越小分越高。误差 0 满分，11 以上为 0。",
      es: "Puntos combinados. Exacto = máx. Error 11+ → 0.",
      pt: "Pontos combinados. Exato = máx. Erro 11+ → 0.",
      fr: "Points combinés. Exact = max. Erreur 11+ → 0.",
    }),
    bbBonusIntro: L(lang, {
      ja: "基本点に加算。合計は10点を超えることがあります。",
      en: "Stacked on base. Total can exceed 10.",
      ko: "기본점에 가산. 합계가 10점을 넘을 수 있습니다.",
      zh: "叠加在基础分上。总分可超过 10。",
      es: "Se suma al base. El total puede superar 10.",
      pt: "Somado à base. O total pode passar de 10.",
      fr: "Ajouté au base. Le total peut dépasser 10.",
    }),
    bbTopScorerHint: L(lang, {
      ja: "最多得点者を的中（勝者予想とは別枠）。",
      en: "Hit the game’s top scorer (separate from the winner pick).",
      ko: "최다 득점자 적중(승자 예상과 별도).",
      zh: "猜中全场得分王（与胜者预测分开）。",
      es: "Acertar el máximo anotador (aparte del ganador).",
      pt: "Acertar o cestinha (separado do vencedor).",
      fr: "Toucher le meilleur marqueur (séparé du vainqueur).",
    }),

    // --- Football BASE ---
    fbBaseIntro: L(lang, {
      ja: "採点スコアは規定時間＋延長（PKの本数は含みません）。勝者が外れると基本点は0点です。",
      en: "Line score is regulation + extra time (no penalty shootout goals). Miss the winner and base is 0.",
      ko: "채점 스코어는 정규+연장(PK 골 제외). 승자를 틀리면 기본점은 0입니다.",
      zh: "计分比分为常规时间+加时（不含点球大战进球）。猜错胜者则基础分为 0。",
      es: "El marcador es tiempo reglamentario + prórroga (sin penales). Si fallas el ganador, base = 0.",
      pt: "Placar = tempo regulamentar + prorrogação (sem pênaltis). Errar o vencedor zera a base.",
      fr: "Le score = temps réglementaire + prolongation (sans tirs au but). Vainqueur raté → base 0.",
    }),
    fbWinnerMissHintWithScorer: L(lang, {
      ja: "得点者ボーナスは別枠で加点あり。",
      en: "Goal-scorer bonus can still apply.",
      ko: "득점자 보너스는 별도로 가산될 수 있습니다.",
      zh: "进球者加分仍可单独计入。",
      es: "El bonus de goleador aún puede aplicar.",
      pt: "O bônus de artilheiro ainda pode valer.",
      fr: "Le bonus buteur peut encore s’appliquer.",
    }),
    fbWinnerMissHintNoScorer: L(lang, {
      ja: "ボーナスもつきません。",
      en: "No bonuses either.",
      ko: "보너스도 없습니다.",
      zh: "加分也不计。",
      es: "Tampoco hay bonus.",
      pt: "Sem bônus também.",
      fr: "Pas de bonus non plus.",
    }),
    fbHomeHint: L(lang, {
      ja: "ホーム得点が完全一致。",
      en: "Exact home goals.",
      ko: "홈 득점 완전 일치.",
      zh: "主队进球完全一致。",
      es: "Goles locales exactos.",
      pt: "Gols mandante exatos.",
      fr: "Buts domicile exacts.",
    }),
    fbAwayHint: L(lang, {
      ja: "アウェイ得点が完全一致。",
      en: "Exact away goals.",
      ko: "원정 득점 완전 일치.",
      zh: "客队进球完全一致。",
      es: "Goles visitantes exactos.",
      pt: "Gols visitante exatos.",
      fr: "Buts extérieur exacts.",
    }),
    fbMarginHint: L(lang, {
      ja: "得失点差が完全一致。例）1–1 vs 0–0 は引き分け+4と差+2で基本6点。",
      en: "Exact goal difference. e.g. 1–1 vs 0–0 → draw +4 and margin +2 = base 6.",
      ko: "득실차 완전 일치. 예: 1–1 vs 0–0 → 무승부 +4 + 차 +2 = 기본 6.",
      zh: "净胜球完全一致。例：1–1 vs 0–0 → 平局+4 + 分差+2 = 基础 6。",
      es: "Diferencia exacta. Ej.: 1–1 vs 0–0 → empate +4 y margen +2 = base 6.",
      pt: "Diferença exata. Ex.: 1–1 vs 0–0 → empate +4 e margem +2 = base 6.",
      fr: "Écart exact. Ex. : 1–1 vs 0–0 → nul +4 et écart +2 = base 6.",
    }),
    fbMarginHintShort: L(lang, {
      ja: "得失点差が完全一致。",
      en: "Exact goal difference.",
      ko: "득실차 완전 일치.",
      zh: "净胜球完全一致。",
      es: "Diferencia de goles exacta.",
      pt: "Diferença de gols exata.",
      fr: "Écart de buts exact.",
    }),
    fbBonusIntro: L(lang, {
      ja: "基本点に加算します。",
      en: "Stacked on base points.",
      ko: "기본점에 가산합니다.",
      zh: "叠加在基础分上。",
      es: "Se suma a los puntos base.",
      pt: "Somado aos pontos base.",
      fr: "Ajouté aux points de base.",
    }),
    fbGoalScorerHint: L(lang, {
      ja: "ゴールする選手を1人的中（オウンゴール除く。勝者予想とは別枠）。",
      en: "Pick one scorer. Own goals excluded. Separate from winner.",
      ko: "득점 선수 1명 적중(자책골 제외. 승자와 별도).",
      zh: "猜中一名进球者（不含乌龙球，与胜者分开）。",
      es: "Acertar un goleador. Sin autogoles. Aparte del ganador.",
      pt: "Acertar um artilheiro. Sem gols contra. Separado do vencedor.",
      fr: "Toucher un buteur. Hors CSC. Séparé du vainqueur.",
    }),

    // --- Shared bonus / upset ---
    upsetHint: L(lang, {
      ja: "市場の偏りが45%以下の側を的中した番狂わせ。",
      en: "Hit the market side at 45% or below.",
      ko: "시장 편중이 45% 이하인 쪽을 맞힌 업셋.",
      zh: "猜中市场占比 ≤45% 的一侧（冷门）。",
      es: "Acertar el lado del mercado al 45% o menos.",
      pt: "Acertar o lado do mercado com 45% ou menos.",
      fr: "Toucher le côté marché à 45 % ou moins.",
    }),
    streakHint: L(lang, {
      ja: "3〜4連勝 +1 · 5〜6連勝 +2 · 7連勝以上 +3。2連勝以下は0点。",
      en: "3–4 wins +1 · 5–6 +2 · 7+ +3. Two or fewer = 0.",
      ko: "3–4연승 +1 · 5–6 +2 · 7+ +3. 2연승 이하는 0.",
      zh: "3–4 连胜 +1 · 5–6 +2 · 7+ +3。2 连胜及以下为 0。",
      es: "3–4 victorias +1 · 5–6 +2 · 7+ +3. Dos o menos = 0.",
      pt: "3–4 vitórias +1 · 5–6 +2 · 7+ +3. Duas ou menos = 0.",
      fr: "3–4 victoires +1 · 5–6 +2 · 7+ +3. Deux ou moins = 0.",
    }),
    upsetPtsIntro: L(lang, {
      ja: "総合得点の UPSET +2 とは別。少数派を当てたときの加点です。",
      en: "Separate from the +2 upset bonus on total score.",
      ko: "종합득점의 UPSET +2와 별개. 소수파를 맞힐 때 가점입니다.",
      zh: "与总分中的 UPSET +2 分开。猜中少数派时的加分。",
      es: "Aparte del bonus upset +2 en la puntuación total.",
      pt: "Separado do bônus upset +2 na pontuação total.",
      fr: "Séparé du bonus upset +2 sur le score total.",
    }),
    upsetHitHint: L(lang, {
      ja: "市場45%以下の少数派を的中したとき。",
      en: "Minority side at 45% or below, and you hit it.",
      ko: "시장 45% 이하 소수파를 맞힐 때.",
      zh: "猜中市场占比 ≤45% 的少数派时。",
      es: "Cuando aciertas el lado minoritario ≤45%.",
      pt: "Quando acertar o lado minoritário ≤45%.",
      fr: "Quand vous touchez le côté minoritaire ≤45 %.",
    }),
    upsetScaleHint: L(lang, {
      ja: "多数派が55%未満は0点。55〜90%は支持率に応じて加点。90%以上は10点。",
      en: "Majority under 55% → 0. 55–90% scales up. 90%+ → 10.",
      ko: "다수파 55% 미만 → 0. 55–90%는 지지율에 따라 가점. 90%+ → 10.",
      zh: "多数派不足 55% → 0。55–90% 按支持率加分。90%+ → 10。",
      es: "Mayoría bajo 55% → 0. 55–90% escala. 90%+ → 10.",
      pt: "Maioria abaixo de 55% → 0. 55–90% escala. 90%+ → 10.",
      fr: "Majorité sous 55 % → 0. 55–90 % scale. 90 %+ → 10.",
    }),
  };
}

export type ScoringRulesCopy = ReturnType<typeof scoringRulesCopy>;
