export type AnalysisTypeId =
  // Tier 1
  | "COMPLETE_PLAYER"
  | "ELITE_ALLROUNDER"

  // S=3
  | "ELITE_CLOSER"
  | "RELIABLE_PRO"
  | "IRON_RUNNER"
  | "PRECISE_CLOSER"
  | "CONFIDENT_FINISHER"
  | "DATA_GRINDER"
  | "PROBABILITY_READER"
  | "STABLE_ANALYST"
  | "GIANT_SLAYER"
  | "SHARP_UPSETTER"
  | "CHAOS_ENGINE"
  | "ACCURACY_CONTROLLER"
  | "CONSISTENT_PRODUCER"

  // S=2
  | "SHARP_EXECUTOR"
  | "MOMENTUM_EDGE"
  | "RELENTLESS_OUTPUT"
  | "CONFIDENCE_DOMINANCE"
  | "HIGH_RISK_READER"
  | "DATA_FORGE"
  | "RHYTHM_BLADE"
  | "PROBABILITY_COMMANDER"
  | "VOLATILE_READER"
  | "BOLD_STRIKER"
  | "EDGE_HUNTER"
  | "CHAOS_SURGE"
  | "BOLD_READER"
  | "ENDURANCE_CORE"
  | "ACCURACY_ENGINE"
  | "RISK_ENGINE"

  // S=1
  | "CLEAN_HIT"
  | "SHARP_EYE"
  | "CHAOS_TAKER"
  | "HIGH_ACTIVITY"
  | "HOT_PHASE"
  | "ACCURACY_PATH"
  | "VOLATILE_PATH"

  // S=0
  | "RAW"
  | "UNSTABLE"
  | "FOUNDATION"
  | "BASELINE"

  // fallback
  | "WILD_CARD";

export type AnalysisTypeMeta = {
  label: string;
  description: string;
};