export type AnalysisTypeId =
  // Tier 1
  | "COMPLETE_PLAYER"
  | "ELITE_ALLROUNDER"

  // S=3
  | "ELITE_CLOSER"
  | "RELIABLE_PRO"
  | "IRON_RUNNER"
  | "SAFE_CLOSER"
  | "Hot_Hand"
  | "DATA_GRINDER"
  | "MODEL_FOLLOWER"
  | "STABLE_ANALYST"
  | "GIANT_SLAYER"
  | "SHARP_UPSETTER"
  | "CHAOS_ENGINE"
  | "PUBLIC_CONTROLLER"
  | "SAFE_PRODUCER"

  // S=2
  | "SHARP_EXECUTOR"
  | "MOMENTUM_EDGE"
  | "RELENTLESS_OUTPUT"
  | "SAFE_DOMINANCE"
  | "CROWD_BREAKER"
  | "DATA_FORGE"
  | "RHYTHM_BLADE"
  | "MODEL_COMMANDER"
  | "LINE_CUTTER"
  | "BOLD_STRIKER"
  | "EDGE_HUNTER"
  | "CHAOS_SURGE"
  | "FADE_ASSASSIN"
  | "ENDURANCE_CORE"
  | "PUBLIC_ENGINE"
  | "DARK_ENGINE"

  // S=1
  | "CLEAN_HIT"
  | "SHARP_EYE"
  | "CHAOS_TAKER"
  | "HIGH_ACTIVITY"
  | "HOT_PHASE"
  | "PUBLIC_PATH"
  | "CROWD_FADE"

  // S=0
  | "RAW"
  | "UNSTABLE"
  | "FOUNDATION"
  | "BASELINE"

  // fallback
  | "WILD_CARD";
