/**
 * 通知設定画面文言（7言語）。
 */
import type { PushNotificationPrefKey } from "@/lib/notifications/pushNotificationPrefs";
import { L, resolveLocalizedLang, type LocalizedLang } from "@/lib/i18n/localize";

export type NotificationSettingsLang = LocalizedLang;

type PrefRowCopy = {
  key: PushNotificationPrefKey;
  title: string;
  desc: string;
};

export function notificationSettingsCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    title: L(lang, {
      ja: "通知設定",
      en: "Notifications",
      ko: "알림 설정",
      zh: "通知设置",
      es: "Notificaciones",
      pt: "Notificações",
      fr: "Notifications",
    }),
    description: L(lang, {
      ja: "受け取る通知の種類を選べます。端末の通知がオフの場合は届きません。",
      en: "Choose which notifications you receive. They won't arrive if system notifications are off.",
      ko: "받을 알림 종류를 선택할 수 있습니다. 기기 알림이 꺼져 있으면 오지 않습니다.",
      zh: "可选择接收的通知类型。系统通知关闭时不会送达。",
      es: "Elige qué notificaciones recibir. No llegarán si las del sistema están off.",
      pt: "Escolha quais notificações receber. Não chegam se as do sistema estiverem off.",
      fr: "Choisissez les notifications. Elles n’arrivent pas si le système est désactivé.",
    }),
    /** Web: 配信先セクション */
    deliverySection: L(lang, {
      ja: "配信先",
      en: "Delivery",
      ko: "수신처",
      zh: "送达方式",
      es: "Entrega",
      pt: "Entrega",
      fr: "Livraison",
    }),
    deliveryHint: L(lang, {
      ja: "プッシュはアプリ側の端末通知がオンのときに届きます。種類はここで選べます。",
      en: "Pushes land when device notifications are on in the app. Types are chosen here.",
      ko: "앱 기기 알림이 켜져 있을 때 푸시가 옵니다. 종류는 여기서 고릅니다.",
      zh: "应用端设备通知开启时才会推送。类型在此选择。",
      es: "Los pushes llegan con notificaciones del dispositivo on. Los tipos se eligen aquí.",
      pt: "Pushes chegam com notificações do dispositivo on. Os tipos se escolhem aqui.",
      fr: "Les pushes arrivent si les notifs appareil sont on. Les types se choisissent ici.",
    }),
    signIn: L(lang, {
      ja: "ログインすると保存できます。",
      en: "Sign in to save these settings.",
      ko: "로그인하면 저장할 수 있습니다.",
      zh: "登录后可保存这些设置。",
      es: "Inicia sesión para guardar estos ajustes.",
      pt: "Entre para salvar estas configurações.",
      fr: "Connectez-vous pour enregistrer ces réglages.",
    }),
    osSection: L(lang, {
      ja: "端末の通知",
      en: "Device notifications",
      ko: "기기 알림",
      zh: "设备通知",
      es: "Notificaciones del dispositivo",
      pt: "Notificações do dispositivo",
      fr: "Notifications de l’appareil",
    }),
    osGranted: L(lang, {
      ja: "許可済み",
      en: "Allowed",
      ko: "허용됨",
      zh: "已允许",
      es: "Permitido",
      pt: "Permitido",
      fr: "Autorisé",
    }),
    osDenied: L(lang, {
      ja: "オフ（システム設定で変更）",
      en: "Off (change in system settings)",
      ko: "꺼짐（시스템 설정에서 변경）",
      zh: "关闭（在系统设置中更改）",
      es: "Off (cámbialo en ajustes del sistema)",
      pt: "Off (altere nas configurações do sistema)",
      fr: "Off (changez dans les réglages système)",
    }),
    osUnknown: L(lang, {
      ja: "未設定",
      en: "Not set",
      ko: "미설정",
      zh: "未设置",
      es: "Sin configurar",
      pt: "Não definido",
      fr: "Non défini",
    }),
    osUnavailable: L(lang, {
      ja: "このビルドでは利用できません",
      en: "Unavailable in this build",
      ko: "이 빌드에서는 사용할 수 없습니다",
      zh: "此构建不可用",
      es: "No disponible en esta build",
      pt: "Indisponível nesta build",
      fr: "Indisponible dans cette build",
    }),
    allowBtn: L(lang, {
      ja: "通知を許可",
      en: "Allow notifications",
      ko: "알림 허용",
      zh: "允许通知",
      es: "Permitir notificaciones",
      pt: "Permitir notificações",
      fr: "Autoriser les notifications",
    }),
    openSettingsBtn: L(lang, {
      ja: "システム設定を開く",
      en: "Open system settings",
      ko: "시스템 설정 열기",
      zh: "打开系统设置",
      es: "Abrir ajustes del sistema",
      pt: "Abrir configurações do sistema",
      fr: "Ouvrir les réglages système",
    }),
    matchSection: L(lang, {
      ja: "試合の進行",
      en: "Match progress",
      ko: "경기 진행",
      zh: "比赛进程",
      es: "Progreso del partido",
      pt: "Andamento da partida",
      fr: "Déroulement du match",
    }),
    matchHint: L(lang, {
      ja: "予想した試合の結果・Unit、未予想の締切まとめ。",
      en: "Results and Units for matches you predicted — plus batched deadlines.",
      ko: "예약한 경기의 결과·Unit, 미예측 마감 요약.",
      zh: "已预测比赛的结果与 Unit，以及未预测截止汇总。",
      es: "Resultados y Units de partidos tipados — más plazos agrupados.",
      pt: "Resultados e Units das partidas tipadas — e prazos agrupados.",
      fr: "Résultats et Units des matchs tippés — plus deadlines groupées.",
    }),
    deadlineSection: L(lang, {
      ja: "締切の何分前",
      en: "Minutes before deadline",
      ko: "마감 몇 분 전",
      zh: "截止前几分钟",
      es: "Minutos antes del plazo",
      pt: "Minutos antes do prazo",
      fr: "Minutes avant la deadline",
    }),
    deadlineFreeHint: L(lang, {
      ja: "Free は 30 分前。60 / 10 分前は Pro。",
      en: "Free is 30 min. Pro unlocks 60 / 10.",
      ko: "Free는 30분 전. 60 / 10분은 Pro.",
      zh: "Free 为 30 分钟。60 / 10 分钟需 Pro。",
      es: "Free: 30 min. Pro desbloquea 60 / 10.",
      pt: "Free: 30 min. Pro libera 60 / 10.",
      fr: "Free : 30 min. Pro débloque 60 / 10.",
    }),
    reviewSection: L(lang, {
      ja: "予想を見直す",
      en: "Recheck alerts",
      ko: "예상 재확인",
      zh: "复查提醒",
      es: "Alertas de revisión",
      pt: "Alertas de revisão",
      fr: "Alertes de relecture",
    }),
    reviewHintPro: L(lang, {
      ja: "欠場・Insight の重要読みなど、予想を直すべき変化だけ。",
      en: "Only availability / key Insight takes that warrant a recheck.",
      ko: "결장·Insight 중요 해석 등 예상을 고쳐야 할 변화만.",
      zh: "仅在缺阵 / Insight 重要解读等需要改预测时通知。",
      es: "Solo disponibilidad / lecturas clave de Insight que justifiquen revisar.",
      pt: "Apenas disponibilidade / leituras-chave de Insight que peçam revisão.",
      fr: "Uniquement disponibilité / lectures Insight clés à revérifier.",
    }),
    reviewHintFree: L(lang, {
      ja: "出場ステータス・Insight・週次/月次レポートは Pro で届きます。",
      en: "Availability, Insight, and weekly/monthly reports are Pro.",
      ko: "출전 상태·Insight·주간/월간 리포트는 Pro.",
      zh: "出场状态、Insight、周报/月报为 Pro。",
      es: "Disponibilidad, Insight e informes semanal/mensual son Pro.",
      pt: "Disponibilidade, Insight e relatórios semanal/mensal são Pro.",
      fr: "Disponibilité, Insight et rapports hebdo/mensuel sont Pro.",
    }),
    requesting: L(lang, {
      ja: "確認中…",
      en: "Checking…",
      ko: "확인 중…",
      zh: "确认中…",
      es: "Comprobando…",
      pt: "Verificando…",
      fr: "Vérification…",
    }),
    openSettingsFail: L(lang, {
      ja: "設定アプリを開けませんでした。",
      en: "Could not open settings.",
      ko: "설정 앱을 열 수 없습니다.",
      zh: "无法打开设置。",
      es: "No se pudieron abrir los ajustes.",
      pt: "Não foi possível abrir as configurações.",
      fr: "Impossible d’ouvrir les réglages.",
    }),
    minutesShort: L(lang, {
      ja: "分前",
      en: "m",
      ko: "분 전",
      zh: "分钟前",
      es: "m",
      pt: "m",
      fr: "m",
    }),
    matchRows: matchPrefRows(lang),
    proRows: proPrefRows(lang),
  };
}

function matchPrefRows(lang: LocalizedLang): PrefRowCopy[] {
  return [
    {
      key: "gameFinal",
      title: L(lang, {
        ja: "結果確定",
        en: "Result confirmed",
        ko: "결과 확정",
        zh: "结果确认",
        es: "Resultado confirmado",
        pt: "Resultado confirmado",
        fr: "Résultat confirmé",
      }),
      desc: L(lang, {
        ja: "予想した試合の結果が確定したとき（スコアは出ません）",
        en: "When a match you predicted is finalized (no score spoiler)",
        ko: "예약한 경기 결과가 확정될 때（스코어 없음）",
        zh: "你预测的比赛结果确定时（不含比分）",
        es: "Cuando se finaliza un partido tipado (sin marcador)",
        pt: "Quando uma partida tipada é finalizada (sem placar)",
        fr: "Quand un match tippé est finalisé (sans score)",
      }),
    },
    {
      key: "predictionDeadline",
      title: L(lang, {
        ja: "予想締切",
        en: "Prediction deadline",
        ko: "예상 마감",
        zh: "预测截止",
        es: "Plazo de predicción",
        pt: "Prazo de palpite",
        fr: "Deadline de tip",
      }),
      desc: L(lang, {
        ja: "未予想だけ。複数あるときは1通にまとめる",
        en: "Unpredicted only — batched into one when several",
        ko: "미예측만. 여러 개면 1통으로 묶음",
        zh: "仅未预测。多场时合并为一则",
        es: "Solo sin tip — varias se agrupan en una",
        pt: "Só sem tip — várias viram uma",
        fr: "Non tippés seulement — regroupés en une si plusieurs",
      }),
    },
    {
      key: "unitReward",
      title: L(lang, {
        ja: "Unit 付与",
        en: "Unit rewards",
        ko: "Unit 지급",
        zh: "Unit 发放",
        es: "Recompensas Unit",
        pt: "Recompensas Unit",
        fr: "Récompenses Unit",
      }),
      desc: L(lang, {
        ja: "週/月ランキングの Unit が付与されたとき",
        en: "When weekly/monthly ranking Units are granted",
        ko: "주/월 랭킹 Unit가 지급될 때",
        zh: "发放周/月排名 Unit 时",
        es: "Cuando se otorgan Units del ranking semanal/mensual",
        pt: "Quando Units do ranking semanal/mensal são concedidos",
        fr: "Quand des Units du classement hebdo/mensuel sont accordés",
      }),
    },
  ];
}

function proPrefRows(lang: LocalizedLang): PrefRowCopy[] {
  return [
    {
      key: "injuryStatus",
      title: L(lang, {
        ja: "出場ステータス変更",
        en: "Availability change",
        ko: "출전 상태 변경",
        zh: "出场状态变更",
        es: "Cambio de disponibilidad",
        pt: "Mudança de disponibilidade",
        fr: "Changement de disponibilité",
      }),
      desc: L(lang, {
        ja: "平均出場 25 分以上の選手の欠場・復帰など",
        en: "Out / return for players averaging 25+ minutes",
        ko: "평균 출전 25분 이상 선수의 결장·복귀 등",
        zh: "平均出场 25 分钟以上球员的缺阵/复出等",
        es: "Baja / regreso de jugadores con 25+ min de media",
        pt: "Fora / retorno de jogadores com média 25+ min",
        fr: "Absent / retour pour joueurs à 25+ min de moyenne",
      }),
    },
    {
      key: "proInsightUpdate",
      title: L(lang, {
        ja: "PRO INSIGHT 重要更新",
        en: "PRO INSIGHT update",
        ko: "PRO INSIGHT 중요 업데이트",
        zh: "PRO INSIGHT 重要更新",
        es: "Actualización PRO INSIGHT",
        pt: "Atualização PRO INSIGHT",
        fr: "Mise à jour PRO INSIGHT",
      }),
      desc: L(lang, {
        ja: "MATCHUP・欠場インパクトなど重要読みが変わったとき",
        en: "When key takes (MATCHUP / injury impact) change",
        ko: "MATCHUP·결장 임팩트 등 중요 해석이 바뀔 때",
        zh: "MATCHUP / 伤病影响等重要解读变化时",
        es: "Cuando cambian lecturas clave (MATCHUP / impacto de bajas)",
        pt: "Quando mudam leituras-chave (MATCHUP / impacto de lesões)",
        fr: "Quand les lectures clés (MATCHUP / impact blessures) changent",
      }),
    },
    {
      key: "weeklyReport",
      title: L(lang, {
        ja: "週次レポート",
        en: "Weekly report",
        ko: "주간 리포트",
        zh: "周报",
        es: "Informe semanal",
        pt: "Relatório semanal",
        fr: "Rapport hebdomadaire",
      }),
      desc: L(lang, {
        ja: "週次レポートが確定したとき",
        en: "When your weekly report is ready",
        ko: "주간 리포트가 준비됐을 때",
        zh: "周报就绪时",
        es: "Cuando tu informe semanal esté listo",
        pt: "Quando seu relatório semanal estiver pronto",
        fr: "Quand votre rapport hebdomadaire est prêt",
      }),
    },
    {
      key: "monthlyReport",
      title: L(lang, {
        ja: "月次レポート",
        en: "Monthly report",
        ko: "월간 리포트",
        zh: "月度报告",
        es: "Informe mensual",
        pt: "Relatório mensal",
        fr: "Rapport mensuel",
      }),
      desc: L(lang, {
        ja: "月次レポートが確定したとき",
        en: "When your monthly report is ready",
        ko: "월간 리포트가 준비됐을 때",
        zh: "月度报告就绪时",
        es: "Cuando tu informe mensual esté listo",
        pt: "Quando seu relatório mensal estiver pronto",
        fr: "Quand votre rapport mensuel est prêt",
      }),
    },
  ];
}
