/**
 * 交換 UI chrome（Hub / Apply / Progress）— 7言語
 */
import {
  L,
  resolveLocalizedLang,
  type LocalizedLang,
} from "@/lib/i18n/localize";

export function redemptionHubUiCopy(language: LocalizedLang | string) {
  const lang = resolveLocalizedLang(language);
  return {
    subtitle: L(lang, {
      ja: "保有 Unit で NBA 関連商品と交換申請。審査後に購入し直送します。",
      en: "Redeem Units for NBA merchandise. After review, we purchase and ship direct to you.",
      ko: "보유 Unit으로 NBA 관련 상품 교환 신청. 심사 후 구매·직송합니다.",
      zh: "用持有 Unit 申请兑换 NBA 相关商品。审核后采购并直送。",
      es: "Canjea Units por merch NBA. Tras revisión, compramos y enviamos directo.",
      pt: "Troque Units por merch NBA. Após análise, compramos e enviamos direto.",
      fr: "Échangez des Units contre du merch NBA. Après revue, achat et envoi direct.",
    }),
    seasonLine: (used: number, cap: number) =>
      L(lang, {
        ja: `今シーズン ${used.toLocaleString("ja-JP")} / ${cap.toLocaleString("ja-JP")} Unit`,
        en: `Season ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        ko: `이번 시즌 ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Unit`,
        zh: `本赛季 ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Unit`,
        es: `Temporada ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        pt: `Temporada ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        fr: `Saison ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
      }),
    previewNote: L(lang, {
      ja: " · プレビュー（Unit ロックは弁護士後）",
      en: " · Preview (Unit lock pending counsel)",
      ko: " · 미리보기(Unit 잠금은 변호사 확인 후)",
      zh: " · 预览（Unit 锁定待法务确认）",
      es: " · Vista previa (bloqueo Unit pendiente)",
      pt: " · Prévia (bloqueio de Unit pendente)",
      fr: " · Aperçu (verrouillage Unit en attente)",
    }),
    apply: L(lang, {
      ja: "交換申請",
      en: "Apply",
      ko: "교환 신청",
      zh: "申请兑换",
      es: "Solicitar",
      pt: "Solicitar",
      fr: "Demander",
    }),
    history: L(lang, {
      ja: "Unit 履歴",
      en: "Unit history",
      ko: "Unit 기록",
      zh: "Unit 记录",
      es: "Historial de Units",
      pt: "Histórico de Units",
      fr: "Historique Units",
    }),
    catalog: L(lang, {
      ja: "カタログ",
      en: "Catalog",
      ko: "카탈로그",
      zh: "目录",
      es: "Catálogo",
      pt: "Catálogo",
      fr: "Catalogue",
    }),
    applyWithTier: L(lang, {
      ja: "この区分で申請",
      en: "Apply with this tier",
      ko: "이 구분으로 신청",
      zh: "用此档申请",
      es: "Solicitar con este nivel",
      pt: "Solicitar com este nível",
      fr: "Demander avec ce niveau",
    }),
    notEligible: L(lang, {
      ja: "対象外",
      en: "Not eligible",
      ko: "대상 제외",
      zh: "不适用",
      es: "No elegible",
      pt: "Não elegível",
      fr: "Non éligible",
    }),
    requests: L(lang, {
      ja: "申請一覧",
      en: "Your requests",
      ko: "신청 목록",
      zh: "申请列表",
      es: "Tus solicitudes",
      pt: "Seus pedidos",
      fr: "Vos demandes",
    }),
    loading: L(lang, {
      ja: "読み込み中…",
      en: "Loading…",
      ko: "불러오는 중…",
      zh: "加载中…",
      es: "Cargando…",
      pt: "Carregando…",
      fr: "Chargement…",
    }),
    noRequests: L(lang, {
      ja: "まだ申請がありません。",
      en: "No requests yet.",
      ko: "아직 신청이 없습니다.",
      zh: "还没有申请。",
      es: "Aún no hay solicitudes.",
      pt: "Ainda sem pedidos.",
      fr: "Pas encore de demandes.",
    }),
    track: L(lang, {
      ja: "進捗",
      en: "Track",
      ko: "진행",
      zh: "进度",
      es: "Seguimiento",
      pt: "Acompanhar",
      fr: "Suivi",
    }),
  };
}

export function redemptionApplyUiCopy(language: LocalizedLang | string) {
  const lang = resolveLocalizedLang(language);
  return {
    subtitle: L(lang, {
      ja: "希望商品と配送先を入力。審査後に購入・直送します。",
      en: "Enter product and shipping details. We purchase and ship after review.",
      ko: "희망 상품과 배송지를 입력. 심사 후 구매·직송합니다.",
      zh: "填写希望商品与收货地址。审核后采购并直送。",
      es: "Introduce producto y envío. Compramos y enviamos tras revisión.",
      pt: "Informe produto e entrega. Compramos e enviamos após análise.",
      fr: "Saisissez produit et livraison. Achat et envoi après revue.",
    }),
    backCatalog: L(lang, {
      ja: "カタログに戻る",
      en: "Back to catalog",
      ko: "카탈로그로",
      zh: "返回目录",
      es: "Volver al catálogo",
      pt: "Voltar ao catálogo",
      fr: "Retour au catalogue",
    }),
    available: (available: number, balance: number, reserved: number) =>
      L(lang, {
        ja: `利用可能 ${available.toLocaleString("ja-JP")} Unit（保有 ${balance.toLocaleString("ja-JP")} − 申請中 ${reserved.toLocaleString("ja-JP")}）`,
        en: `Available ${available.toLocaleString("en-US")} Units (held ${balance.toLocaleString("en-US")} − reserved ${reserved.toLocaleString("en-US")})`,
        ko: `사용 가능 ${available.toLocaleString("en-US")} Unit (보유 ${balance.toLocaleString("en-US")} − 신청 중 ${reserved.toLocaleString("en-US")})`,
        zh: `可用 ${available.toLocaleString("en-US")} Unit（持有 ${balance.toLocaleString("en-US")} − 申请中 ${reserved.toLocaleString("en-US")}）`,
        es: `Disponibles ${available.toLocaleString("en-US")} Units (saldo ${balance.toLocaleString("en-US")} − reservado ${reserved.toLocaleString("en-US")})`,
        pt: `Disponíveis ${available.toLocaleString("en-US")} Units (saldo ${balance.toLocaleString("en-US")} − reservado ${reserved.toLocaleString("en-US")})`,
        fr: `Disponibles ${available.toLocaleString("en-US")} Units (solde ${balance.toLocaleString("en-US")} − réservé ${reserved.toLocaleString("en-US")})`,
      }),
    seasonUsed: (used: number, cap: number) =>
      L(lang, {
        ja: `今シーズン交換 ${used.toLocaleString("ja-JP")} / ${cap.toLocaleString("ja-JP")} Unit`,
        en: `Season used ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        ko: `이번 시즌 교환 ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Unit`,
        zh: `本赛季兑换 ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Unit`,
        es: `Usado esta temporada ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        pt: `Usado na temporada ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
        fr: `Utilisé cette saison ${used.toLocaleString("en-US")} / ${cap.toLocaleString("en-US")} Units`,
      }),
    needUnits: (units: number, cap: string) =>
      L(lang, {
        ja: `必要 ${units} Unit · 価格上限 ${cap}`,
        en: `${units} Units · Cap ${cap}`,
        ko: `필요 ${units} Unit · 가격 상한 ${cap}`,
        zh: `需要 ${units} Unit · 价格上限 ${cap}`,
        es: `${units} Units · Tope ${cap}`,
        pt: `${units} Units · Teto ${cap}`,
        fr: `${units} Units · Plafond ${cap}`,
      }),
    productTier: L(lang, {
      ja: "商品区分",
      en: "Product tier",
      ko: "상품 구분",
      zh: "商品档位",
      es: "Nivel de producto",
      pt: "Nível do produto",
      fr: "Niveau produit",
    }),
    productName: L(lang, {
      ja: "商品名",
      en: "Product name",
      ko: "상품명",
      zh: "商品名",
      es: "Nombre del producto",
      pt: "Nome do produto",
      fr: "Nom du produit",
    }),
    productUrl: L(lang, {
      ja: "商品ページ URL",
      en: "Product URL",
      ko: "상품 페이지 URL",
      zh: "商品页面链接",
      es: "URL del producto",
      pt: "URL do produto",
      fr: "URL du produit",
    }),
    store: L(lang, {
      ja: "販売店",
      en: "Store",
      ko: "판매점",
      zh: "店铺",
      es: "Tienda",
      pt: "Loja",
      fr: "Boutique",
    }),
    size: L(lang, {
      ja: "サイズ",
      en: "Size",
      ko: "사이즈",
      zh: "尺码",
      es: "Talla",
      pt: "Tamanho",
      fr: "Taille",
    }),
    color: L(lang, {
      ja: "カラー",
      en: "Color",
      ko: "컬러",
      zh: "颜色",
      es: "Color",
      pt: "Cor",
      fr: "Couleur",
    }),
    notes: L(lang, {
      ja: "補足",
      en: "Notes",
      ko: "비고",
      zh: "备注",
      es: "Notas",
      pt: "Notas",
      fr: "Notes",
    }),
    productImage: L(lang, {
      ja: "商品画像（スクショ）※申請時必須",
      en: "Product screenshot (required to submit)",
      ko: "상품 이미지(스크린샷) ※신청 시 필수",
      zh: "商品截图（提交时必填）",
      es: "Captura del producto (obligatoria al enviar)",
      pt: "Print do produto (obrigatório ao enviar)",
      fr: "Capture produit (obligatoire à l’envoi)",
    }),
    productImageHint: L(lang, {
      ja: "販売ページの商品写真スクショを添付してください（審査用・8MB以下）。",
      en: "Attach a screenshot of the product page (for review, max 8MB).",
      ko: "판매 페이지 상품 사진 스크린샷을 첨부하세요(심사용·8MB 이하).",
      zh: "请附上商品页截图（供审核，最大 8MB）。",
      es: "Adjunta una captura de la página del producto (revisión, máx. 8 MB).",
      pt: "Anexe um print da página do produto (análise, máx. 8 MB).",
      fr: "Joignez une capture de la page produit (revue, max. 8 Mo).",
    }),
    pickImage: L(lang, {
      ja: "画像を選択",
      en: "Choose image",
      ko: "이미지 선택",
      zh: "选择图片",
      es: "Elegir imagen",
      pt: "Escolher imagem",
      fr: "Choisir une image",
    }),
    removeImage: L(lang, {
      ja: "削除",
      en: "Remove",
      ko: "삭제",
      zh: "删除",
      es: "Quitar",
      pt: "Remover",
      fr: "Retirer",
    }),
    needImageFile: L(lang, {
      ja: "画像ファイルを選んでください。",
      en: "Please choose an image file.",
      ko: "이미지 파일을 선택해 주세요.",
      zh: "请选择图片文件。",
      es: "Elige un archivo de imagen.",
      pt: "Escolha um arquivo de imagem.",
      fr: "Choisissez un fichier image.",
    }),
    imageTooLarge: L(lang, {
      ja: "画像は 8MB 以下にしてください。",
      en: "Image must be 8MB or less.",
      ko: "이미지는 8MB 이하여야 합니다.",
      zh: "图片须为 8MB 以下。",
      es: "La imagen debe ser de 8 MB o menos.",
      pt: "A imagem deve ter 8 MB ou menos.",
      fr: "L’image doit faire 8 Mo ou moins.",
    }),
    submitting: L(lang, {
      ja: "送信中…",
      en: "Submitting…",
      ko: "전송 중…",
      zh: "提交中…",
      es: "Enviando…",
      pt: "Enviando…",
      fr: "Envoi…",
    }),
    shipping: L(lang, {
      ja: "配送先",
      en: "Shipping",
      ko: "배송지",
      zh: "收货地址",
      es: "Envío",
      pt: "Entrega",
      fr: "Livraison",
    }),
    fullName: L(lang, {
      ja: "氏名",
      en: "Full name",
      ko: "성명",
      zh: "姓名",
      es: "Nombre completo",
      pt: "Nome completo",
      fr: "Nom complet",
    }),
    postalCode: L(lang, {
      ja: "郵便番号",
      en: "Postal code",
      ko: "우편번호",
      zh: "邮编",
      es: "Código postal",
      pt: "CEP",
      fr: "Code postal",
    }),
    address: L(lang, {
      ja: "住所",
      en: "Address",
      ko: "주소",
      zh: "地址",
      es: "Dirección",
      pt: "Endereço",
      fr: "Adresse",
    }),
    phone: L(lang, {
      ja: "電話",
      en: "Phone",
      ko: "전화",
      zh: "电话",
      es: "Teléfono",
      pt: "Telefone",
      fr: "Téléphone",
    }),
    country: L(lang, {
      ja: "国コード",
      en: "Country",
      ko: "국가 코드",
      zh: "国家代码",
      es: "País",
      pt: "País",
      fr: "Pays",
    }),
    terms: L(lang, {
      ja: "利用規約",
      en: "Terms",
      ko: "이용약관",
      zh: "服务条款",
      es: "Términos",
      pt: "Termos",
      fr: "Conditions",
    }),
    privacy: L(lang, {
      ja: "プライバシー",
      en: "Privacy",
      ko: "개인정보",
      zh: "隐私",
      es: "Privacidad",
      pt: "Privacidade",
      fr: "Confidentialité",
    }),
    submit: L(lang, {
      ja: "申請する",
      en: "Submit",
      ko: "신청",
      zh: "提交",
      es: "Enviar",
      pt: "Enviar",
      fr: "Envoyer",
    }),
    draft: L(lang, {
      ja: "下書き保存",
      en: "Save draft",
      ko: "초안 저장",
      zh: "保存草稿",
      es: "Guardar borrador",
      pt: "Salvar rascunho",
      fr: "Enregistrer le brouillon",
    }),
  };
}

export function redemptionProgressUiCopy(language: LocalizedLang | string) {
  const lang = resolveLocalizedLang(language);
  return {
    subtitle: L(lang, {
      ja: "申請から配送までの進捗を確認できます。",
      en: "Track your request from review through delivery.",
      ko: "신청부터 배송까지 진행을 확인할 수 있습니다.",
      zh: "可查看从申请到配送的进度。",
      es: "Sigue tu solicitud desde la revisión hasta la entrega.",
      pt: "Acompanhe do pedido à entrega.",
      fr: "Suivez de la revue à la livraison.",
    }),
    backHome: L(lang, {
      ja: "交換トップ",
      en: "Redeem home",
      ko: "교환 홈",
      zh: "兑换首页",
      es: "Inicio de canje",
      pt: "Início do resgate",
      fr: "Accueil échange",
    }),
    loading: L(lang, {
      ja: "読み込み中…",
      en: "Loading…",
      ko: "불러오는 중…",
      zh: "加载中…",
      es: "Cargando…",
      pt: "Carregando…",
      fr: "Chargement…",
    }),
    notFound: L(lang, {
      ja: "申請が見つかりません。",
      en: "Request not found.",
      ko: "신청을 찾을 수 없습니다.",
      zh: "未找到申请。",
      es: "Solicitud no encontrada.",
      pt: "Pedido não encontrado.",
      fr: "Demande introuvable.",
    }),
    tracking: L(lang, {
      ja: "追跡",
      en: "Tracking",
      ko: "배송 추적",
      zh: "物流追踪",
      es: "Seguimiento",
      pt: "Rastreio",
      fr: "Suivi",
    }),
    timeline: L(lang, {
      ja: "履歴",
      en: "Timeline",
      ko: "이력",
      zh: "时间线",
      es: "Historial",
      pt: "Linha do tempo",
      fr: "Historique",
    }),
    submitDraft: L(lang, {
      ja: "申請を送信",
      en: "Submit draft",
      ko: "신청 보내기",
      zh: "提交申请",
      es: "Enviar borrador",
      pt: "Enviar rascunho",
      fr: "Envoyer le brouillon",
    }),
    cancel: L(lang, {
      ja: "申請を取り消す",
      en: "Cancel request",
      ko: "신청 취소",
      zh: "取消申请",
      es: "Cancelar solicitud",
      pt: "Cancelar pedido",
      fr: "Annuler la demande",
    }),
  };
}
