/**
 * NBA プレイヤー詳細 chrome（7言語）。hintJa/hintEn 等カタログは非 ja → en。
 */
import { L, resolveLocalizedLang } from "@/lib/i18n/localize";

export function nbaPlayerDetailChrome(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    catalogJa: lang === "ja",
    homeAway: L(lang, {
      ja: "ホーム / アウェイ",
      en: "HOME / AWAY",
      ko: "홈 / 어웨이",
      zh: "主场 / 客场",
      es: "LOCAL / VISITANTE",
      pt: "CASA / FORA",
      fr: "DOMICILE / EXTÉRIEUR",
    }),
    vsOppAvg: L(lang, {
      ja: "対戦相手別（平均）",
      en: "VS OPPONENT (AVG)",
      ko: "상대별(평균)",
      zh: "对阵对手（平均）",
      es: "VS RIVAL (PROM)",
      pt: "VS ADVERSÁRIO (MÉD)",
      fr: "VS ADV. (MOY)",
    }),
    oppCol: L(lang, {
      ja: "相手",
      en: "OPP",
      ko: "상대",
      zh: "对手",
      es: "RIV",
      pt: "ADV",
      fr: "ADV",
    }),
    seasonAverages: L(lang, {
      ja: "シーズン平均",
      en: "SEASON AVERAGES",
      ko: "시즌 평균",
      zh: "赛季平均",
      es: "PROMEDIOS DE TEMPORADA",
      pt: "MÉDIAS DA TEMPORADA",
      fr: "MOYENNES DE SAISON",
    }),
    thisSeason: L(lang, {
      ja: "今季年俸",
      en: "THIS SEASON",
      ko: "이번 시즌 연봉",
      zh: "本季薪资",
      es: "ESTA TEMPORADA",
      pt: "ESTA TEMPORADA",
      fr: "CETTE SAISON",
    }),
    rem: L(lang, {
      ja: "残",
      en: "REM",
      ko: "잔여",
      zh: "剩余",
      es: "REST",
      pt: "REST",
      fr: "REST",
    }),
    total: L(lang, {
      ja: "総額",
      en: "TOTAL",
      ko: "총액",
      zh: "总额",
      es: "TOTAL",
      pt: "TOTAL",
      fr: "TOTAL",
    }),
    guar: L(lang, {
      ja: "残保証",
      en: "GUAR.",
      ko: "보장 잔여",
      zh: "剩余保障",
      es: "GAR.",
      pt: "GAR.",
      fr: "GAR.",
    }),
    contractStatus: L(lang, {
      ja: "契約ステータス",
      en: "CONTRACT STATUS",
      ko: "계약 상태",
      zh: "合同状态",
      es: "ESTADO DEL CONTRATO",
      pt: "STATUS DO CONTRATO",
      fr: "STATUT DU CONTRAT",
    }),
    freeAgent: L(lang, {
      ja: "契約満了 (FREE AGENT)",
      en: "FREE AGENT / EXPIRED",
      ko: "계약 만료 (FA)",
      zh: "合同到期（自由球员）",
      es: "AGENTE LIBRE / EXPIRADO",
      pt: "FA / EXPIRADO",
      fr: "AGENT LIBRE / EXPIRÉ",
    }),
    none: L(lang, {
      ja: "なし",
      en: "None",
      ko: "없음",
      zh: "无",
      es: "Ninguno",
      pt: "Nenhum",
      fr: "Aucun",
    }),
    age: L(lang, {
      ja: "年齢",
      en: "AGE",
      ko: "나이",
      zh: "年龄",
      es: "EDAD",
      pt: "IDADE",
      fr: "ÂGE",
    }),
    history: L(lang, {
      ja: "経歴",
      en: "HISTORY",
      ko: "경력",
      zh: "履历",
      es: "HISTORIAL",
      pt: "HISTÓRICO",
      fr: "HISTORIQUE",
    }),
    seasonAvgHint: L(lang, {
      ja: "今季の出場試合からの平均",
      en: "Season average from games played",
      ko: "이번 시즌 출전 경기 평균",
      zh: "本季出场比赛平均",
      es: "Promedio de partidos jugados esta temporada",
      pt: "Média dos jogos disputados nesta temporada",
      fr: "Moyenne des matchs joués cette saison",
    }),
  };
}
