export const NBA_TEAM_IDS: Record<string, string> = {
  "Atlanta Hawks": "nba-hawks",
  "Boston Celtics": "nba-celtics",
  "Brooklyn Nets": "nba-nets",
  "Charlotte Hornets": "nba-hornets",
  "Chicago Bulls": "nba-bulls",
  "Cleveland Cavaliers": "nba-cavaliers",
  "Dallas Mavericks": "nba-mavericks",
  "Denver Nuggets": "nba-nuggets",
  "Detroit Pistons": "nba-pistons",
  "Golden State Warriors": "nba-warriors",
  "Houston Rockets": "nba-rockets",
  "Indiana Pacers": "nba-pacers",
  "LA Clippers": "nba-clippers",
  "Los Angeles Lakers": "nba-lakers",
  "Memphis Grizzlies": "nba-grizzlies",
  "Miami Heat": "nba-heat",
  "Milwaukee Bucks": "nba-bucks",
  "Minnesota Timberwolves": "nba-timberwolves",
  "New Orleans Pelicans": "nba-pelicans",
  "New York Knicks": "nba-knicks",
  "Oklahoma City Thunder": "nba-thunder",
  "Orlando Magic": "nba-magic",
  "Philadelphia 76ers": "nba-76ers",
  "Phoenix Suns": "nba-suns",
  "Portland Trail Blazers": "nba-blazers",
  "Sacramento Kings": "nba-kings",
  "San Antonio Spurs": "nba-spurs",
  "Toronto Raptors": "nba-raptors",
  "Utah Jazz": "nba-jazz",
  "Washington Wizards": "nba-wizards",
};
