export const NBA_TEAM_NAME_BY_ID: Record<string, string> = {
  "nba-hawks": "Atlanta Hawks",
  "nba-celtics": "Boston Celtics",
  "nba-nets": "Brooklyn Nets",
  "nba-hornets": "Charlotte Hornets",
  "nba-bulls": "Chicago Bulls",
  "nba-cavaliers": "Cleveland Cavaliers",
  "nba-mavericks": "Dallas Mavericks",
  "nba-nuggets": "Denver Nuggets",
  "nba-pistons": "Detroit Pistons",
  "nba-warriors": "Golden State Warriors",
  "nba-rockets": "Houston Rockets",
  "nba-pacers": "Indiana Pacers",
  "nba-clippers": "LA Clippers",
  "nba-lakers": "Los Angeles Lakers",
  "nba-grizzlies": "Memphis Grizzlies",
  "nba-heat": "Miami Heat",
  "nba-bucks": "Milwaukee Bucks",
  "nba-timberwolves": "Minnesota Timberwolves",
  "nba-pelicans": "New Orleans Pelicans",
  "nba-knicks": "New York Knicks",
  "nba-thunder": "Oklahoma City Thunder",
  "nba-magic": "Orlando Magic",
  "nba-76ers": "Philadelphia 76ers",
  "nba-suns": "Phoenix Suns",
  "nba-blazers": "Portland Trail Blazers",
  "nba-kings": "Sacramento Kings",
  "nba-spurs": "San Antonio Spurs",
  "nba-raptors": "Toronto Raptors",
  "nba-jazz": "Utah Jazz",
  "nba-wizards": "Washington Wizards",
};
