// lib/team-ids.ts
export const TEAM_IDS: Record<string, string> = {
  // ===== J1 =====
  "北海道コンサドーレ札幌": "j1-hokkaido",
  "鹿島アントラーズ": "j1-kashima",
  "浦和レッズ": "j1-urawa",
  "柏レイソル": "j1-kashiwa",
  "FC東京": "j1-fctokyo",
  "東京ヴェルディ": "j1-verdy",
  "川崎フロンターレ": "j1-kawasaki",
  "横浜F・マリノス": "j1-marinos",
  "湘南ベルマーレ": "j1-shonan",
  "アルビレックス新潟": "j1-niigata",
  "名古屋グランパス": "j1-grampus",
  "京都サンガF.C.": "j1-kyoto",
  "ガンバ大阪": "j1-gamba",
  "セレッソ大阪": "j1-cerezo",
  "ヴィッセル神戸": "j1-kobe",
  "サンフレッチェ広島": "j1-hiroshima",
  "アビスパ福岡": "j1-fukuoka",
  "サガン鳥栖": "j1-tosu",
  "ジュビロ磐田": "j1-iwata",
  "FC町田ゼルビア": "j1-machida",

  // ===== B1 =====
  "レバンガ北海道": "b1-levanga",
  "秋田ノーザンハピネッツ": "b1-akita",
  "仙台89ERS": "b1-sendai",
  "宇都宮ブレックス": "b1-utsunomiya",
  "群馬クレインサンダーズ": "b1-gunma",
  "茨城ロボッツ": "b1-ibaraki",
  "千葉ジェッツ": "b1-chiba",
  "アルバルク東京": "b1-alvark",
  "サンロッカーズ渋谷": "b1-shibuya",
  "川崎ブレイブサンダース": "b1-kawasaki",
  "横浜ビー・コルセアーズ": "b1-yokohama",
  "信州ブレイブウォリアーズ": "b1-shinshu",
  "三遠ネオフェニックス": "b1-sanen",
  "シーホース三河": "b1-mikawa",
  "ファイティングイーグルス名古屋": "b1-fe-nagoya",
  "名古屋ダイヤモンドドルフィンズ": "b1-dolphins",
  "京都ハンナリーズ": "b1-kyoto",
  "大阪エヴェッサ": "b1-osaka",
  "島根スサノオマジック": "b1-shimane",
  "広島ドラゴンフライズ": "b1-hiroshima",
  "佐賀バルーナーズ": "b1-saga",
  "長崎ヴェルカ": "b1-nagasaki",
  "琉球ゴールデンキングス": "b1-ryukyu",
  "富山グラウジーズ": "b1-toyama",
  "福島ファイヤーボンズ": "b1-fukushima",
  "越谷アルファーズ": "b1-koshigaya",
  "滋賀レイクス": "b1-shiga",
};
