// lib/team-short.ts
export const TEAM_SHORT: Record<string, string> = {
// --- B1 ---
"b1-akita": "秋田",
"b1-altiri": "千葉A",     // アルティーリ千葉 → 千葉と被るのでA
"b1-alvark": "A東京",
"b1-chiba": "千葉J",      // 千葉ジェッツ
"b1-dolphins": "名古屋D",
"b1-fe-nagoya": "FE名古屋",
"b1-fukushima": "福島",
"b1-gunma": "群馬",
"b1-hiroshima": "広島",
"b1-ibaraki": "茨城",
"b1-kawasaki": "川崎",
"b1-koshigaya": "越谷",
"b1-kyoto": "京都",
"b1-levanga": "北海道",
"b1-mikawa": "三河",
"b1-nagasaki": "長崎",
"b1-osaka": "大阪E",    // エヴェッサ
"b1-ryukyu": "琉球",
"b1-saga": "佐賀",
"b1-sanen": "三遠",
"b1-sendai": "仙台",
"b1-shibuya": "渋谷",
"b1-shiga": "滋賀",
"b1-shimane": "島根",
"b1-shinshu": "信州",
"b1-toyama": "富山",
"b1-utsunomiya": "宇都宮",
"b1-yokohama": "横浜B",   // 横浜ビーコル

// --- J1 ---
"j1-urawa": "浦和",
"j1-kawasaki": "川崎F",
"j1-fctokyo": "FC東",
"j1-gamba": "G大阪",
"j1-cerezo": "C大阪",
"j1-kobe": "神戸",
"j1-kashiwa": "柏",
"j1-kashima": "鹿島",
"j1-fukuoka": "福岡",
"j1-hiroshima": "広島",
"j1-grampus": "名古屋",
"j1-iwata": "磐田",
"j1-yokohama": "横浜FM",
"j1-hokkaido": "札幌",
"j1-shonan": "湘南",
"j1-niigata": "新潟",
"j1-sagan": "鳥栖",
"j1-tosu": "鳥栖",    // 同じ表記でOK
"j1-kyoto": "京都",
"j1-vegalta": "仙台",  // 参考：昇降で変動するが対応用

// --- NBA Eastern ---
"nba-hawks": "ATL",
"nba-celtics": "BOS",
"nba-nets": "BKN",
"nba-hornets": "CHA",
"nba-bulls": "CHI",
"nba-cavaliers": "CLE",
"nba-mavericks": "DAL",
"nba-nuggets": "DEN",
"nba-pistons": "DET",
"nba-warriors": "GSW",
"nba-rockets": "HOU",
"nba-pacers": "IND",
"nba-clippers": "LAC",
"nba-lakers": "LAL",
"nba-grizzlies": "MEM",
"nba-heat": "MIA",
"nba-bucks": "MIL",
"nba-timberwolves": "MIN",
"nba-pelicans": "NOP",
"nba-knicks": "NYK",
"nba-thunder": "OKC",
"nba-magic": "ORL",
"nba-76ers": "PHI",
"nba-suns": "PHX",
"nba-blazers": "POR",
"nba-kings": "SAC",
"nba-spurs": "SAS",
"nba-raptors": "TOR",
"nba-jazz": "UTA",
"nba-wizards": "WAS",

// --- Premier League ---
"pl-arsenal": "ARS",
"pl-aston-villa": "AVL",
"pl-bournemouth": "BOU",
"pl-brentford": "BRE",
"pl-brighton": "BHA",
"pl-chelsea": "CHE",
"pl-crystal-palace": "CRY",
"pl-everton": "EVE",
"pl-fulham": "FUL",
"pl-ipswich": "IPS",
"pl-leicester": "LEI",
"pl-liverpool": "LIV",
"pl-man-city": "MCI",
"pl-man-united": "MUN",
"pl-newcastle": "NEW",
"pl-nottingham": "NFO",
"pl-southampton": "SOU",
"pl-tottenham": "TOT",
"pl-west-ham": "WHU",
"pl-wolves": "WOL",
"pl-sunderland": "SUN",
"pl-leeds": "LEE",
"pl-burnley": "BUR",
};