// lib/team-names-nba.ts
export const teamNameRulesNBA: Record<string, { line1: string; line2: string }> = {
  "Atlanta Hawks":            { line1: "Atlanta", line2: "Hawks" },
  "Boston Celtics":           { line1: "Boston", line2: "Celtics" },
  "Brooklyn Nets":            { line1: "Brooklyn", line2: "Nets" },
  "Charlotte Hornets":        { line1: "Charlotte", line2: "Hornets" },
  "Chicago Bulls":            { line1: "Chicago", line2: "Bulls" },
  "Cleveland Cavaliers":      { line1: "Cleveland", line2: "Cavaliers" },
  "Dallas Mavericks":         { line1: "Dallas", line2: "Mavericks" },
  "Denver Nuggets":           { line1: "Denver", line2: "Nuggets" },
  "Detroit Pistons":          { line1: "Detroit", line2: "Pistons" },
  "Golden State Warriors":    { line1: "Golden State", line2: "Warriors" },
  "Houston Rockets":          { line1: "Houston", line2: "Rockets" },
  "Indiana Pacers":           { line1: "Indiana", line2: "Pacers" },
  "LA Clippers":              { line1: "LA", line2: "Clippers" },
  "Los Angeles Lakers":       { line1: "Los Angeles", line2: "Lakers" },
  "Memphis Grizzlies":        { line1: "Memphis", line2: "Grizzlies" },
  "Miami Heat":               { line1: "Miami", line2: "Heat" },
  "Milwaukee Bucks":          { line1: "Milwaukee", line2: "Bucks" },
  "Minnesota Timberwolves":   { line1: "Minnesota", line2: "Timberwolves" },
  "New Orleans Pelicans":     { line1: "New Orleans", line2: "Pelicans" },
  "New York Knicks":          { line1: "New York", line2: "Knicks" },
  "Oklahoma City Thunder":    { line1: "Oklahoma City", line2: "Thunder" },
  "Orlando Magic":            { line1: "Orlando", line2: "Magic" },
  "Philadelphia 76ers":       { line1: "Philadelphia", line2: "76ers" },
  "Phoenix Suns":             { line1: "Phoenix", line2: "Suns" },
  "Portland Trail Blazers":   { line1: "Portland", line2: "Trail Blazers" },
  "Sacramento Kings":         { line1: "Sacramento", line2: "Kings" },
  "San Antonio Spurs":        { line1: "San Antonio", line2: "Spurs" },
  "Toronto Raptors":          { line1: "Toronto", line2: "Raptors" },
  "Utah Jazz":                { line1: "Utah", line2: "Jazz" },
  "Washington Wizards":       { line1: "Washington", line2: "Wizards" },
};
