// lib/team-ids.ts
export const TEAM_IDS: Record<string, string> = {
  // ===== J1 =====
  "北海道コンサドーレ札幌": "j1-hokkaido",
  "鹿島アントラーズ": "j1-kashima",
  "浦和レッズ": "j1-urawa",
  "柏レイソル": "j1-kashiwa",
  "FC東京": "j1-fctokyo",
  "東京ヴェルディ": "j1-verdy",
  "川崎フロンターレ": "j1-kawasaki",
  "横浜F・マリノス": "j1-marinos",
  "湘南ベルマーレ": "j1-shonan",
  "アルビレックス新潟": "j1-niigata",
  "名古屋グランパス": "j1-grampus",
  "京都サンガF.C.": "j1-kyoto",
  "ガンバ大阪": "j1-gamba",
  "セレッソ大阪": "j1-cerezo",
  "ヴィッセル神戸": "j1-kobe",
  "サンフレッチェ広島": "j1-hiroshima",
  "アビスパ福岡": "j1-fukuoka",
  "サガン鳥栖": "j1-tosu",
  "ジュビロ磐田": "j1-iwata",
  "FC町田ゼルビア": "j1-machida",
  "清水エスパルス": "j1-shimizu",
"ファジアーノ岡山": "j1-okayama",
"横浜FC": "j1-yokohamafc",

  // ===== B1 =====
  "レバンガ北海道": "b1-levanga",
  "秋田ノーザンハピネッツ": "b1-akita",
  "仙台89ERS": "b1-sendai",
  "宇都宮ブレックス": "b1-utsunomiya",
  "群馬クレインサンダーズ": "b1-gunma",
  "茨城ロボッツ": "b1-ibaraki",
  "千葉ジェッツ": "b1-chiba",
  "アルバルク東京": "b1-alvark",
  "サンロッカーズ渋谷": "b1-shibuya",
  "川崎ブレイブサンダース": "b1-kawasaki",
  "横浜ビー・コルセアーズ": "b1-yokohama",
  "信州ブレイブウォリアーズ": "b1-shinshu",
  "三遠ネオフェニックス": "b1-sanen",
  "シーホース三河": "b1-mikawa",
  "ファイティングイーグルス名古屋": "b1-fe-nagoya",
  "名古屋ダイヤモンドドルフィンズ": "b1-dolphins",
  "京都ハンナリーズ": "b1-kyoto",
  "大阪エヴェッサ": "b1-osaka",
  "島根スサノオマジック": "b1-shimane",
  "広島ドラゴンフライズ": "b1-hiroshima",
  "佐賀バルーナーズ": "b1-saga",
  "長崎ヴェルカ": "b1-nagasaki",
  "琉球ゴールデンキングス": "b1-ryukyu",
  "富山グラウジーズ": "b1-toyama",
  "福島ファイヤーボンズ": "b1-fukushima",
  "越谷アルファーズ": "b1-koshigaya",
  "滋賀レイクス": "b1-shiga",
  "アルティーリ千葉": "b1-altiri",

  // ===== NBA =====
"Atlanta Hawks": "nba-hawks",
"Boston Celtics": "nba-celtics",
"Brooklyn Nets": "nba-nets",
"Charlotte Hornets": "nba-hornets",
"Chicago Bulls": "nba-bulls",
"Cleveland Cavaliers": "nba-cavaliers",
"Dallas Mavericks": "nba-mavericks",
"Denver Nuggets": "nba-nuggets",
"Detroit Pistons": "nba-pistons",
"Golden State Warriors": "nba-warriors",
"Houston Rockets": "nba-rockets",
"Indiana Pacers": "nba-pacers",
"LA Clippers": "nba-clippers",
"Los Angeles Lakers": "nba-lakers",
"Memphis Grizzlies": "nba-grizzlies",
"Miami Heat": "nba-heat",
"Milwaukee Bucks": "nba-bucks",
"Minnesota Timberwolves": "nba-timberwolves",
"New Orleans Pelicans": "nba-pelicans",
"New York Knicks": "nba-knicks",
"Oklahoma City Thunder": "nba-thunder",
"Orlando Magic": "nba-magic",
"Philadelphia 76ers": "nba-76ers",
"Phoenix Suns": "nba-suns",
"Portland Trail Blazers": "nba-blazers",
"Sacramento Kings": "nba-kings",
"San Antonio Spurs": "nba-spurs",
"Toronto Raptors": "nba-raptors",
"Utah Jazz": "nba-jazz",
"Washington Wizards": "nba-wizards",

  // ===== Premier League =====
  "Arsenal": "pl-arsenal",
  "Aston Villa": "pl-aston-villa",
  "Bournemouth": "pl-bournemouth",
  "Brentford": "pl-brentford",
  "Brighton & Hove Albion": "pl-brighton",
  "Chelsea": "pl-chelsea",
  "Crystal Palace": "pl-crystal-palace",
  "Everton": "pl-everton",
  "Fulham": "pl-fulham",
  "Ipswich Town": "pl-ipswich",
  "Leicester City": "pl-leicester",
  "Liverpool": "pl-liverpool",
  "Manchester City": "pl-man-city",
  "Manchester United": "pl-man-united",
  "Newcastle United": "pl-newcastle",
  "Nottingham Forest": "pl-nottingham",
  "Southampton": "pl-southampton",
  "Tottenham Hotspur": "pl-tottenham",
  "West Ham United": "pl-west-ham",
  "Wolverhampton Wanderers": "pl-wolves",
  "Sunderland": "pl-sunderland",
  "Leeds United": "pl-leeds",
  "Burnley": "pl-burnley"

};
