// 月次レポート（Pro）UI コピー — Web `app/component/reports/MonthlyReportView.tsx` と
// Native `apps/native/src/features/profile/reports/MonthlyReportViewNative.tsx` の共有辞書。
// docs/pro-subscription-plan.md §4。全キー 7 言語（ja/en/ko/zh/es/pt/fr）。
// 分析タイプの長文は `monthlyReportAnalysisTypeCopy.ts`、サマリー本文は builder 側。

import { L, resolveLocalizedLang, type LocalizedLang } from "@/lib/i18n/localize";
import type {
  MonthlyReportMetricKey,
  MonthlyReportRadarAxisKey,
  MonthlyReportUnitMetric,
  MonthlyReportUnitSource,
} from "@/lib/reports/monthlyReportTypes";

export type MonthlyReportUiCopy = ReturnType<typeof monthlyReportUiCopy>;

export function monthlyReportUiCopy(language: LocalizedLang | string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    /** ブランド語。全言語共通 */
    title: "MONTHLY REPORT",
    rankLabel: "RANK",
    unitsLabel: "UNITS",
    thisMonth: L(lang, {
      ja: "今月の結果",
      en: "This Month",
      ko: "이번 달 결과",
      zh: "本月结果",
      es: "Este mes",
      pt: "Este mês",
      fr: "Ce mois",
    }),
    monthLabel: (monthKey: string) => {
      const [y, m] = monthKey.split("-");
      const month = Number(m);
      return L(lang, {
        ja: `${y}年${month}月`,
        en: `${y}-${m}`,
        ko: `${y}년 ${month}월`,
        zh: `${y}年${month}月`,
        es: `${m}/${y}`,
        pt: `${m}/${y}`,
        fr: `${m}/${y}`,
      });
    },
    participants: (n: number) =>
      L(lang, {
        ja: `${n}人中`,
        en: `of ${n}`,
        ko: `${n}명 중`,
        zh: `共 ${n} 人`,
        es: `de ${n}`,
        pt: `de ${n}`,
        fr: `sur ${n}`,
      }),
    top: (p: string) => `TOP ${p}%`,
    posts: L(lang, {
      ja: "投稿",
      en: "picks",
      ko: "예상",
      zh: "投稿",
      es: "picks",
      pt: "palpites",
      fr: "picks",
    }),
    wins: L(lang, {
      ja: "勝",
      en: "W",
      ko: "승",
      zh: "胜",
      es: "V",
      pt: "V",
      fr: "V",
    }),
    losses: L(lang, {
      ja: "敗",
      en: "L",
      ko: "패",
      zh: "负",
      es: "D",
      pt: "D",
      fr: "D",
    }),
    unitsEarnedLabel: L(lang, {
      ja: "今月の獲得",
      en: "Earned",
      ko: "이번 달 획득",
      zh: "本月获得",
      es: "Obtenidos",
      pt: "Obtidos",
      fr: "Obtenus",
    }),
    monthlyChange: L(lang, {
      ja: "前月比",
      en: "MoM",
      ko: "전월 대비",
      zh: "环比",
      es: "MoM",
      pt: "MoM",
      fr: "MoM",
    }),
    typeLabel: L(lang, {
      ja: "今月の分析タイプ",
      en: "Analysis Type",
      ko: "이번 달 분석 타입",
      zh: "本月分析类型",
      es: "Tipo de análisis",
      pt: "Tipo de análise",
      fr: "Type d'analyse",
    }),
    numbers: L(lang, {
      ja: "数字で見る今月",
      en: "Month in Numbers",
      ko: "숫자로 보는 이번 달",
      zh: "数字看本月",
      es: "Mes en números",
      pt: "Mês em números",
      fr: "Mois en chiffres",
    }),
    unitsBreakdown: L(lang, {
      ja: "獲得 Unit 内訳",
      en: "Units Breakdown",
      ko: "획득 Unit 내역",
      zh: "Unit 明细",
      es: "Desglose de Units",
      pt: "Detalhe de Units",
      fr: "Détail des Units",
    }),
    unitsBreakdownEmpty: L(lang, {
      ja: "今月の Unit 付与はありません。",
      en: "No Units granted this month.",
      ko: "이번 달 Unit 지급이 없습니다.",
      zh: "本月没有 Unit 发放。",
      es: "No se otorgaron Units este mes.",
      pt: "Nenhum Unit concedido neste mês.",
      fr: "Aucun Unit attribué ce mois-ci.",
    }),
    unitsBreakdownTotal: L(lang, {
      ja: "今月の合計",
      en: "Month total",
      ko: "이번 달 합계",
      zh: "本月合计",
      es: "Total del mes",
      pt: "Total do mês",
      fr: "Total du mois",
    }),
    unitsBreakdownExpand: L(lang, {
      ja: "タップで内訳",
      en: "Tap for details",
      ko: "탭하여 내역 보기",
      zh: "点按查看明细",
      es: "Toca para ver el desglose",
      pt: "Toque para ver o detalhe",
      fr: "Touchez pour le détail",
    }),
    unitsBreakdownCollapse: L(lang, {
      ja: "閉じる",
      en: "Hide",
      ko: "접기",
      zh: "收起",
      es: "Ocultar",
      pt: "Ocultar",
      fr: "Masquer",
    }),
    unitSource: {
      personal_weekly: L(lang, {
        ja: "個人・週間",
        en: "Personal · Weekly",
        ko: "개인 · 주간",
        zh: "个人 · 周",
        es: "Personal · Semanal",
        pt: "Pessoal · Semanal",
        fr: "Perso · Hebdo",
      }),
      personal_monthly: L(lang, {
        ja: "個人・月間",
        en: "Personal · Monthly",
        ko: "개인 · 월간",
        zh: "个人 · 月",
        es: "Personal · Mensual",
        pt: "Pessoal · Mensal",
        fr: "Perso · Mensuel",
      }),
      group_weekly: L(lang, {
        ja: "グループ・週間",
        en: "Group · Weekly",
        ko: "그룹 · 주간",
        zh: "团队 · 周",
        es: "Grupo · Semanal",
        pt: "Grupo · Semanal",
        fr: "Groupe · Hebdo",
      }),
      group_monthly: L(lang, {
        ja: "グループ・月間",
        en: "Group · Monthly",
        ko: "그룹 · 월간",
        zh: "团队 · 月",
        es: "Grupo · Mensual",
        pt: "Grupo · Mensal",
        fr: "Groupe · Mensuel",
      }),
      invite: L(lang, {
        ja: "招待",
        en: "Invite",
        ko: "초대",
        zh: "邀请",
        es: "Invitación",
        pt: "Convite",
        fr: "Invitation",
      }),
      metric_rank: L(lang, {
        ja: "部門上位",
        en: "Metric top",
        ko: "부문 상위",
        zh: "分项前列",
        es: "Top por métrica",
        pt: "Top por métrica",
        fr: "Top par métrique",
      }),
      event: L(lang, {
        ja: "イベント",
        en: "Event",
        ko: "이벤트",
        zh: "活动",
        es: "Evento",
        pt: "Evento",
        fr: "Événement",
      }),
    } satisfies Record<MonthlyReportUnitSource, string>,
    unitMetric: {
      totalPoints: L(lang, {
        ja: "総合得点",
        en: "Points",
        ko: "총점",
        zh: "总分",
        es: "Puntos",
        pt: "Pontos",
        fr: "Points",
      }),
      winRate: L(lang, {
        ja: "勝率",
        en: "Win %",
        ko: "승률",
        zh: "胜率",
        es: "% victorias",
        pt: "% de acerto",
        fr: "% victoires",
      }),
      scorer: "SCORER",
      upset: "UPSET",
    } satisfies Record<MonthlyReportUnitMetric, string>,
    unitRank: (n: number) => `#${n}`,
    metricRank: (n: number) => `#${n}`,
    radar: L(lang, {
      ja: "能力チャート",
      en: "Ability Chart",
      ko: "능력 차트",
      zh: "能力图",
      es: "Gráfico de habilidad",
      pt: "Gráfico de habilidade",
      fr: "Graphique d'aptitude",
    }),
    habits: L(lang, {
      ja: "予想のクセ",
      en: "Habits",
      ko: "예상 습관",
      zh: "预测习惯",
      es: "Hábitos",
      pt: "Hábitos",
      fr: "Habitudes",
    }),
    habitsEmpty: L(lang, {
      ja: "サンプルが足りず、今月のクセはまだ出せません。",
      en: "Not enough sample to surface habits this month.",
      ko: "표본이 부족해 이번 달 습관은 아직 표시할 수 없습니다.",
      zh: "样本不足，本月的习惯还无法呈现。",
      es: "No hay muestra suficiente para mostrar hábitos este mes.",
      pt: "Amostra insuficiente para mostrar hábitos neste mês.",
      fr: "Échantillon insuffisant pour dégager des habitudes ce mois-ci.",
    }),
    habitsMapHint: L(lang, {
      ja: "横: Away ←→ Home / 縦: 順当 ←→ 逆張り · 点の大きさ=勝率",
      en: "X: Away ←→ Home / Y: Consensus ←→ Fade · Dot size = win rate",
      ko: "가로: Away ←→ Home / 세로: 정배 ←→ 역배 · 점 크기 = 승률",
      zh: "横轴: Away ←→ Home / 纵轴: 顺势 ←→ 逆势 · 点的大小 = 胜率",
      es: "X: Away ←→ Home / Y: Consenso ←→ Contra · Tamaño del punto = win rate",
      pt: "X: Away ←→ Home / Y: Consenso ←→ Contra · Tamanho do ponto = taxa de acerto",
      fr: "X : Away ←→ Home / Y : Consensus ←→ Contre · Taille du point = taux de victoire",
    }),
    /** スタイルマップ上端／下端のラベル */
    consensus: L(lang, {
      ja: "順当",
      en: "CONSENSUS",
      ko: "정배",
      zh: "顺势",
      es: "CONSENSO",
      pt: "CONSENSO",
      fr: "CONSENSUS",
    }),
    fade: L(lang, {
      ja: "逆張り",
      en: "FADE",
      ko: "역배",
      zh: "逆势",
      es: "CONTRA",
      pt: "CONTRA",
      fr: "CONTRE",
    }),
    homeAway: "Home / Away",
    market: L(lang, {
      ja: "順当 / 逆張り",
      en: "Consensus / Fade",
      ko: "정배 / 역배",
      zh: "顺势 / 逆势",
      es: "Consenso / Contra",
      pt: "Consenso / Contra",
      fr: "Consensus / Contre",
    }),
    homeWr: L(lang, {
      ja: "Home勝率",
      en: "Home win %",
      ko: "Home 승률",
      zh: "Home 胜率",
      es: "Win % Home",
      pt: "Taxa Home",
      fr: "Taux Home",
    }),
    awayWr: L(lang, {
      ja: "Away勝率",
      en: "Away win %",
      ko: "Away 승률",
      zh: "Away 胜率",
      es: "Win % Away",
      pt: "Taxa Away",
      fr: "Taux Away",
    }),
    favWr: L(lang, {
      ja: "順当勝率",
      en: "Consensus win %",
      ko: "정배 승률",
      zh: "顺势胜率",
      es: "Win % consenso",
      pt: "Taxa consenso",
      fr: "Taux consensus",
    }),
    dogWr: L(lang, {
      ja: "逆張り勝率",
      en: "Fade win %",
      ko: "역배 승률",
      zh: "逆势胜率",
      es: "Win % contra",
      pt: "Taxa contra",
      fr: "Taux contre",
    }),
    homeShare: "Home",
    awayShare: "Away",
    favShare: L(lang, {
      ja: "順当",
      en: "Consensus",
      ko: "정배",
      zh: "顺势",
      es: "Consenso",
      pt: "Consenso",
      fr: "Consensus",
    }),
    dogShare: L(lang, {
      ja: "逆張り",
      en: "Fade",
      ko: "역배",
      zh: "逆势",
      es: "Contra",
      pt: "Contra",
      fr: "Contre",
    }),
    pickShare: L(lang, {
      ja: "選球比",
      en: "Pick share",
      ko: "선택 비율",
      zh: "选择占比",
      es: "Reparto de picks",
      pt: "Distribuição de palpites",
      fr: "Répartition des picks",
    }),
    affinity: L(lang, {
      ja: "チーム相性",
      en: "Team Affinity",
      ko: "팀 궁합",
      zh: "球队契合",
      es: "Afinidad",
      pt: "Afinidade",
      fr: "Affinité",
    }),
    strong: L(lang, {
      ja: "得意",
      en: "Strong",
      ko: "강함",
      zh: "擅长",
      es: "Fuerte",
      pt: "Forte",
      fr: "Fort",
    }),
    weak: L(lang, {
      ja: "苦手",
      en: "Weak",
      ko: "약함",
      zh: "不擅长",
      es: "Débil",
      pt: "Fraco",
      fr: "Faible",
    }),
    highlights: L(lang, {
      ja: "月間ハイライト",
      en: "Highlights",
      ko: "월간 하이라이트",
      zh: "月度亮点",
      es: "Destacados",
      pt: "Destaques",
      fr: "Temps forts",
    }),
    bestPick: L(lang, {
      ja: "ベスト予想",
      en: "Best Pick",
      ko: "베스트 예상",
      zh: "最佳预测",
      es: "Mejor pick",
      pt: "Melhor palpite",
      fr: "Meilleur pick",
    }),
    myPick: L(lang, {
      ja: "自分の予想",
      en: "Your pick",
      ko: "내 예상",
      zh: "我的预测",
      es: "Tu pick",
      pt: "Seu palpite",
      fr: "Votre pick",
    }),
    bestDay: L(lang, {
      ja: "ベストデー",
      en: "Best Day",
      ko: "베스트 데이",
      zh: "最佳单日",
      es: "Mejor día",
      pt: "Melhor dia",
      fr: "Meilleur jour",
    }),
    bestDayLine: (wins: number, posts: number) =>
      L(lang, {
        ja: `${posts}試合 ${wins}勝`,
        en: `${wins}W of ${posts}`,
        ko: `${posts}경기 ${wins}승`,
        zh: `${posts} 场 ${wins} 胜`,
        es: `${wins}V de ${posts}`,
        pt: `${wins}V de ${posts}`,
        fr: `${wins}V sur ${posts}`,
      }),
    streak: L(lang, {
      ja: "最長連勝",
      en: "Longest Streak",
      ko: "최장 연승",
      zh: "最长连胜",
      es: "Racha más larga",
      pt: "Maior sequência",
      fr: "Plus longue série",
    }),
    streakUnit: L(lang, {
      ja: "連勝",
      en: "wins",
      ko: "연승",
      zh: "连胜",
      es: "victorias",
      pt: "vitórias",
      fr: "victoires",
    }),
    upset: L(lang, {
      ja: "最大アップセット",
      en: "Biggest Upset",
      ko: "최대 업셋",
      zh: "最大冷门",
      es: "Mayor upset",
      pt: "Maior upset",
      fr: "Plus gros upset",
    }),
    divisionTop10: (division: string, rank: number) =>
      L(lang, {
        ja: `${division} 部門 #${rank}`,
        en: `${division} #${rank}`,
        ko: `${division} 부문 #${rank}`,
        zh: `${division} 分项 #${rank}`,
        es: `${division} #${rank}`,
        pt: `${division} #${rank}`,
        fr: `${division} #${rank}`,
      }),
    outlook: L(lang, {
      ja: "今月のサマリー",
      en: "Month Summary",
      ko: "이번 달 요약",
      zh: "本月摘要",
      es: "Resumen del mes",
      pt: "Resumo do mês",
      fr: "Résumé du mois",
    }),
    metric: {
      posts: L(lang, {
        ja: "予想数",
        en: "Picks",
        ko: "예상 수",
        zh: "预测数",
        es: "Picks",
        pt: "Palpites",
        fr: "Picks",
      }),
      points: L(lang, {
        ja: "総合得点",
        en: "Total Points",
        ko: "총점",
        zh: "总分",
        es: "Puntos totales",
        pt: "Pontos totais",
        fr: "Points totaux",
      }),
      winRate: L(lang, {
        ja: "勝率",
        en: "Win %",
        ko: "승률",
        zh: "胜率",
        es: "% victorias",
        pt: "% de acerto",
        fr: "% victoires",
      }),
      goalScorerHits: L(lang, {
        ja: "SCORER 的中",
        en: "Scorer hits",
        ko: "SCORER 적중",
        zh: "SCORER 命中",
        es: "Aciertos SCORER",
        pt: "Acertos SCORER",
        fr: "Réussites SCORER",
      }),
      upsetPoints: L(lang, {
        ja: "UPSET pt",
        en: "Upset pts",
        ko: "UPSET pt",
        zh: "UPSET 分",
        es: "Pts UPSET",
        pt: "Pts UPSET",
        fr: "Pts UPSET",
      }),
      units: L(lang, {
        ja: "獲得 Unit",
        en: "Units",
        ko: "획득 Unit",
        zh: "获得 Unit",
        es: "Units",
        pt: "Units",
        fr: "Units",
      }),
    } satisfies Record<MonthlyReportMetricKey, string>,
    prevDelta: L(lang, {
      ja: "前月比",
      en: "vs last",
      ko: "전월 대비",
      zh: "环比",
      es: "vs anterior",
      pt: "vs anterior",
      fr: "vs préc.",
    }),
    medianMark: L(lang, {
      ja: "中央値",
      en: "Median",
      ko: "중앙값",
      zh: "中位数",
      es: "Mediana",
      pt: "Mediana",
      fr: "Médiane",
    }),
    youMark: L(lang, {
      ja: "自分",
      en: "You",
      ko: "나",
      zh: "我",
      es: "Tú",
      pt: "Você",
      fr: "Vous",
    }),
    top10Mark: L(lang, {
      ja: "上位10%",
      en: "Top 10%",
      ko: "상위 10%",
      zh: "前 10%",
      es: "Top 10%",
      pt: "Top 10%",
      fr: "Top 10%",
    }),
    vsMedian: L(lang, {
      ja: "中央値より",
      en: "vs med",
      ko: "중앙값 대비",
      zh: "对比中位数",
      es: "vs mediana",
      pt: "vs mediana",
      fr: "vs médiane",
    }),
    vsTop10: L(lang, {
      ja: "上位10%より",
      en: "vs top10%",
      ko: "상위 10% 대비",
      zh: "对比前 10%",
      es: "vs top10%",
      pt: "vs top10%",
      fr: "vs top10%",
    }),
    /** 5軸ラベルはブランド語。全言語共通 */
    radarAxis: {
      win: "WIN",
      scorer: "SCORER",
      upset: "UPSET",
      activity: "ACTIVITY",
      consistency: "CONSISTENCY",
    } satisfies Record<MonthlyReportRadarAxisKey, string>,
    /** 軸タップ時のツールチップ。1行目は軸名、2行目以降が説明 */
    radarAxisHelp: {
      win: L(lang, {
        ja: "WIN\n勝敗予想の強さ。当月コホート内での勝率の位置（パーセンタイル）。",
        en: "WIN\nWin-pick strength. Your win-rate percentile in this month's cohort.",
        ko: "WIN\n승패 예상의 강도. 당월 코호트 내 승률의 위치(백분위).",
        zh: "WIN\n胜负预测的强度。本月同期群体中胜率所处的位置（百分位）。",
        es: "WIN\nFuerza en picks de ganador. Tu percentil de win rate dentro de la cohorte del mes.",
        pt: "WIN\nForça nos palpites de vencedor. Seu percentil de taxa de acerto na coorte do mês.",
        fr: "WIN\nForce sur les vainqueurs. Votre percentile de taux de victoire dans la cohorte du mois.",
      }),
      scorer: L(lang, {
        ja: "SCORER\n得点者予想の的中力。最多得点者を当てる力の相対位置。",
        en: "SCORER\nGoal-scorer hit strength. Relative skill at picking top scorers.",
        ko: "SCORER\n득점자 예상의 적중력. 최다 득점자를 맞히는 능력의 상대적 위치.",
        zh: "SCORER\n得分者预测的命中力。猜中最高得分者能力的相对位置。",
        es: "SCORER\nAcierto en máximos anotadores. Posición relativa al elegir al máximo anotador.",
        pt: "SCORER\nAcerto em cestinhas. Posição relativa ao escolher o maior pontuador.",
        fr: "SCORER\nRéussite sur les marqueurs. Position relative pour désigner le meilleur marqueur.",
      }),
      upset: L(lang, {
        ja: "UPSET\n番狂わせで稼ぐ力。アップセット得点の相対位置。",
        en: "UPSET\nUpset earning power. Relative upset points in the cohort.",
        ko: "UPSET\n이변으로 벌어들이는 힘. 업셋 점수의 상대적 위치.",
        zh: "UPSET\n靠冷门得分的能力。冷门得分的相对位置。",
        es: "UPSET\nCapacidad de puntuar con sorpresas. Posición relativa en puntos de upset.",
        pt: "UPSET\nCapacidade de pontuar com zebras. Posição relativa em pontos de upset.",
        fr: "UPSET\nCapacité à marquer sur les surprises. Position relative en points d'upset.",
      }),
      activity: L(lang, {
        ja: "ACTIVITY\n参加量。ピックアップ試合にどれだけ予想したか。",
        en: "ACTIVITY\nParticipation volume. How many pickup games you picked.",
        ko: "ACTIVITY\n참여량. 픽업 경기에 얼마나 예상했는지.",
        zh: "ACTIVITY\n参与量。你对多少场精选比赛做了预测。",
        es: "ACTIVITY\nVolumen de participación. En cuántos partidos destacados hiciste pick.",
        pt: "ACTIVITY\nVolume de participação. Em quantos jogos em destaque você palpitou.",
        fr: "ACTIVITY\nVolume de participation. Sur combien de matchs sélectionnés vous avez joué.",
      }),
      consistency: L(lang, {
        ja: "CONSISTENCY\n安定性。連勝を活かし、連敗の傷を抑える力。",
        en: "CONSISTENCY\nStability. Riding win streaks while limiting losing runs.",
        ko: "CONSISTENCY\n안정성. 연승을 살리고 연패의 상처를 줄이는 힘.",
        zh: "CONSISTENCY\n稳定性。用好连胜、控制连败的能力。",
        es: "CONSISTENCY\nEstabilidad. Aprovechar las rachas buenas y limitar las malas.",
        pt: "CONSISTENCY\nEstabilidade. Aproveitar as boas sequências e limitar as ruins.",
        fr: "CONSISTENCY\nRégularité. Exploiter les séries positives et limiter les négatives.",
      }),
    } satisfies Record<MonthlyReportRadarAxisKey, string>,
  };
}
