// 週次レポート（Pro）UI コピー — Web `app/component/reports/WeeklyReportView.tsx` と
// Native `apps/native/src/features/profile/reports/WeeklyReportViewNative.tsx` の共有辞書。
// docs/pro-subscription-plan.md §3。全キー 7 言語（ja/en/ko/zh/es/pt/fr）。

import { L, resolveLocalizedLang, type LocalizedLang } from "@/lib/i18n/localize";
import type { WeeklyReportCommentTone } from "@/lib/reports/weeklyReportTypes";

export type WeeklyReportUiCopy = ReturnType<typeof weeklyReportUiCopy>;

/** tone と factor の連結。CJK は詰め、それ以外は半角スペース */
function toneFactorSeparator(lang: LocalizedLang): string {
  return lang === "ja" || lang === "zh" ? "" : " ";
}

export function weeklyReportUiCopy(language: LocalizedLang | string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    /** ブランド語。全言語共通 */
    title: "WEEKLY REPORT",
    live: "LEGACY",
    liveNote: L(lang, {
      ja: "過去の進行中レポートです。いまは確定週のみ配信されます。",
      en: "Legacy in-progress report. Weekly reports now ship as finals only.",
      ko: "과거의 진행 중 리포트입니다. 지금은 확정된 주만 배포됩니다.",
      zh: "这是过去的进行中报告。现在仅发布已确定的周报。",
      es: "Informe en curso heredado. Ahora los informes semanales solo se publican como definitivos.",
      pt: "Relatório antigo em andamento. Agora os relatórios semanais saem apenas como finais.",
      fr: "Ancien rapport en cours. Les rapports hebdomadaires ne sont plus publiés qu'en version finale.",
    }),
    heroRank: L(lang, {
      ja: "順位",
      en: "Rank",
      ko: "순위",
      zh: "排名",
      es: "Puesto",
      pt: "Posição",
      fr: "Rang",
    }),
    heroScore: L(lang, {
      ja: "スコア",
      en: "Score",
      ko: "점수",
      zh: "得分",
      es: "Puntos",
      pt: "Pontos",
      fr: "Score",
    }),
    participants: (n: number) =>
      L(lang, {
        ja: `${n}人中`,
        en: `of ${n}`,
        ko: `${n}명 중`,
        zh: `共 ${n} 人`,
        es: `de ${n}`,
        pt: `de ${n}`,
        fr: `sur ${n}`,
      }),
    top: (p: string) => `TOP ${p}%`,
    posts: L(lang, {
      ja: "投稿",
      en: "picks",
      ko: "예상",
      zh: "投稿",
      es: "picks",
      pt: "palpites",
      fr: "picks",
    }),
    wins: L(lang, {
      ja: "勝",
      en: "W",
      ko: "승",
      zh: "胜",
      es: "V",
      pt: "V",
      fr: "V",
    }),
    losses: L(lang, {
      ja: "敗",
      en: "L",
      ko: "패",
      zh: "负",
      es: "D",
      pt: "D",
      fr: "D",
    }),
    firstWeekRank: L(lang, {
      ja: "今週から参戦",
      en: "First week",
      ko: "이번 주 첫 참가",
      zh: "本周首次参战",
      es: "Primera semana",
      pt: "Primeira semana",
      fr: "Première semaine",
    }),
    divisions: L(lang, {
      ja: "部門成績",
      en: "Divisions",
      ko: "부문 성적",
      zh: "分项成绩",
      es: "Divisiones",
      pt: "Divisões",
      fr: "Divisions",
    }),
    divisionRank: (n: number) =>
      L(lang, {
        ja: `部門 #${n}`,
        en: `Div #${n}`,
        ko: `부문 #${n}`,
        zh: `分项 #${n}`,
        es: `Div #${n}`,
        pt: `Div #${n}`,
        fr: `Div #${n}`,
      }),
    divisionUnranked: L(lang, {
      ja: "圏外",
      en: "Unranked",
      ko: "순위 외",
      zh: "未上榜",
      es: "Sin clasificar",
      pt: "Sem ranking",
      fr: "Non classé",
    }),
    divisionReference: L(lang, {
      ja: "参考記録",
      en: "Reference",
      ko: "참고 기록",
      zh: "参考记录",
      es: "Referencia",
      pt: "Referência",
      fr: "Référence",
    }),
    divisionPostsToQualify: (n: number) =>
      L(lang, {
        ja: `あと${n}予想`,
        en: `${n} more picks`,
        ko: `${n}개 더 예상`,
        zh: `还需 ${n} 次预测`,
        es: `${n} picks más`,
        pt: `${n} palpites a mais`,
        fr: `${n} picks de plus`,
      }),
    overtaken: L(lang, {
      ja: "抜いた相手",
      en: "Passed",
      ko: "앞지른 상대",
      zh: "超越的对手",
      es: "Superados",
      pt: "Ultrapassados",
      fr: "Dépassés",
    }),
    overtakenBy: L(lang, {
      ja: "抜かれた相手",
      en: "Passed by",
      ko: "나를 앞지른 상대",
      zh: "被超越的对手",
      es: "Superado por",
      pt: "Ultrapassado por",
      fr: "Dépassé par",
    }),
    noOvertaken: L(lang, {
      ja: "今週は誰も抜けなかった",
      en: "No one passed this week",
      ko: "이번 주에는 아무도 앞지르지 못했습니다",
      zh: "本周没有超越任何人",
      es: "Esta semana no superaste a nadie",
      pt: "Nesta semana você não passou ninguém",
      fr: "Personne dépassé cette semaine",
    }),
    noOvertakenBy: L(lang, {
      ja: "誰にも抜かれなかった",
      en: "Nobody passed you",
      ko: "아무에게도 추월당하지 않았습니다",
      zh: "没有被任何人超越",
      es: "Nadie te superó",
      pt: "Ninguém te ultrapassou",
      fr: "Personne ne vous a dépassé",
    }),
    moreRivals: (n: number) =>
      L(lang, {
        ja: `ほか ${n} 人`,
        en: `+${n} more`,
        ko: `외 ${n}명`,
        zh: `其他 ${n} 人`,
        es: `+${n} más`,
        pt: `+${n} mais`,
        fr: `+${n} autres`,
      }),
    showMore: (n: number) =>
      L(lang, {
        ja: `もっと見る（${n}人）`,
        en: `Show all (+${n})`,
        ko: `더 보기 (${n}명)`,
        zh: `查看更多（${n} 人）`,
        es: `Ver todos (+${n})`,
        pt: `Ver todos (+${n})`,
        fr: `Tout afficher (+${n})`,
      }),
    showLess: L(lang, {
      ja: "閉じる",
      en: "Show less",
      ko: "접기",
      zh: "收起",
      es: "Ver menos",
      pt: "Ver menos",
      fr: "Réduire",
    }),
    firstWeekBattle: L(lang, {
      ja: "今週から参戦。抜いた・抜かれたは来週から表示されます。",
      en: "First week in. Battle log starts next week.",
      ko: "이번 주에 처음 참가했습니다. 추월 기록은 다음 주부터 표시됩니다.",
      zh: "本周首次参战。超越与被超越的记录将从下周开始显示。",
      es: "Primera semana dentro. El registro de duelos empieza la semana que viene.",
      pt: "Primeira semana dentro. O registro de duelos começa na próxima semana.",
      fr: "Première semaine. Le journal des duels démarre la semaine prochaine.",
    }),
    battleSummary: (passed: number, passedBy: number) =>
      L(lang, {
        ja: `今週は${passed}人を抜き、${passedBy}人に抜かれました`,
        en: `Passed ${passed}, passed by ${passedBy} this week`,
        ko: `이번 주 ${passed}명을 앞지르고 ${passedBy}명에게 추월당했습니다`,
        zh: `本周超越 ${passed} 人，被 ${passedBy} 人超越`,
        es: `Esta semana superaste a ${passed} y te superaron ${passedBy}`,
        pt: `Nesta semana você passou ${passed} e foi passado por ${passedBy}`,
        fr: `Cette semaine : ${passed} dépassés, ${passedBy} vous ont dépassé`,
      }),
    battleSection: L(lang, {
      ja: "順位変動",
      en: "Rank Moves",
      ko: "순위 변동",
      zh: "排名变动",
      es: "Movimientos",
      pt: "Movimentos",
      fr: "Mouvements",
    }),
    nowRank: (n: number) =>
      L(lang, {
        ja: `現在 #${n}`,
        en: `now #${n}`,
        ko: `현재 #${n}`,
        zh: `当前 #${n}`,
        es: `ahora #${n}`,
        pt: `agora #${n}`,
        fr: `actuel #${n}`,
      }),
    nextTarget: L(lang, {
      ja: "次のターゲット",
      en: "Next Target",
      ko: "다음 타깃",
      zh: "下一个目标",
      es: "Siguiente objetivo",
      pt: "Próximo alvo",
      fr: "Prochaine cible",
    }),
    targetGapLabel: L(lang, {
      ja: "抜くまであと",
      en: "To pass",
      ko: "추월까지",
      zh: "追上还差",
      es: "Para superar",
      pt: "Para passar",
      fr: "Pour dépasser",
    }),
    youAreTop: L(lang, {
      ja: "あなたが首位。追われる側です。",
      en: "You lead the board.",
      ko: "당신이 1위입니다. 쫓기는 입장이죠.",
      zh: "你是第一名，正被追赶。",
      es: "Lideras la tabla.",
      pt: "Você lidera a tabela.",
      fr: "Vous êtes en tête.",
    }),
    threat: L(lang, {
      ja: "背後の脅威",
      en: "Closing In",
      ko: "뒤의 위협",
      zh: "身后威胁",
      es: "Amenaza detrás",
      pt: "Ameaça atrás",
      fr: "Menace derrière",
    }),
    threatGapLabel: L(lang, {
      ja: "背後に接近中",
      en: "Behind you",
      ko: "뒤에서 접근 중",
      zh: "正在逼近",
      es: "Detrás de ti",
      pt: "Atrás de você",
      fr: "Derrière vous",
    }),
    noThreat: L(lang, {
      ja: "背後に脅威なし",
      en: "No threat behind",
      ko: "뒤에 위협 없음",
      zh: "身后无威胁",
      es: "Sin amenazas detrás",
      pt: "Sem ameaças atrás",
      fr: "Aucune menace derrière",
    }),
    proMember: L(lang, {
      ja: "Pro会員",
      en: "Pro member",
      ko: "Pro 회원",
      zh: "Pro 会员",
      es: "Miembro Pro",
      pt: "Membro Pro",
      fr: "Membre Pro",
    }),
    prevWeek: L(lang, {
      ja: "前の週",
      en: "Previous week",
      ko: "이전 주",
      zh: "上一周",
      es: "Semana anterior",
      pt: "Semana anterior",
      fr: "Semaine précédente",
    }),
    nextWeek: L(lang, {
      ja: "次の週",
      en: "Next week",
      ko: "다음 주",
      zh: "下一周",
      es: "Semana siguiente",
      pt: "Próxima semana",
      fr: "Semaine suivante",
    }),
    toneFactorSeparator: toneFactorSeparator(lang),
    commentTone: {
      climbedBig: L(lang, {
        ja: "圧巻の週。",
        en: "A statement week.",
        ko: "압권의 한 주.",
        zh: "压倒性的一周。",
        es: "Una semana rotunda.",
        pt: "Uma semana marcante.",
        fr: "Une semaine magistrale.",
      }),
      climbed: L(lang, {
        ja: "確実に順位を上げた。",
        en: "A solid climb.",
        ko: "확실하게 순위를 올렸다.",
        zh: "排名稳步上升。",
        es: "Una subida sólida.",
        pt: "Uma subida sólida.",
        fr: "Une montée solide.",
      }),
      held: L(lang, {
        ja: "順位キープ。",
        en: "Held your ground.",
        ko: "순위 유지.",
        zh: "排名守住了。",
        es: "Mantuviste la posición.",
        pt: "Manteve a posição.",
        fr: "Position tenue.",
      }),
      dropped: L(lang, {
        ja: "後退した週。",
        en: "A step back.",
        ko: "후퇴한 한 주.",
        zh: "后退的一周。",
        es: "Una semana de retroceso.",
        pt: "Uma semana de recuo.",
        fr: "Une semaine en recul.",
      }),
      firstWeek: L(lang, {
        ja: "初参戦の記録がここから始まる。来週は順位変動も表示される。",
        en: "Your record starts here. Rank moves show next week.",
        ko: "첫 참가 기록이 여기서 시작됩니다. 다음 주에는 순위 변동도 표시됩니다.",
        zh: "初次参战的记录从这里开始。下周将显示排名变动。",
        es: "Tu historial empieza aquí. Los movimientos de puesto se verán la semana que viene.",
        pt: "Seu histórico começa aqui. Os movimentos de posição aparecem na próxima semana.",
        fr: "Votre historique commence ici. Les mouvements de rang s'afficheront la semaine prochaine.",
      }),
    } satisfies Record<WeeklyReportCommentTone, string>,
    commentFactor: {
      targetGap: (rank: number, name: string, pt: string) =>
        L(lang, {
          ja: `#${rank} ${name} まであと ${pt}pt。来週の数試合で届く。`,
          en: `${pt}pt to #${rank} ${name}. A few games away.`,
          ko: `#${rank} ${name}까지 ${pt}pt. 다음 주 몇 경기면 닿는다.`,
          zh: `距 #${rank} ${name} 还差 ${pt}pt。下周几场就能追上。`,
          es: `${pt}pt para alcanzar a #${rank} ${name}. A unos pocos partidos.`,
          pt: `${pt}pt para alcançar #${rank} ${name}. A poucos jogos de distância.`,
          fr: `${pt}pt pour rattraper #${rank} ${name}. À quelques matchs près.`,
        }),
      overtakenBy: (name: string) =>
        L(lang, {
          ja: `${name} に抜かれたまま終わるか、抜き返すか。`,
          en: `Passed by ${name}. Pass back next week.`,
          ko: `${name}에게 추월당한 채로 끝낼지, 되받아칠지.`,
          zh: `是就这样被 ${name} 超越，还是反超回去。`,
          es: `${name} te superó. Devuélvele el adelantamiento la próxima semana.`,
          pt: `${name} te ultrapassou. Devolva a ultrapassagem na próxima semana.`,
          fr: `${name} vous a dépassé. À vous de repasser devant la semaine prochaine.`,
        }),
      divisionUp: (label: string) =>
        L(lang, {
          ja: `${label} の伸びが効いた。`,
          en: `${label} carried the week.`,
          ko: `${label}의 상승이 효과적이었다.`,
          zh: `${label} 的提升起了作用。`,
          es: `${label} tiró de la semana.`,
          pt: `${label} puxou a semana.`,
          fr: `${label} a porté la semaine.`,
        }),
      divisionDown: (label: string) =>
        L(lang, {
          ja: `${label} が足を引っ張った。`,
          en: `${label} held you back.`,
          ko: `${label}이 발목을 잡았다.`,
          zh: `${label} 拖了后腿。`,
          es: `${label} te frenó.`,
          pt: `${label} te segurou.`,
          fr: `${label} vous a freiné.`,
        }),
      lowVolume: (n: number) =>
        L(lang, {
          ja: `投稿 ${n} 件。まずは母数から。`,
          en: `${n} picks. Volume first.`,
          ko: `예상 ${n}건. 우선 표본부터.`,
          zh: `${n} 次预测。先把量做上来。`,
          es: `${n} picks. Primero el volumen.`,
          pt: `${n} palpites. Volume primeiro.`,
          fr: `${n} picks. Le volume d'abord.`,
        }),
    },
  };
}
