import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Montserrat } from "next/font/google";
import { Noto_Sans_JP, Lilita_One, Acme, Alfa_Slab_One } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-montserrat",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto = Noto_Sans_JP({ subsets: ["latin"], variable: "--font-noto" });
const lilita = Lilita_One({ weight: "400", subsets: ["latin"], variable: "--font-lilita" });
const acme = Acme({ weight: "400", subsets: ["latin"], variable: "--font-acme" });
const alfa = Alfa_Slab_One({ weight: "400", subsets: ["latin"], variable: "--font-alfa" });

export default function WithNavLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased bg-app min-h-screen`}
      style={{ paddingBottom: "env(safe-area-inset-bottom)" }}
    >
      {/* ★ 下部 NavBar は削除 */}
      {children}
    </div>
  );
}
