/**
 * Games 一覧 `GameCardList` が使うスタイル（`GamesHomeScreen` と同じ値）。
 * 試合カード見た目の正。プレビューと一覧で共有する。
 */
import { StyleSheet } from "react-native";
import { colors, spacing, typography } from "../../theme/tokens";
import {
  liveMarkPillCyberBase,
  liveMarkTextCyberBase,
} from "../../ui/liveMarkCyberStyles";
import { MOBILE_GAMES_CARD_MAX_WIDTH } from "./gamesMobileLayout";
import {
  DISPLAY_FONT_FAMILY,
  NUMERIC_FONT_FAMILY,
} from "./gameCardDisplayUtils";
import {
  MATCH_CARD_DISPLAY_FONT,
  MATCH_CARD_METRIC_FONT,
  MATCH_CARD_SCORE_FONT,
} from "./matchCardTypography";

export const gameCardListStyles = StyleSheet.create({
  body: {
    color: colors.textSecondary,
    fontSize: typography.body,
  },
  listArea: {
    marginTop: 4,
  },
  listContent: {
    gap: 10,
    paddingBottom: spacing.xl,
    paddingTop: 0,
    paddingHorizontal: 12,
  },
  gameCardOuter: {
    position: "relative",
    overflow: "visible",
    width: "100%",
    maxWidth: MOBILE_GAMES_CARD_MAX_WIDTH,
    alignSelf: "center",
  },
  cardPressableBody: {
    flex: 1,
    zIndex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 0,
    gap: 2,
  },
  cardMainContent: {
    flexShrink: 0,
  },
  cardFineInteriorContent: {
    paddingHorizontal: 8,
    paddingTop: 2,
    paddingBottom: 0,
    gap: 1,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    marginBottom: 1,
    gap: spacing.xs,
  },
  roundLabelText: {
    flex: 1,
    color: "rgba(241,245,255,0.95)",
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 22,
    letterSpacing: 1.6,
    textAlign: "center",
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: MATCH_CARD_DISPLAY_FONT,
    transform: [{ skewX: "-10deg" }],
  },
  matchupGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 4,
    marginTop: 0,
    marginBottom: 0,
  },
  teamColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 84,
  },
  teamTopGroup: {
    alignItems: "center",
    gap: 2,
    marginTop: 2,
  },
  teamBottomGroup: {
    alignItems: "center",
    gap: 0,
    marginTop: 2,
    marginBottom: 0,
  },
  sideLabel: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 15,
    letterSpacing: 0.96,
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: DISPLAY_FONT_FAMILY,
  },
  teamMark: {
    width: 62,
    height: 62,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  teamNameMain: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "400",
    textAlign: "center",
    letterSpacing: 0.96,
    lineHeight: 18,
    marginTop: 0,
    marginBottom: 0,
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: MATCH_CARD_DISPLAY_FONT,
    maxWidth: "100%",
    transform: [{ skewX: "-6deg" }],
  },
  teamRecordText: {
    color: "rgba(226,232,240,0.7)",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 11,
    marginTop: 0,
    letterSpacing: 0.2,
    includeFontPadding: false,
    fontFamily: MATCH_CARD_METRIC_FONT,
  },
  centerColumn: {
    flex: 1.05,
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    marginTop: 0,
    paddingTop: 1,
  },
  centerScoreWrap: {
    width: "96%",
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    paddingTop: 0,
  },
  seriesText: {
    marginTop: 2,
    color: "#f7d449",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    lineHeight: 13,
    includeFontPadding: false,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
    fontFamily: NUMERIC_FONT_FAMILY,
  },
  centerText: {
    color: "rgba(239,245,255,0.96)",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 26,
    textAlign: "center",
    letterSpacing: 0.15,
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
    fontFamily: NUMERIC_FONT_FAMILY,
    textShadowColor: "rgba(0,0,0,0.45)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  centerTextScoreRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 8,
    maxWidth: "100%",
  },
  centerTextScoreRowWc: {
    marginTop: 2,
    gap: 10,
  },
  centerTextScoreNum: {
    flexShrink: 0,
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
    fontStyle: "italic",
    lineHeight: 20,
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
    fontFamily: MATCH_CARD_SCORE_FONT,
    textShadowColor: "rgba(0,0,0,0.4)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  centerTextScoreNumWc: {
    fontSize: 22,
    lineHeight: 24,
  },
  centerScoreDash: {
    flexShrink: 0,
    color: "rgba(255,255,255,0.7)",
    fontSize: 18,
    fontWeight: "900",
    fontStyle: "italic",
    lineHeight: 20,
    fontFamily: MATCH_CARD_SCORE_FONT,
  },
  centerScoreDashWc: {
    fontSize: 22,
    lineHeight: 24,
  },
  centerSubline: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    lineHeight: 14,
    textAlign: "center",
    includeFontPadding: false,
    fontFamily: MATCH_CARD_DISPLAY_FONT,
  },
  centerSublineWc: {
    fontSize: 11,
    opacity: 0.8,
  },
  liveMarkWrap: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    gap: 3,
  },
  liveScoreStack: {
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    minHeight: 36,
  },
  liveMarkPill: liveMarkPillCyberBase,
  liveMarkText: liveMarkTextCyberBase,
  leagueDividerWrap: {
    width: "100%",
    marginTop: 6,
    paddingTop: 0,
  },
  leagueDivider: {
    height: 1,
    width: "100%",
    borderRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  cardFooterShell: {
    width: "100%",
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 10,
  },
  lineFrameInterior: {
    paddingHorizontal: 8,
    paddingTop: 20,
    paddingBottom: 18,
  },
  lineFrameTeamMark: {
    width: 54,
    height: 54,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  lineFrameTeamName: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "400",
    textAlign: "center",
    letterSpacing: 1.2,
    lineHeight: 19,
    marginTop: 4,
    marginBottom: 0,
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: MATCH_CARD_DISPLAY_FONT,
    maxWidth: "100%",
    transform: [{ skewX: "-6deg" }],
  },
  lineFrameTeamColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 72,
  },
});
