import { Platform, StyleSheet } from "react-native";
import { colors, spacing } from "../../theme/tokens";
import {
  liveMarkPillCyberBase,
  liveMarkTextCyberBase,
} from "../../ui/liveMarkCyberStyles";
import { MOBILE_GAMES_CARD_MAX_WIDTH } from "./gamesMobileLayout";
import { DISPLAY_FONT_FAMILY, NUMERIC_FONT_FAMILY } from "./gameCardDisplayUtils";
import { MATCH_CARD_SCORE_FONT } from "./matchCardTypography";

/** 試合一覧カード（GameCardList / 予想一覧）共通スタイル */
export const gameCardListStyles = StyleSheet.create({
  listArea: {
    marginTop: 4,
  },
  listContent: {
    gap: 10,
    paddingBottom: spacing.xl,
    paddingTop: 0,
    paddingHorizontal: 4,
  },
  body: {
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 24,
  },
  gameCardOuter: {
    position: "relative",
    overflow: "visible",
    width: "100%",
    maxWidth: MOBILE_GAMES_CARD_MAX_WIDTH,
    alignSelf: "center",
  },
  cardFineShellBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  cardPressableBody: {
    flex: 1,
    zIndex: 1,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 0,
    gap: 2,
  },
  cardFineInteriorContent: {
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 2,
    gap: 2,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    marginBottom: 3,
    gap: spacing.xs,
  },
  roundLabelText: {
    flex: 1,
    color: "rgba(241,245,255,0.95)",
    fontSize: 21,
    fontWeight: "800",
    lineHeight: 24,
    letterSpacing: 1,
    textAlign: "center",
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: DISPLAY_FONT_FAMILY,
  },
  matchupGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 5,
    marginTop: 0,
    marginBottom: 0,
  },
  teamColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 94,
  },
  teamTopGroup: {
    alignItems: "center",
    gap: 3,
    marginTop: 3,
  },
  teamBottomGroup: {
    alignItems: "center",
    gap: 0,
    marginTop: 2,
    marginBottom: 0,
  },
  teamBottomGroupWc: {
    width: 72,
    alignItems: "center",
    marginTop: 3,
  },
  sideLabel: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 14,
    letterSpacing: 0.96,
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: DISPLAY_FONT_FAMILY,
  },
  teamMark: {
    width: 62,
    height: 62,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  teamNameMain: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 0.5,
    lineHeight: 18,
    marginTop: 0,
    marginBottom: 0,
    includeFontPadding: false,
    textTransform: "uppercase",
    fontFamily: DISPLAY_FONT_FAMILY,
    maxWidth: "100%",
  },
  teamNameMainWc: {
    width: 72,
    maxWidth: 72,
    paddingTop: 2,
    lineHeight: 17,
  },
  teamRecordText: {
    color: "rgba(226,232,240,0.82)",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 11,
    marginTop: -1,
    letterSpacing: 0.2,
    includeFontPadding: false,
    fontFamily: NUMERIC_FONT_FAMILY,
  },
  centerColumn: {
    flex: 1.05,
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    marginTop: 0,
    paddingTop: 1,
  },
  centerScoreWrap: {
    width: "96%",
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingTop: 0,
  },
  seriesText: {
    marginTop: 2,
    color: "#f7d449",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    lineHeight: 13,
    includeFontPadding: false,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
    fontFamily: NUMERIC_FONT_FAMILY,
  },
  centerText: {
    color: "rgba(239,245,255,0.96)",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 26,
    textAlign: "center",
    letterSpacing: 0.15,
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
    fontFamily: NUMERIC_FONT_FAMILY,
    textShadowColor: "rgba(0,0,0,0.45)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  centerTextScore: {
    textAlign: "center",
  },
  centerTextScoreRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 8,
    maxWidth: "100%",
  },
  centerTextScoreNum: {
    flexShrink: 0,
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 22,
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
    fontFamily: MATCH_CARD_SCORE_FONT,
    letterSpacing: -0.4,
    textShadowColor: "rgba(0,0,0,0.4)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  centerScoreDash: {
    flexShrink: 0,
    color: "rgba(255,255,255,0.5)",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 22,
    fontFamily: MATCH_CARD_SCORE_FONT,
  },
  centerSubline: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 12,
    lineHeight: 14,
    textAlign: "center",
    includeFontPadding: false,
  },
  liveMarkWrap: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    gap: 4,
  },
  liveScoreStack: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    minHeight: 44,
  },
  liveMarkPill: liveMarkPillCyberBase,
  liveMarkText: liveMarkTextCyberBase,
  /** 得点ブロックと league 仕切り棒の間 — Web mobile dense `mt-1.5 md:mt-2` */
  leagueDividerWrap: {
    width: "100%",
    marginTop: "auto",
    paddingTop: 8,
  },
  leagueDivider: {
    height: 2,
    width: "100%",
    borderRadius: 999,
    shadowColor: "rgb(0, 245, 255)",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 3,
  },
  wcBroadcastRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
    marginTop: 6,
    paddingVertical: 4,
  },
  wcBroadcastLabel: {
    flexShrink: 0,
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    fontWeight: "600",
    includeFontPadding: false,
    fontFamily: DISPLAY_FONT_FAMILY,
  },
  cardFooterShell: {
    width: "100%",
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  cardAction: {
    width: "100%",
    minHeight: 32,
    borderRadius: 6,
    borderWidth: 0,
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    marginTop: 0,
    marginBottom: 2,
    paddingVertical: 0,
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
});
