/**
 * functions 用の選手名インデックスを生成（得点者名→playerId 解決用）
 * 実行: npx tsx scripts/generate-wc-squad-index-for-functions.ts
 */
import fs from "fs";
import path from "path";
import { WC_GENERATED_SQUADS } from "../lib/wc/squads/_generatedSquads";

function main() {
  const lines: string[] = [
    "// Auto-generated by scripts/generate-wc-squad-index-for-functions.ts — do not edit",
    "",
    "export type WcSquadNameEntry = { id: string; name: string };",
    "",
    "export const WC_SQUAD_NAME_INDEX: Record<string, WcSquadNameEntry[]> = {",
  ];

  for (const [iso3, players] of Object.entries(WC_GENERATED_SQUADS).sort()) {
    if (!players?.length) continue;
    lines.push(`  "${iso3}": [`);
    for (const p of players) {
      lines.push(`    { id: ${JSON.stringify(p.id)}, name: ${JSON.stringify(p.name)} },`);
    }
    lines.push("  ],");
  }

  lines.push("};");
  lines.push("");

  const out = path.join(
    process.cwd(),
    "functions/src/wc/squadNameIndex.ts"
  );
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, lines.join("\n"));
  console.log(`Wrote ${out}`);
}

main();
