/**
 * Wikipedia 2026 FIFA World Cup squads テキストから名簿 TS を生成する。
 *
 * 入力: agent-tools の Wikipedia 全文テキスト（またはパス指定）
 * 出力: lib/wc/squads/_generatedSquads.ts
 *
 *   npx tsx scripts/generate-wc-squads.ts [wikipedia.txt]
 */

import fs from "fs";
import path from "path";

const WIKI_TEAM_TO_ISO3: Record<string, string> = {
  "Czech Republic": "cze",
  Mexico: "mex",
  "South Africa": "zaf",
  "South Korea": "kor",
  "Bosnia and Herzegovina": "bih",
  Canada: "can",
  Qatar: "qat",
  Switzerland: "che",
  Brazil: "bra",
  Haiti: "hti",
  Morocco: "mar",
  Scotland: "sct",
  Australia: "aus",
  Paraguay: "pry",
  Turkey: "tur",
  "United States": "usa",
  "Curaçao": "cuw",
  Ecuador: "ecu",
  Germany: "deu",
  "Ivory Coast": "civ",
  Japan: "jpn",
  Netherlands: "nld",
  Sweden: "swe",
  Tunisia: "tun",
  Belgium: "bel",
  Egypt: "egy",
  Iran: "irn",
  "New Zealand": "nzl",
  "Cape Verde": "cpv",
  "Saudi Arabia": "sau",
  Spain: "esp",
  Uruguay: "ury",
  France: "fra",
  Iraq: "irq",
  Norway: "nor",
  Senegal: "sen",
  Algeria: "dza",
  Argentina: "arg",
  Austria: "aut",
  Jordan: "jor",
  Colombia: "col",
  "DR Congo": "cod",
  Portugal: "prt",
  Uzbekistan: "uzb",
  Croatia: "hrv",
  England: "eng",
  Ghana: "gha",
  Panama: "pan",
};

type RawPlayer = {
  name: string;
  pos: "GK" | "DF" | "MF" | "FW";
  club: string;
  captain: boolean;
};

function stripAccents(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ł/g, "l")
    .replace(/Ł/g, "L")
    .replace(/ø/g, "o")
    .replace(/Ø/g, "O")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .replace(/ß/g, "ss");
}

function slugify(name: string): string {
  const clean = stripAccents(name)
    .replace(/\(.*?\)/g, "")
    .trim();
  const parts = clean.split(/\s+/).filter(Boolean);
  const last = parts[parts.length - 1] ?? clean;
  return last
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function fifaPosToWc(pos: string): "GK" | "DF" | "MF" | "FW" {
  if (pos.includes("GK")) return "GK";
  if (pos.includes("DF")) return "DF";
  if (pos.includes("FW")) return "FW";
  return "MF";
}

function parseWiki(text: string): Record<string, RawPlayer[]> {
  const result: Record<string, RawPlayer[]> = {};
  const sections = text.split(/^### /m).slice(1);
  for (const section of sections) {
    const lines = section.split("\n");
    const teamName = lines[0]?.trim();
    if (!teamName || !WIKI_TEAM_TO_ISO3[teamName]) continue;
    const iso3 = WIKI_TEAM_TO_ISO3[teamName];
    const players: RawPlayer[] = [];
    for (const line of lines) {
      if (!line.startsWith("|") || line.includes("No. | Pos.")) continue;
      const cols = line.split("|").map((c) => c.trim());
      if (cols.length < 8) continue;
      const posCol = cols[2];
      const nameCol = cols[3];
      const clubCol = cols[7];
      if (!posCol?.match(/^\d/)) continue;
      const captain = /\(captain\)/i.test(nameCol);
      const name = nameCol.replace(/\(captain\)/gi, "").trim();
      players.push({
        name,
        pos: fifaPosToWc(posCol),
        club: clubCol,
        captain,
      });
    }
    if (players.length > 0) result[iso3] = players;
  }
  return result;
}

function makeUniqueIds(iso3: string, players: RawPlayer[]) {
  const used = new Map<string, number>();
  return players.map((p) => {
    let slug = slugify(p.name);
    if (!slug) slug = "player";
    const count = used.get(slug) ?? 0;
    used.set(slug, count + 1);
    const id =
      count === 0 ? `${iso3}-${slug}` : `${iso3}-${slug}-${count + 1}`;
    return { ...p, id };
  });
}

function esc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function emitSquads(data: Record<string, ReturnType<typeof makeUniqueIds>>) {
  const iso3List = Object.keys(WIKI_TEAM_TO_ISO3).map(
    (k) => WIKI_TEAM_TO_ISO3[k],
  );
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-wc-squads.ts — FIFA final 26-man lists (2026-06-02)",
    "// Source: Wikipedia 2026 FIFA World Cup squads",
    "",
    'import type { WcTeamSquad } from "../squadTypes";',
    "",
    "export const WC_GENERATED_SQUADS: Record<string, WcTeamSquad[\"squad\"]> = {",
  ];

  for (const iso3 of iso3List.sort()) {
    const players = data[iso3];
    if (!players?.length) {
      console.warn(`WARN: missing squad for ${iso3}`);
      continue;
    }
    lines.push(`  ${iso3}: [`);
    for (const p of players) {
      const fields = [
        `id: "${esc(p.id)}"`,
        `name: "${esc(p.name)}"`,
        `pos: "${p.pos}"`,
        `club: "${esc(p.club)}"`,
      ];
      if (p.captain) fields.push("captain: true");
      lines.push(`    { ${fields.join(", ")} },`);
    }
    lines.push("  ],");
  }
  lines.push("};");
  lines.push("");
  lines.push("export const WC_SQUAD_ISO3_LIST = [");
  for (const iso3 of iso3List.sort()) {
    if (data[iso3]?.length) lines.push(`  "${iso3}",`);
  }
  lines.push("] as const;");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const input =
    process.argv[2] ??
    path.join(
      process.env.HOME ?? "",
      ".cursor/projects/Users-rikutokamiya-Desktop-nextjs-boilerplate/agent-tools/6d767797-41b4-4866-95ad-2bca4923e950.txt",
    );
  const text = fs.readFileSync(input, "utf8");
  const parsed = parseWiki(text);
  const withIds: Record<string, ReturnType<typeof makeUniqueIds>> = {};
  for (const [iso3, players] of Object.entries(parsed)) {
    withIds[iso3] = makeUniqueIds(iso3, players);
    console.log(`${iso3}: ${players.length} players`);
  }
  const out = path.join(
    process.cwd(),
    "lib/wc/squads/_generatedSquads.ts",
  );
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, emitSquads(withIds));
  console.log(`Wrote ${out}`);
}

main();
