/**
 * 複数メディア（Goal / RotoWire / ESPN / FourFourTwo）の予想XIを参考に
 * 自社編集の予想スタメンを合成し _generatedLineups.ts を出力。
 *
 *   npx tsx scripts/scrape-rotowire-wc-lineups.ts   # RotoWire 更新時
 *   npx tsx scripts/generate-wc-predicted-lineups.ts
 */

import fs from "fs";
import path from "path";
import type { WcFormationCode, WcSquadPlayer } from "../lib/wc/squadTypes";
import { WC_GENERATED_SQUADS } from "../lib/wc/squads/_generatedSquads";
import { getWcKeyPlayers } from "../lib/wc/rosters";
import { matchPlayer } from "../lib/wc/squads/lineupMatching";
import {
  resolveRawLineup,
  synthesizeLineup,
  type ResolvedSourceLineup,
} from "../lib/wc/squads/synthesizeLineup";
import { buildLineupSlots } from "../lib/wc/formationLayouts";
import { GOAL_LINEUPS } from "../lib/wc/squads/sources/goalLineups";
import { ESPN_LINEUPS } from "../lib/wc/squads/sources/espnLineups";
import { FOUR_FOUR_TWO_LINEUPS } from "../lib/wc/squads/sources/fourFourTwoLineups";
import { MATCH_LINEUPS } from "../lib/wc/squads/sources/matchLineups";
import { CBS_LINEUPS } from "../lib/wc/squads/sources/cbsLineups";

// rotowireLineups.ts はスクレイパーで生成（未実行時は空配列にフォールバック）
let ROTOWIRE_LINEUPS: typeof GOAL_LINEUPS = [];
try {
  const mod = await import("../lib/wc/squads/sources/rotowireLineups");
  ROTOWIRE_LINEUPS = mod.ROTOWIRE_LINEUPS;
} catch {
  console.warn("rotowireLineups.ts not found — run scrape-rotowire-wc-lineups.ts first");
}

const SOURCE_WEIGHTS = {
  goal: 1.0,
  rotowire: 0.95,
  espn: 1.15,
  fourFourTwo: 0.9,
  cbs: 1.05,
} as const;

const ALL_ISO3 = Object.keys(WC_GENERATED_SQUADS).sort();

function keyPlayerIdsForTeam(iso3: string, squad: WcSquadPlayer[]): Set<string> {
  const teamId = `wc-${iso3}`;
  const keyPlayers = getWcKeyPlayers(teamId);
  const ids = new Set<string>();
  for (const kp of keyPlayers) {
    const id = matchPlayer(iso3, squad, kp.name);
    if (id) ids.add(id);
  }
  return ids;
}

function sourcesForTeam(iso3: string, squad: WcSquadPlayer[]): ResolvedSourceLineup[] {
  const resolved: ResolvedSourceLineup[] = [];

  const goal = GOAL_LINEUPS.find((l) => l.iso3 === iso3);
  if (goal) {
    const r = resolveRawLineup(iso3, squad, goal, "goal", SOURCE_WEIGHTS.goal);
    if (r) resolved.push(r);
  }

  const rw = ROTOWIRE_LINEUPS.find((l) => l.iso3 === iso3);
  if (rw) {
    const r = resolveRawLineup(iso3, squad, rw, "rotowire", SOURCE_WEIGHTS.rotowire);
    if (r) resolved.push(r);
  }

  const espn = ESPN_LINEUPS.find((l) => l.iso3 === iso3);
  if (espn) {
    const r = resolveRawLineup(iso3, squad, espn, "espn", SOURCE_WEIGHTS.espn);
    if (r) resolved.push(r);
  }

  const fft = FOUR_FOUR_TWO_LINEUPS.find((l) => l.iso3 === iso3);
  if (fft) {
    const r = resolveRawLineup(iso3, squad, fft, "fourFourTwo", SOURCE_WEIGHTS.fourFourTwo);
    if (r) resolved.push(r);
  }

  const cbs = CBS_LINEUPS.find((l) => l.iso3 === iso3);
  if (cbs) {
    const r = resolveRawLineup(iso3, squad, cbs, "cbs", SOURCE_WEIGHTS.cbs);
    if (r) resolved.push(r);
  }

  return resolved;
}

function main() {
  const out: Record<
    string,
    { formation: WcFormationCode; slots: NonNullable<ReturnType<typeof synthesizeLineup>>["slots"] }
  > = {};
  const errors: string[] = [];
  const stats = { match: 0, multi: 0, single: 0, failed: 0 };
  const primaryCounts = new Map<string, number>();

  for (const iso3 of ALL_ISO3) {
    const squad = WC_GENERATED_SQUADS[iso3];
    if (!squad?.length) {
      errors.push(`${iso3}: no squad`);
      continue;
    }

    const matchLineup = MATCH_LINEUPS.find((l) => l.iso3 === iso3);
    if (matchLineup) {
      const resolved = resolveRawLineup(iso3, squad, matchLineup, "match", 100);
      if (!resolved) {
        errors.push(`${iso3}: confirmed match lineup failed to resolve`);
        stats.failed++;
        continue;
      }
      const slots = buildLineupSlots(
        resolved.formation,
        resolved.playerIds as [
          string, string, string, string, string, string,
          string, string, string, string, string,
        ],
      );
      out[iso3] = { formation: resolved.formation, slots };
      stats.match++;
      continue;
    }

    const sources = sourcesForTeam(iso3, squad);
    if (!sources.length) {
      errors.push(`${iso3}: no resolvable sources`);
      stats.failed++;
      continue;
    }

    const keyIds = keyPlayerIdsForTeam(iso3, squad);
    const result = synthesizeLineup(squad, sources, keyIds);
    if (!result) {
      errors.push(`${iso3}: synthesis failed (${sources.length} sources)`);
      stats.failed++;
      continue;
    }

    if (result.sourceCount > 1) stats.multi++;
    else stats.single++;
    out[iso3] = { formation: result.formation, slots: result.slots };
  }

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-wc-predicted-lineups.ts",
    "// Predicted lineups: confirmed match XIs override media synthesis for played teams",
    "",
    'import type { WcPredictedLineup } from "../squadTypes";',
    "",
    "export const WC_PREDICTED_LINEUPS: Record<string, WcPredictedLineup> = {",
  ];

  for (const [iso3, data] of Object.entries(out).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${iso3}: {`);
    lines.push(`    formation: "${data.formation}",`);
    lines.push("    slots: [");
    for (const s of data.slots) {
      lines.push(`      { playerId: "${s.playerId}", x: ${s.x}, y: ${s.y} },`);
    }
    lines.push("    ],");
    lines.push("  },");
  }
  lines.push("};");
  lines.push("");

  const outPath = path.join(process.cwd(), "lib/wc/squads/_generatedLineups.ts");
  fs.writeFileSync(outPath, lines.join("\n"));

  console.log(`Wrote ${outPath} (${Object.keys(out).length}/48 teams)`);
  console.log(
    `  Confirmed match XIs: ${stats.match}, Multi-source: ${stats.multi}, Single-source: ${stats.single}, Failed: ${stats.failed}`,
  );

  if (errors.length) {
    console.error("ERRORS:");
    for (const e of errors) console.error("  " + e);
    if (Object.keys(out).length < 48) process.exit(1);
  }
}

main();
