/**
 * RotoWire 2026 World Cup グループプレビュー12記事から予想XIを抽出し TS を生成。
 *
 *   npx tsx scripts/scrape-rotowire-wc-lineups.ts
 */

import fs from "fs";
import path from "path";
import type { WcFormationCode } from "../lib/wc/squadTypes";
import { inferFormationFromPlayerGroups } from "../lib/wc/squads/synthesizeLineup";

const GROUP_ARTICLE_IDS = [
  111369, 111899, 109040, 110622, 109286, 112643,
  109591, 109699, 111129, 109964, 113000, 113532,
];

const TEAM_NAME_TO_ISO3: Record<string, string> = {
  Algeria: "dza",
  "Saudi Arabia": "sau",
  Argentina: "arg",
  Australia: "aus",
  Austria: "aut",
  Belgium: "bel",
  "Bosnia and Herzegovina": "bih",
  Bosnia: "bih",
  Brazil: "bra",
  Canada: "can",
  "Cape Verde": "cpv",
  Colombia: "col",
  "South Korea": "kor",
  Korea: "kor",
  "Ivory Coast": "civ",
  "Côte d'Ivoire": "civ",
  "Cote d'Ivoire": "civ",
  Curaçao: "cuw",
  Curacao: "cuw",
  Croatia: "hrv",
  Ecuador: "ecu",
  Egypt: "egy",
  France: "fra",
  Germany: "deu",
  Ghana: "gha",
  Japan: "jpn",
  Jordan: "jor",
  Haiti: "hti",
  England: "eng",
  Iran: "irn",
  Iraq: "irq",
  Morocco: "mar",
  Mexico: "mex",
  Norway: "nor",
  "New Zealand": "nzl",
  Netherlands: "nld",
  Panama: "pan",
  Paraguay: "pry",
  Portugal: "prt",
  Qatar: "qat",
  Czechia: "cze",
  "Czech Republic": "cze",
  "DR Congo": "cod",
  "Democratic Republic of Congo": "cod",
  Scotland: "sct",
  Senegal: "sen",
  Spain: "esp",
  "United States": "usa",
  USA: "usa",
  "South Africa": "zaf",
  Sweden: "swe",
  Switzerland: "che",
  Tunisia: "tun",
  Turkey: "tur",
  Turkiye: "tur",
  Uruguay: "ury",
  Croaita: "hrv",
  Uzbekistan: "uzb",
};

type ParsedLineup = {
  iso3: string;
  teamName: string;
  formation: WcFormationCode;
  players: string[];
};

function cleanHtml(text: string): string {
  return text
    .replace(/&nbsp;/g, " ")
    .replace(/<br\s*\/?>/gi, ";")
    .replace(/<[^>]+>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function parseFigcaption(raw: string): Omit<ParsedLineup, "iso3"> | null {
  const text = cleanHtml(raw);
  const m = text.match(
    /2026 World Cup\s*:\s*(.+?)\s+Predicted Lineup:\s*(.+?)\.?$/i,
  );
  if (!m) return null;

  const teamName = m[1]!.trim();
  const body = m[2]!.trim();
  const groups = body
    .split(";")
    .map((g) =>
      g
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0),
    )
    .filter((g) => g.length > 0);
  const players = groups.flat();
  if (players.length !== 11) return null;

  return {
    teamName,
    formation: inferFormationFromPlayerGroups(groups),
    players,
  };
}

async function fetchArticle(articleId: number): Promise<string> {
  const url = `https://www.rotowire.com/soccer/article/-${articleId}`;
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; wc-lineup-scraper/1.0)" },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for article ${articleId}`);
  return res.text();
}

function extractLineups(html: string): ParsedLineup[] {
  const results: ParsedLineup[] = [];
  const re = /<figcaption>([^<]*(?:<(?!\/figcaption>)[^<]*)*)<\/figcaption>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html))) {
    const parsed = parseFigcaption(m[1]!);
    if (!parsed) continue;
    const iso3 = TEAM_NAME_TO_ISO3[parsed.teamName];
    if (!iso3) {
      console.warn(`Unknown team name: "${parsed.teamName}"`);
      continue;
    }
    results.push({ iso3, ...parsed });
  }
  return results;
}

async function main() {
  const byIso = new Map<string, ParsedLineup>();

  for (const id of GROUP_ARTICLE_IDS) {
    console.log(`Fetching article ${id}...`);
    const html = await fetchArticle(id);
    const lineups = extractLineups(html);
    console.log(`  → ${lineups.length} lineups`);
    for (const lu of lineups) {
      if (byIso.has(lu.iso3)) {
        console.warn(`  duplicate ${lu.iso3}, keeping first`);
        continue;
      }
      byIso.set(lu.iso3, lu);
    }
  }

  const sorted = [...byIso.values()].sort((a, b) => a.iso3.localeCompare(b.iso3));
  console.log(`Total unique teams: ${sorted.length}/48`);

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/scrape-rotowire-wc-lineups.ts",
    "// Source: RotoWire 2026 World Cup group previews (2026-04〜05)",
    "",
    'import type { RawSourceLineup } from "./goalLineups";',
    "",
    "export const ROTOWIRE_LINEUPS: RawSourceLineup[] = [",
  ];

  for (const lu of sorted) {
    const playerList = lu.players.map((p) => JSON.stringify(p)).join(", ");
    lines.push(
      `  { iso3: "${lu.iso3}", formation: "${lu.formation}", players: [${playerList}] },`,
    );
  }
  lines.push("];");
  lines.push("");

  const outPath = path.join(
    process.cwd(),
    "lib/wc/squads/sources/rotowireLineups.ts",
  );
  fs.writeFileSync(outPath, lines.join("\n"));
  console.log(`Wrote ${outPath}`);

  if (sorted.length < 48) {
    const missing = 48 - sorted.length;
    console.warn(`Warning: ${missing} teams missing from RotoWire scrape`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
