/**
 * アカウント削除画面文言（7言語）。
 */
import { L, resolveLocalizedLang } from "@/lib/i18n/localize";

export function deleteAccountCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    title: L(lang, {
      ja: "アカウント削除",
      en: "Delete Account",
      ko: "계정 삭제",
      zh: "删除账户",
      es: "Eliminar cuenta",
      pt: "Excluir conta",
      fr: "Supprimer le compte",
    }),
    desc: L(lang, {
      ja: "アカウントを削除すると、プロフィール情報は消去され、ログインできなくなります。投稿データなどの一部はシステム上に残る場合があります。",
      en: "Deleting your account removes your profile and you will no longer be able to sign in. Some historical data may remain in the system.",
      ko: "계정을 삭제하면 프로필 정보가 삭제되고 로그인할 수 없습니다. 게시 데이터 등은 시스템에 남을 수 있습니다.",
      zh: "删除账户后，资料信息将被清除且无法登录。部分帖子等数据可能仍保留在系统中。",
      es: "Al eliminar tu cuenta se borra el perfil y ya no podrás iniciar sesión. Algunos datos históricos pueden permanecer.",
      pt: "Excluir a conta remove seu perfil e você não poderá mais entrar. Alguns dados históricos podem permanecer.",
      fr: "Supprimer le compte efface le profil et vous ne pourrez plus vous connecter. Certaines données peuvent rester.",
    }),
    proNote: L(lang, {
      ja: "Pro をご利用の場合は、削除前に App Store / Google Play でサブスクリプションを解約してください。",
      en: "If you have Pro, cancel your subscription in the App Store / Google Play before deleting.",
      ko: "Pro 이용 중이라면 삭제 전에 App Store / Google Play에서 구독을 해지하세요.",
      zh: "若使用 Pro，请在删除前于 App Store / Google Play 取消订阅。",
      es: "Si tienes Pro, cancela la suscripción en App Store / Google Play antes de eliminar.",
      pt: "Se tiver Pro, cancele a assinatura na App Store / Google Play antes de excluir.",
      fr: "Si vous avez Pro, résiliez l’abonnement dans l’App Store / Google Play avant de supprimer.",
    }),
    password: L(lang, {
      ja: "現在のパスワード",
      en: "Current password",
      ko: "현재 비밀번호",
      zh: "当前密码",
      es: "Contraseña actual",
      pt: "Senha atual",
      fr: "Mot de passe actuel",
    }),
    typeDelete: L(lang, {
      ja: "確認のため DELETE と入力",
      en: "Type DELETE to confirm",
      ko: "확인을 위해 DELETE 입력",
      zh: "输入 DELETE 以确认",
      es: "Escribe DELETE para confirmar",
      pt: "Digite DELETE para confirmar",
      fr: "Tapez DELETE pour confirmer",
    }),
    placeholder: "DELETE",
    submit: L(lang, {
      ja: "アカウントを削除する",
      en: "Delete my account",
      ko: "계정 삭제하기",
      zh: "删除我的账户",
      es: "Eliminar mi cuenta",
      pt: "Excluir minha conta",
      fr: "Supprimer mon compte",
    }),
    submitting: L(lang, {
      ja: "削除中…",
      en: "Deleting…",
      ko: "삭제 중…",
      zh: "删除中…",
      es: "Eliminando…",
      pt: "Excluindo…",
      fr: "Suppression…",
    }),
    needDelete: L(lang, {
      ja: "確認のため DELETE と入力してください。",
      en: "Please type DELETE to confirm.",
      ko: "확인을 위해 DELETE를 입력하세요.",
      zh: "请输入 DELETE 以确认。",
      es: "Escribe DELETE para confirmar.",
      pt: "Digite DELETE para confirmar.",
      fr: "Veuillez taper DELETE pour confirmer.",
    }),
    needPassword: L(lang, {
      ja: "パスワードを入力してください。",
      en: "Please enter your password.",
      ko: "비밀번호를 입력하세요.",
      zh: "请输入密码。",
      es: "Introduce tu contraseña.",
      pt: "Digite sua senha.",
      fr: "Veuillez entrer votre mot de passe.",
    }),
    done: L(lang, {
      ja: "アカウントを削除しました。",
      en: "Your account has been deleted.",
      ko: "계정이 삭제되었습니다.",
      zh: "账户已删除。",
      es: "Tu cuenta ha sido eliminada.",
      pt: "Sua conta foi excluída.",
      fr: "Votre compte a été supprimé.",
    }),
    fail: L(lang, {
      ja: "削除に失敗しました。時間をおいて再度お試しください。",
      en: "Deletion failed. Please try again later.",
      ko: "삭제에 실패했습니다. 잠시 후 다시 시도하세요.",
      zh: "删除失败。请稍后再试。",
      es: "Error al eliminar. Inténtalo más tarde.",
      pt: "Falha ao excluir. Tente novamente mais tarde.",
      fr: "Échec de la suppression. Réessayez plus tard.",
    }),
    back: L(lang, {
      ja: "戻る",
      en: "Back",
      ko: "뒤로",
      zh: "返回",
      es: "Atrás",
      pt: "Voltar",
      fr: "Retour",
    }),
  };
}
