/**
 * チーム詳細 TEAM INFORMATION chrome（9言語）
 */
import { L, resolveLocalizedLang } from "@/lib/i18n/localize";
import type { NbaConferenceId } from "@/lib/nba/nbaConferenceTeams";
import {
  formatChampionshipSeasonLabel,
  type NbaTeamFranchiseResolved,
} from "@/lib/nba/teamFranchise/nbaTeamFranchiseInfo";

export function nbaTeamFranchiseUiCopy(language: string | null | undefined) {
  const lang = resolveLocalizedLang(language);
  return {
    lang,
    sectionTitle: L(lang, {
      ja: "TEAM INFORMATION",
      en: "TEAM INFORMATION",
      ko: "TEAM INFORMATION",
      zh: "TEAM INFORMATION",
      es: "TEAM INFORMATION",
      pt: "TEAM INFORMATION",
      fr: "TEAM INFORMATION",
      de: "TEAM INFORMATION",
      ar: "TEAM INFORMATION",
    }),
    city: L(lang, {
      ja: "本拠地",
      en: "City",
      ko: "연고지",
      zh: "主场城市",
      es: "Ciudad",
      pt: "Cidade",
      fr: "Ville",
      de: "Stadt",
      ar: "المدينة",
    }),
    arena: L(lang, {
      ja: "アリーナ",
      en: "Arena",
      ko: "아레나",
      zh: "球馆",
      es: "Pabellón",
      pt: "Arena",
      fr: "Salle",
      de: "Arena",
      ar: "الصالة",
    }),
    headCoach: L(lang, {
      ja: "HC",
      en: "Head coach",
      ko: "감독",
      zh: "主教练",
      es: "Entrenador",
      pt: "Técnico",
      fr: "Entraîneur",
      de: "Trainer",
      ar: "المدرب",
    }),
    generalManager: L(lang, {
      ja: "GM",
      en: "GM",
      ko: "GM",
      zh: "GM",
      es: "GM",
      pt: "GM",
      fr: "GM",
      de: "GM",
      ar: "GM",
    }),
    owner: L(lang, {
      ja: "オーナー",
      en: "Owner",
      ko: "구단주",
      zh: "老板",
      es: "Propietario",
      pt: "Dono",
      fr: "Propriétaire",
      de: "Eigentümer",
      ar: "المالك",
    }),
    founded: L(lang, {
      ja: "創設",
      en: "Founded",
      ko: "창단",
      zh: "创立",
      es: "Fundación",
      pt: "Fundação",
      fr: "Fondation",
      de: "Gegründet",
      ar: "التأسيس",
    }),
    formerNames: L(lang, {
      ja: "旧名",
      en: "Former names",
      ko: "이전 이름",
      zh: "曾用名",
      es: "Nombres anteriores",
      pt: "Nomes anteriores",
      fr: "Anciens noms",
      de: "Frühere Namen",
      ar: "الأسماء السابقة",
    }),
    championships: L(lang, {
      ja: "優勝回数",
      en: "Titles",
      ko: "우승",
      zh: "总冠军",
      es: "Títulos",
      pt: "Títulos",
      fr: "Titres",
      de: "Titel",
      ar: "الألقاب",
    }),
    lastTitle: L(lang, {
      ja: "直近優勝",
      en: "Last title",
      ko: "최근 우승",
      zh: "最近夺冠",
      es: "Último título",
      pt: "Último título",
      fr: "Dernier titre",
      de: "Letzter Titel",
      ar: "آخر لقب",
    }),
    conference: L(lang, {
      ja: "カンファレンス",
      en: "Conference",
      ko: "콘퍼런스",
      zh: "分区联盟",
      es: "Conferencia",
      pt: "Conferência",
      fr: "Conférence",
      de: "Conference",
      ar: "المؤتمر",
    }),
    division: L(lang, {
      ja: "ディビジョン",
      en: "Division",
      ko: "디비전",
      zh: "赛区",
      es: "División",
      pt: "Divisão",
      fr: "Division",
      de: "Division",
      ar: "القسم",
    }),
    colors: L(lang, {
      ja: "チームカラー",
      en: "Colors",
      ko: "팀 컬러",
      zh: "队色",
      es: "Colores",
      pt: "Cores",
      fr: "Couleurs",
      de: "Farben",
      ar: "الألوان",
    }),
    mascot: L(lang, {
      ja: "マスコット",
      en: "Mascot",
      ko: "마스코트",
      zh: "吉祥物",
      es: "Mascota",
      pt: "Mascote",
      fr: "Mascotte",
      de: "Maskottchen",
      ar: "التميمة",
    }),
    none: L(lang, {
      ja: "—",
      en: "—",
      ko: "—",
      zh: "—",
      es: "—",
      pt: "—",
      fr: "—",
      de: "—",
      ar: "—",
    }),
    conferenceLabel: (c: NbaConferenceId) =>
      c === "east"
        ? L(lang, {
            ja: "イースト",
            en: "Eastern",
            ko: "동부",
            zh: "东部",
            es: "Este",
            pt: "Leste",
            fr: "Est",
            de: "Ost",
            ar: "الشرقي",
          })
        : L(lang, {
            ja: "ウェスト",
            en: "Western",
            ko: "서부",
            zh: "西部",
            es: "Oeste",
            pt: "Oeste",
            fr: "Ouest",
            de: "West",
            ar: "الغربي",
          }),
    divisionLabel: (info: NbaTeamFranchiseResolved) =>
      lang === "ja" ? info.divisionLabel.ja : info.divisionLabel.en,
    lastTitleValue: (info: NbaTeamFranchiseResolved) => {
      const y = formatChampionshipSeasonLabel(info.lastChampionshipSeasonKey);
      return y ?? "—";
    },
    formerNamesValue: (info: NbaTeamFranchiseResolved) =>
      info.formerNames.length > 0 ? info.formerNames.join(" · ") : "—",
    /** HC / GM: 名前 + 就任年 */
    personWithSince: (name: string, sinceYear: number) =>
      L(lang, {
        ja: `${name}（${sinceYear}〜）`,
        en: `${name} (since ${sinceYear})`,
        ko: `${name} (${sinceYear}~)`,
        zh: `${name}（${sinceYear}起）`,
        es: `${name} (desde ${sinceYear})`,
        pt: `${name} (desde ${sinceYear})`,
        fr: `${name} (depuis ${sinceYear})`,
        de: `${name} (seit ${sinceYear})`,
        ar: `${name} (منذ ${sinceYear})`,
      }),
  };
}

export type NbaTeamFranchiseUiCopy = ReturnType<typeof nbaTeamFranchiseUiCopy>;
