// lib/wc/rosters.ts
//
// World Cup ロスターも静的データ扱い（大会前に決まれば大会期間中はほぼ動かない）。
// 全 23–26 名は冗長なので「キープレイヤー数名」だけ。
// フル名簿が要るときはここを増やすだけで OK。
//
// 最終更新: 2026-05-28 頃 — 最終発表済みチームのみ 26 人へ拡張

export type WcPosition = "GK" | "DF" | "MF" | "FW";

export type WcRosterPlayer = {
  /** 背番号 */
  no: number;
  name: string;
  pos: WcPosition;
  /** 所属クラブ（任意） */
  club?: string;
  /** キャプテンマーク */
  captain?: boolean;
};

const WC_ROSTERS: Record<string, WcRosterPlayer[]> = {
  zaf: [
    { no: 1, name: "Ronwen Williams", pos: "GK", club: "Mamelodi Sundowns", captain: true },
    { no: 2, name: "Ricardo Goss", pos: "GK", club: "Siwelele" },
    { no: 3, name: "Sipho Chaine", pos: "GK", club: "Orlando Pirates" },
    { no: 4, name: "Aubrey Modiba", pos: "DF", club: "Mamelodi Sundowns" },
    { no: 5, name: "Khuliso Mudau", pos: "DF", club: "Mamelodi Sundowns" },
    { no: 6, name: "Nkosinathi Sibisi", pos: "DF", club: "Orlando Pirates" },
    { no: 7, name: "Mbekezeli Mbokazi", pos: "DF", club: "Chicago Fire" },
    { no: 8, name: "Ime Okon", pos: "DF", club: "Hannover 96" },
    { no: 9, name: "Samukele Kabini", pos: "DF", club: "Molde" },
    { no: 10, name: "Khulumani Ndamane", pos: "DF", club: "Mamelodi Sundowns" },
    { no: 11, name: "Thabang Matuludi", pos: "DF", club: "Polokwane City" },
    { no: 12, name: "Kamogelo Sebelebele", pos: "DF", club: "Orlando Pirates" },
    { no: 13, name: "Bradley Cross", pos: "DF", club: "Kaizer Chiefs" },
    { no: 14, name: "Olwethu Makhanya", pos: "DF", club: "Philadelphia Union" },
    { no: 15, name: "Teboho Mokoena", pos: "MF", club: "Mamelodi Sundowns" },
    { no: 16, name: "Sphephelo Sithole", pos: "MF", club: "Tondela" },
    { no: 17, name: "Thalente Mbatha", pos: "MF", club: "Orlando Pirates" },
    { no: 18, name: "Jayden Adams", pos: "MF", club: "Mamelodi Sundowns" },
    { no: 19, name: "Themba Zwane", pos: "FW", club: "Mamelodi Sundowns" },
    { no: 20, name: "Lyle Foster", pos: "FW", club: "Burnley" },
    { no: 21, name: "Evidence Makgopa", pos: "FW", club: "Orlando Pirates" },
    { no: 22, name: "Oswin Appollis", pos: "FW", club: "Orlando Pirates" },
    { no: 23, name: "Iqraam Rayners", pos: "FW", club: "Mamelodi Sundowns" },
    { no: 24, name: "Relebohile Mofokeng", pos: "FW", club: "Orlando Pirates" },
    { no: 25, name: "Thapelo Maseko", pos: "FW", club: "AEL Limassol" },
    { no: 26, name: "Tshepang Moremi", pos: "FW", club: "Orlando Pirates" },
  ],
  kor: [
    { no: 1, name: "Kim Seung-gyu", pos: "GK", club: "FC Tokyo" },
    { no: 2, name: "Jo Hyeon-woo", pos: "GK", club: "Ulsan HD" },
    { no: 3, name: "Song Bum-keun", pos: "GK", club: "Jeonbuk Hyundai Motors" },
    { no: 4, name: "Kim Min-jae", pos: "DF", club: "Bayern Munich" },
    { no: 5, name: "Kim Moon-hwan", pos: "DF", club: "Daejeon Hana Citizen" },
    { no: 6, name: "Seol Young-woo", pos: "DF", club: "Red Star Belgrade" },
    { no: 7, name: "Cho Yu-min", pos: "DF", club: "Sharjah" },
    { no: 8, name: "Lee Tae-seok", pos: "DF", club: "Austria Wien" },
    { no: 9, name: "Park Jin-seob", pos: "DF", club: "Zhejiang FC" },
    { no: 10, name: "Kim Tae-hyeon", pos: "DF", club: "Kashima Antlers" },
    { no: 11, name: "Lee Han-beom", pos: "DF", club: "Midtjylland" },
    { no: 12, name: "Jens Castrop", pos: "DF", club: "Borussia Mönchengladbach" },
    { no: 13, name: "Lee Ki-hyuk", pos: "DF", club: "Gangwon FC" },
    { no: 14, name: "Lee Jae-sung", pos: "MF", club: "Mainz 05" },
    { no: 15, name: "Hwang Hee-chan", pos: "MF", club: "Wolverhampton Wanderers" },
    { no: 16, name: "Hwang In-beom", pos: "MF", club: "Feyenoord" },
    { no: 17, name: "Lee Kang-in", pos: "MF", club: "Paris Saint-Germain" },
    { no: 18, name: "Paik Seung-ho", pos: "MF", club: "Birmingham City" },
    { no: 19, name: "Kim Jin-gyu", pos: "MF", club: "Jeonbuk Hyundai Motors" },
    { no: 20, name: "Lee Dong-gyeong", pos: "MF", club: "Ulsan HD" },
    { no: 21, name: "Bae Jun-ho", pos: "MF", club: "Stoke City" },
    { no: 22, name: "Eom Ji-sung", pos: "MF", club: "Swansea City" },
    { no: 23, name: "Yang Hyun-jun", pos: "MF", club: "Celtic" },
    { no: 24, name: "Son Heung-min", pos: "FW", club: "Los Angeles FC", captain: true },
    { no: 25, name: "Cho Gue-sung", pos: "FW", club: "Midtjylland" },
    { no: 26, name: "Oh Hyeon-gyu", pos: "FW", club: "Beşiktaş" },
  ],
  bih: [
    { no: 1, name: "Nikola Vasilj", pos: "GK", club: "FC St. Pauli" },
    { no: 2, name: "Martin Zlomislić", pos: "GK", club: "Rijeka" },
    { no: 3, name: "Osman Hadžikić", pos: "GK", club: "Slaven Belupo" },
    { no: 4, name: "Sead Kolašinac", pos: "DF", club: "Atalanta" },
    { no: 5, name: "Dennis Hadžikadunić", pos: "DF", club: "Sampdoria" },
    { no: 6, name: "Amar Dedić", pos: "DF", club: "Benfica" },
    { no: 7, name: "Nikola Katić", pos: "DF", club: "Schalke 04" },
    { no: 8, name: "Tarik Muharemović", pos: "DF", club: "Sassuolo" },
    { no: 9, name: "Nihad Mujakić", pos: "DF", club: "Gaziantep" },
    { no: 10, name: "Stjepan Radeljić", pos: "DF", club: "Rijeka" },
    { no: 11, name: "Nidal Čelik", pos: "DF", club: "Lens" },
    { no: 12, name: "Amir Hadžiahmetović", pos: "MF", club: "Hull City" },
    { no: 13, name: "Benjamin Tahirović", pos: "MF", club: "Brøndby" },
    { no: 14, name: "Armin Gigović", pos: "MF", club: "Young Boys" },
    { no: 15, name: "Dženis Burnić", pos: "MF", club: "Karlsruher SC" },
    { no: 16, name: "Ivan Bašić", pos: "MF", club: "Astana" },
    { no: 17, name: "Esmir Bajraktarević", pos: "MF", club: "PSV Eindhoven" },
    { no: 18, name: "Amar Memić", pos: "MF", club: "Viktoria Plzeň" },
    { no: 19, name: "Ivan Šunjić", pos: "MF", club: "Pafos" },
    { no: 20, name: "Kerim Alajbegović", pos: "MF", club: "Red Bull Salzburg" },
    { no: 21, name: "Ermin Mahmić", pos: "MF", club: "Slovan Liberec" },
    { no: 22, name: "Edin Džeko", pos: "FW", club: "Schalke 04", captain: true },
    { no: 23, name: "Ermedin Demirović", pos: "FW", club: "VfB Stuttgart" },
    { no: 24, name: "Samed Baždar", pos: "FW", club: "Jagiellonia Białystok" },
    { no: 25, name: "Haris Tabaković", pos: "FW", club: "Borussia Mönchengladbach" },
    { no: 26, name: "Jovo Lukić", pos: "FW", club: "Universitatea Cluj" },
  ],
  bra: [
    { no: 1, name: "Alisson", pos: "GK", club: "Liverpool" },
    { no: 2, name: "Ederson", pos: "GK", club: "Fenerbahçe" },
    { no: 3, name: "Weverton", pos: "GK", club: "Grêmio" },
    { no: 4, name: "Marquinhos", pos: "DF", club: "Paris Saint-Germain" },
    { no: 5, name: "Danilo Luiz", pos: "DF", club: "Flamengo" },
    { no: 6, name: "Alex Sandro", pos: "DF", club: "Flamengo" },
    { no: 7, name: "Gabriel Magalhães", pos: "DF", club: "Arsenal" },
    { no: 8, name: "Bremer", pos: "DF", club: "Juventus" },
    { no: 9, name: "Wesley", pos: "DF", club: "Roma" },
    { no: 10, name: "Roger Ibañez", pos: "DF", club: "Al-Ahli" },
    { no: 11, name: "Douglas Santos", pos: "DF", club: "Zenit Saint Petersburg" },
    { no: 12, name: "Léo Pereira", pos: "DF", club: "Flamengo" },
    { no: 13, name: "Casemiro", pos: "MF", club: "Manchester United", captain: true },
    { no: 14, name: "Lucas Paquetá", pos: "MF", club: "Flamengo" },
    { no: 15, name: "Bruno Guimarães", pos: "MF", club: "Newcastle United" },
    { no: 16, name: "Fabinho", pos: "MF", club: "Al-Ittihad" },
    { no: 17, name: "Danilo Santos", pos: "MF", club: "Botafogo" },
    { no: 18, name: "Neymar", pos: "FW", club: "Santos" },
    { no: 19, name: "Vinícius Júnior", pos: "FW", club: "Real Madrid" },
    { no: 20, name: "Raphinha", pos: "FW", club: "Barcelona" },
    { no: 21, name: "Gabriel Martinelli", pos: "FW", club: "Arsenal" },
    { no: 22, name: "Matheus Cunha", pos: "FW", club: "Manchester United" },
    { no: 23, name: "Endrick", pos: "FW", club: "Lyon" },
    { no: 24, name: "Luiz Henrique", pos: "FW", club: "Zenit Saint Petersburg" },
    { no: 25, name: "Igor Thiago", pos: "FW", club: "Brentford" },
    { no: 26, name: "Rayan", pos: "FW", club: "Bournemouth" },
  ],
  mar: [
    { no: 1, name: "Yassine Bounou", pos: "GK", club: "Al-Hilal" },
    { no: 2, name: "Munir Mohamedi", pos: "GK", club: "RS Berkane" },
    { no: 3, name: "Ahmed Reda Tagnaouti", pos: "GK", club: "AS FAR" },
    { no: 4, name: "Achraf Hakimi", pos: "DF", club: "Paris Saint-Germain", captain: true },
    { no: 5, name: "Nayef Aguerd", pos: "DF", club: "Marseille" },
    { no: 6, name: "Noussair Mazraoui", pos: "DF", club: "Manchester United" },
    { no: 7, name: "Youssef Belammari", pos: "DF", club: "Al Ahly" },
    { no: 8, name: "Anass Salah-Eddine", pos: "DF", club: "PSV Eindhoven" },
    { no: 9, name: "Chadi Riad", pos: "DF", club: "Crystal Palace" },
    { no: 10, name: "Issa Diop", pos: "DF", club: "Fulham" },
    { no: 11, name: "Zakaria El Ouahdi", pos: "DF", club: "Genk" },
    { no: 12, name: "Redouane Halhal", pos: "DF", club: "Mechelen" },
    { no: 13, name: "Sofyan Amrabat", pos: "MF", club: "Real Betis" },
    { no: 14, name: "Azzedine Ounahi", pos: "MF", club: "Girona" },
    { no: 15, name: "Bilal El Khannouss", pos: "MF", club: "VfB Stuttgart" },
    { no: 16, name: "Ismael Saibari", pos: "MF", club: "PSV Eindhoven" },
    { no: 17, name: "Neil El Aynaoui", pos: "MF", club: "Roma" },
    { no: 18, name: "Samir El Mourabet", pos: "MF", club: "Strasbourg" },
    { no: 19, name: "Gessime Yassine", pos: "MF", club: "Strasbourg" },
    { no: 20, name: "Ayyoub Bouaddi", pos: "MF", club: "Lille" },
    { no: 21, name: "Ayoub El Kaabi", pos: "FW", club: "Olympiacos" },
    { no: 22, name: "Abde Ezzalzouli", pos: "FW", club: "Real Betis" },
    { no: 23, name: "Soufiane Rahimi", pos: "FW", club: "Al Ain" },
    { no: 24, name: "Brahim Díaz", pos: "FW", club: "Real Madrid" },
    { no: 25, name: "Chemsdine Talbi", pos: "FW", club: "Sunderland" },
    { no: 26, name: "Ayoube Amaimouni", pos: "FW", club: "Eintracht Frankfurt" },
  ],
  hti: [
    { no: 1, name: "Johny Placide", pos: "GK", club: "Bastia", captain: true },
    { no: 2, name: "Alexandre Pierre", pos: "GK", club: "Sochaux" },
    { no: 3, name: "Josué Duverger", pos: "GK", club: "Cosmos Koblenz" },
    { no: 4, name: "Ricardo Adé", pos: "DF", club: "LDU Quito" },
    { no: 5, name: "Carlens Arcus", pos: "DF", club: "Angers" },
    { no: 6, name: "Martin Expérience", pos: "DF", club: "Nancy" },
    { no: 7, name: "Jean-Kévin Duverne", pos: "DF", club: "Gent" },
    { no: 8, name: "Duke Lacroix", pos: "DF", club: "Colorado Springs Switchbacks" },
    { no: 9, name: "Wilguens Paugain", pos: "DF", club: "Zulte Waregem" },
    { no: 10, name: "Hannes Delcroix", pos: "DF", club: "Lugano" },
    { no: 11, name: "Keeto Thermoncy", pos: "DF", club: "Young Boys" },
    { no: 12, name: "Leverton Pierre", pos: "MF", club: "Vizela" },
    { no: 13, name: "Danley Jean Jacques", pos: "MF", club: "Philadelphia Union" },
    { no: 14, name: "Carl Sainté", pos: "MF", club: "El Paso Locomotive FC" },
    { no: 15, name: "Jean-Ricner Bellegarde", pos: "MF", club: "Wolverhampton Wanderers" },
    { no: 16, name: "Woodensky Pierre", pos: "MF", club: "Violette" },
    { no: 17, name: "Dominique Simon", pos: "MF", club: "Tatran Prešov" },
    { no: 18, name: "Duckens Nazon", pos: "FW", club: "Esteghlal" },
    { no: 19, name: "Frantzdy Pierrot", pos: "FW", club: "Çaykur Rizespor" },
    { no: 20, name: "Derrick Etienne Jr.", pos: "FW", club: "Toronto FC" },
    { no: 21, name: "Louicius Deedson", pos: "FW", club: "FC Dallas" },
    { no: 22, name: "Ruben Providence", pos: "FW", club: "Almere City" },
    { no: 23, name: "Josué Casimir", pos: "FW", club: "Auxerre" },
    { no: 24, name: "Yassin Fortuné", pos: "FW", club: "Vizela" },
    { no: 25, name: "Wilson Isidor", pos: "FW", club: "Sunderland" },
    { no: 26, name: "Lenny Joseph", pos: "FW", club: "Ferencváros" },
  ],
  sct: [
    { no: 1, name: "Craig Gordon", pos: "GK", club: "Heart of Midlothian" },
    { no: 2, name: "Angus Gunn", pos: "GK", club: "Nottingham Forest" },
    { no: 3, name: "Liam Kelly", pos: "GK", club: "Rangers" },
    { no: 4, name: "Andy Robertson", pos: "DF", club: "Liverpool", captain: true },
    { no: 5, name: "Grant Hanley", pos: "DF", club: "Hibernian" },
    { no: 6, name: "Kieran Tierney", pos: "DF", club: "Celtic" },
    { no: 7, name: "Scott McKenna", pos: "DF", club: "Dinamo Zagreb" },
    { no: 8, name: "Jack Hendry", pos: "DF", club: "Al-Ettifaq" },
    { no: 9, name: "Nathan Patterson", pos: "DF", club: "Everton" },
    { no: 10, name: "Anthony Ralston", pos: "DF", club: "Celtic" },
    { no: 11, name: "John Souttar", pos: "DF", club: "Rangers" },
    { no: 12, name: "Aaron Hickey", pos: "DF", club: "Brentford" },
    { no: 13, name: "Dominic Hyam", pos: "DF", club: "Wrexham" },
    { no: 14, name: "John McGinn", pos: "MF", club: "Aston Villa" },
    { no: 15, name: "Scott McTominay", pos: "MF", club: "Napoli" },
    { no: 16, name: "Ryan Christie", pos: "MF", club: "Bournemouth" },
    { no: 17, name: "Kenny McLean", pos: "MF", club: "Norwich City" },
    { no: 18, name: "Billy Gilmour", pos: "MF", club: "Napoli" },
    { no: 19, name: "Lewis Ferguson", pos: "MF", club: "Bologna" },
    { no: 20, name: "Ben Gannon-Doak", pos: "MF", club: "Bournemouth" },
    { no: 21, name: "Findlay Curtis", pos: "MF", club: "Kilmarnock" },
    { no: 22, name: "Lyndon Dykes", pos: "FW", club: "Charlton Athletic" },
    { no: 23, name: "Ché Adams", pos: "FW", club: "Torino" },
    { no: 24, name: "Lawrence Shankland", pos: "FW", club: "Heart of Midlothian" },
    { no: 25, name: "George Hirst", pos: "FW", club: "Ipswich Town" },
    { no: 26, name: "Ross Stewart", pos: "FW", club: "Southampton" },
  ],
  civ: [
    { no: 1, name: "Yahia Fofana", pos: "GK", club: "Çaykur Rizespor" },
    { no: 2, name: "Alban Lafont", pos: "GK", club: "Panathinaikos" },
    { no: 3, name: "Mohamed Koné", pos: "GK", club: "Charleroi" },
    { no: 4, name: "Ghislain Konan", pos: "DF", club: "Gil Vicente" },
    { no: 5, name: "Odilon Kossounou", pos: "DF", club: "Atalanta" },
    { no: 6, name: "Wilfried Singo", pos: "DF", club: "Galatasaray" },
    { no: 7, name: "Evan Ndicka", pos: "DF", club: "Roma" },
    { no: 8, name: "Emmanuel Agbadou", pos: "DF", club: "Beşiktaş" },
    { no: 9, name: "Guéla Doué", pos: "DF", club: "Strasbourg" },
    { no: 10, name: "Ousmane Diomande", pos: "DF", club: "Sporting CP" },
    { no: 11, name: "Clément Akpa", pos: "DF", club: "Auxerre" },
    { no: 12, name: "Franck Kessié", pos: "MF", club: "Al-Ahli", captain: true },
    { no: 13, name: "Jean Michaël Seri", pos: "MF", club: "Maribor" },
    { no: 14, name: "Ibrahim Sangaré", pos: "MF", club: "Nottingham Forest" },
    { no: 15, name: "Seko Fofana", pos: "MF", club: "Porto" },
    { no: 16, name: "Christ Inao Oulaï", pos: "MF", club: "Trabzonspor" },
    { no: 17, name: "Parfait Guiagon", pos: "MF", club: "Charleroi" },
    { no: 18, name: "Nicolas Pépé", pos: "FW", club: "Villarreal" },
    { no: 19, name: "Oumar Diakité", pos: "FW", club: "Cercle Brugge" },
    { no: 20, name: "Simon Adingra", pos: "FW", club: "Monaco" },
    { no: 21, name: "Evann Guessand", pos: "FW", club: "Crystal Palace" },
    { no: 22, name: "Amad Diallo", pos: "FW", club: "Manchester United" },
    { no: 23, name: "Yan Diomande", pos: "FW", club: "RB Leipzig" },
    { no: 24, name: "Bazoumana Touré", pos: "FW", club: "TSG Hoffenheim" },
    { no: 25, name: "Elye Wahi", pos: "FW", club: "Nice" },
    { no: 26, name: "Ange-Yoan Bonny", pos: "FW", club: "Inter Milan" },
  ],
  cuw: [
    { no: 1, name: "Eloy Room", pos: "GK", club: "Miami FC" },
    { no: 2, name: "Trevor Doornbusch", pos: "GK", club: "VVV-Venlo" },
    { no: 3, name: "Tyrick Bodak", pos: "GK", club: "Telstar" },
    { no: 4, name: "Juriën Gaari", pos: "DF", club: "Abha" },
    { no: 5, name: "Roshon van Eijma", pos: "DF", club: "RKC Waalwijk" },
    { no: 6, name: "Sherel Floranus", pos: "DF", club: "PEC Zwolle" },
    { no: 7, name: "Joshua Brenet", pos: "DF", club: "Kayserispor" },
    { no: 8, name: "Shurandy Sambo", pos: "DF", club: "Sparta Rotterdam" },
    { no: 9, name: "Armando Obispo", pos: "DF", club: "PSV Eindhoven" },
    { no: 10, name: "Riechedly Bazoer", pos: "DF", club: "Konyaspor" },
    { no: 11, name: "Deveron Fonville", pos: "DF", club: "NEC" },
    { no: 12, name: "Leandro Bacuna", pos: "MF", club: "Iğdır", captain: true },
    { no: 13, name: "Juninho Bacuna", pos: "MF", club: "Volendam" },
    { no: 14, name: "Godfried Roemeratoe", pos: "MF", club: "RKC Waalwijk" },
    { no: 15, name: "Kevin Felida", pos: "MF", club: "Den Bosch" },
    { no: 16, name: "Livano Comenencia", pos: "MF", club: "Zürich" },
    { no: 17, name: "Ar'jany Martha", pos: "MF", club: "Rotherham United" },
    { no: 18, name: "Tyrese Noslin", pos: "MF", club: "Telstar" },
    { no: 19, name: "Kenji Gorré", pos: "FW", club: "Maccabi Haifa" },
    { no: 20, name: "Brandley Kuwas", pos: "FW", club: "Volendam" },
    { no: 21, name: "Gervane Kastaneer", pos: "FW", club: "Terengganu" },
    { no: 22, name: "Jeremy Antonisse", pos: "FW", club: "Kifisia" },
    { no: 23, name: "Jearl Margaritha", pos: "FW", club: "Beveren" },
    { no: 24, name: "Jürgen Locadia", pos: "FW", club: "Miami FC" },
    { no: 25, name: "Sontje Hansen", pos: "FW", club: "Middlesbrough" },
    { no: 26, name: "Tahith Chong", pos: "FW", club: "Sheffield United" },
  ],
  nld: [
    { no: 1, name: "Bart Verbruggen", pos: "GK", club: "Brighton & Hove Albion" },
    { no: 2, name: "Mark Flekken", pos: "GK", club: "Bayer Leverkusen" },
    { no: 3, name: "Robin Roefs", pos: "GK", club: "Sunderland" },
    { no: 4, name: "Virgil van Dijk", pos: "DF", club: "Liverpool", captain: true },
    { no: 5, name: "Denzel Dumfries", pos: "DF", club: "Inter Milan" },
    { no: 6, name: "Nathan Aké", pos: "DF", club: "Manchester City" },
    { no: 7, name: "Jurriën Timber", pos: "DF", club: "Arsenal" },
    { no: 8, name: "Micky van de Ven", pos: "DF", club: "Tottenham Hotspur" },
    { no: 9, name: "Mats Wieffer", pos: "DF", club: "Brighton & Hove Albion" },
    { no: 10, name: "Jan Paul van Hecke", pos: "DF", club: "Brighton & Hove Albion" },
    { no: 11, name: "Jorrel Hato", pos: "DF", club: "Chelsea" },
    { no: 12, name: "Frenkie de Jong", pos: "MF", club: "Barcelona" },
    { no: 13, name: "Marten de Roon", pos: "MF", club: "Atalanta" },
    { no: 14, name: "Tijjani Reijnders", pos: "MF", club: "Manchester City" },
    { no: 15, name: "Teun Koopmeiners", pos: "MF", club: "Juventus" },
    { no: 16, name: "Ryan Gravenberch", pos: "MF", club: "Liverpool" },
    { no: 17, name: "Justin Kluivert", pos: "MF", club: "Bournemouth" },
    { no: 18, name: "Quinten Timber", pos: "MF", club: "Marseille" },
    { no: 19, name: "Guus Til", pos: "MF", club: "PSV Eindhoven" },
    { no: 20, name: "Memphis Depay", pos: "FW", club: "Corinthians" },
    { no: 21, name: "Wout Weghorst", pos: "FW", club: "Ajax" },
    { no: 22, name: "Donyell Malen", pos: "FW", club: "Roma" },
    { no: 23, name: "Cody Gakpo", pos: "FW", club: "Liverpool" },
    { no: 24, name: "Noa Lang", pos: "FW", club: "Galatasaray" },
    { no: 25, name: "Brian Brobbey", pos: "FW", club: "Sunderland" },
    { no: 26, name: "Crysencio Summerville", pos: "FW", club: "West Ham United" },
  ],
  jpn: [
    { no: 1, name: "Zion Suzuki", pos: "GK", club: "Parma" },
    { no: 22, name: "Yuto Nagatomo", pos: "DF", club: "FC Tokyo" },
    { no: 4, name: "Wataru Endo", pos: "MF", club: "Liverpool", captain: true },
    { no: 8, name: "Daichi Kamada", pos: "MF", club: "Crystal Palace" },
    { no: 7, name: "Takefusa Kubo", pos: "MF", club: "Real Sociedad" },
    { no: 9, name: "Ayase Ueda", pos: "FW", club: "Feyenoord" },
  ],
  swe: [
    { no: 1, name: "Kristoffer Nordfeldt", pos: "GK", club: "AIK" },
    { no: 3, name: "Victor Lindelöf", pos: "DF", club: "Aston Villa", captain: true },
    { no: 20, name: "Lucas Bergvall", pos: "MF", club: "Tottenham" },
    { no: 9, name: "Alexander Isak", pos: "FW", club: "Liverpool" },
    { no: 11, name: "Viktor Gyökeres", pos: "FW", club: "Arsenal" },
    { no: 21, name: "Anthony Elanga", pos: "FW", club: "Newcastle" },
  ],
  tun: [
    { no: 1, name: "Aymen Dahmen", pos: "GK", club: "CS Sfaxien" },
    { no: 2, name: "Sabri Ben Hessen", pos: "GK", club: "Étoile du Sahel" },
    { no: 3, name: "Mouhib Chamakh", pos: "GK", club: "Club Africain" },
    { no: 4, name: "Montassar Talbi", pos: "DF", club: "Lorient" },
    { no: 5, name: "Dylan Bronn", pos: "DF", club: "Servette" },
    { no: 6, name: "Ali Abdi", pos: "DF", club: "Nice" },
    { no: 7, name: "Yan Valery", pos: "DF", club: "Young Boys" },
    { no: 8, name: "Mohamed Amine Ben Hamida", pos: "DF", club: "Espérance de Tunis" },
    { no: 9, name: "Moutaz Neffati", pos: "DF", club: "IFK Norrköping" },
    { no: 10, name: "Omar Rekik", pos: "DF", club: "Maribor" },
    { no: 11, name: "Adem Arous", pos: "DF", club: "Kasımpaşa" },
    { no: 12, name: "Raed Chikhaoui", pos: "DF", club: "US Monastir" },
    { no: 13, name: "Ellyes Skhiri", pos: "MF", club: "Eintracht Frankfurt", captain: true },
    { no: 14, name: "Hannibal Mejbri", pos: "MF", club: "Burnley" },
    { no: 15, name: "Anis Ben Slimane", pos: "MF", club: "Norwich City" },
    { no: 16, name: "Mortadha Ben Ouanes", pos: "MF", club: "Kasımpaşa" },
    { no: 17, name: "Ismaël Gharbi", pos: "MF", club: "FC Augsburg" },
    { no: 18, name: "Hadj Mahmoud", pos: "MF", club: "Lugano" },
    { no: 19, name: "Rani Khedira", pos: "MF", club: "Union Berlin" },
    { no: 20, name: "Elias Achouri", pos: "FW", club: "Copenhagen" },
    { no: 21, name: "Firas Chaouat", pos: "FW", club: "Club Africain" },
    { no: 22, name: "Hazem Mastouri", pos: "FW", club: "Dynamo Makhachkala" },
    { no: 23, name: "Elias Saad", pos: "FW", club: "Hannover 96" },
    { no: 24, name: "Sebastian Tounekti", pos: "FW", club: "Celtic" },
    { no: 25, name: "Khalil Ayari", pos: "FW", club: "Paris Saint-Germain" },
    { no: 26, name: "Rayan Elloumi", pos: "FW", club: "Vancouver Whitecaps FC" },
  ],
  bel: [
    { no: 1, name: "Thibaut Courtois", pos: "GK", club: "Real Madrid" },
    { no: 2, name: "Senne Lammens", pos: "GK", club: "Manchester United" },
    { no: 3, name: "Mike Penders", pos: "GK", club: "Strasbourg" },
    { no: 4, name: "Thomas Meunier", pos: "DF", club: "Lille" },
    { no: 5, name: "Timothy Castagne", pos: "DF", club: "Fulham" },
    { no: 6, name: "Arthur Theate", pos: "DF", club: "Eintracht Frankfurt" },
    { no: 7, name: "Zeno Debast", pos: "DF", club: "Sporting CP" },
    { no: 8, name: "Maxim De Cuyper", pos: "DF", club: "Brighton & Hove Albion" },
    { no: 9, name: "Brandon Mechele", pos: "DF", club: "Club Brugge" },
    { no: 10, name: "Koni De Winter", pos: "DF", club: "Milan" },
    { no: 11, name: "Joaquin Seys", pos: "DF", club: "Club Brugge" },
    { no: 12, name: "Nathan Ngoy", pos: "DF", club: "Lille" },
    { no: 13, name: "Axel Witsel", pos: "MF", club: "Girona" },
    { no: 14, name: "Kevin De Bruyne", pos: "MF", club: "Napoli" },
    { no: 15, name: "Youri Tielemans", pos: "MF", club: "Aston Villa", captain: true },
    { no: 16, name: "Hans Vanaken", pos: "MF", club: "Club Brugge" },
    { no: 17, name: "Amadou Onana", pos: "MF", club: "Aston Villa" },
    { no: 18, name: "Nicolas Raskin", pos: "MF", club: "Rangers" },
    { no: 19, name: "Romelu Lukaku", pos: "FW", club: "Napoli" },
    { no: 20, name: "Leandro Trossard", pos: "FW", club: "Arsenal" },
    { no: 21, name: "Jérémy Doku", pos: "FW", club: "Manchester City" },
    { no: 22, name: "Dodi Lukébakio", pos: "FW", club: "Benfica" },
    { no: 23, name: "Charles De Ketelaere", pos: "FW", club: "Atalanta" },
    { no: 24, name: "Alexis Saelemaekers", pos: "FW", club: "Milan" },
    { no: 25, name: "Diego Moreira", pos: "FW", club: "Strasbourg" },
    { no: 26, name: "Matias Fernandez-Pardo", pos: "FW", club: "Lille" },
  ],
  nzl: [
    { no: 1, name: "Max Crocombe", pos: "GK", club: "Millwall" },
    { no: 4, name: "Tyler Bindon", pos: "DF", club: "Sheffield United" },
    { no: 8, name: "Marko Stamenić", pos: "MF", club: "Swansea City" },
    { no: 9, name: "Chris Wood", pos: "FW", club: "Nottingham Forest", captain: true },
    { no: 11, name: "Elijah Just", pos: "MF", club: "Motherwell" },
    { no: 17, name: "Kosta Barbarouses", pos: "FW", club: "Western Sydney" },
  ],
  esp: [
    { no: 1, name: "Unai Simón", pos: "GK", club: "Athletic Bilbao" },
    { no: 2, name: "David Raya", pos: "GK", club: "Arsenal" },
    { no: 3, name: "Joan Garcia", pos: "GK", club: "Barcelona" },
    { no: 4, name: "Aymeric Laporte", pos: "DF", club: "Athletic Bilbao" },
    { no: 5, name: "Marc Cucurella", pos: "DF", club: "Chelsea" },
    { no: 6, name: "Marcos Llorente", pos: "DF", club: "Atlético Madrid" },
    { no: 7, name: "Eric García", pos: "DF", club: "Barcelona" },
    { no: 8, name: "Pedro Porro", pos: "DF", club: "Tottenham Hotspur" },
    { no: 9, name: "Álex Grimaldo", pos: "DF", club: "Bayer Leverkusen" },
    { no: 10, name: "Pau Cubarsí", pos: "DF", club: "Barcelona" },
    { no: 11, name: "Marc Pubill", pos: "DF", club: "Atlético Madrid" },
    { no: 12, name: "Rodri", pos: "MF", club: "Manchester City", captain: true },
    { no: 13, name: "Mikel Merino", pos: "MF", club: "Arsenal" },
    { no: 14, name: "Fabián Ruiz", pos: "MF", club: "Paris Saint-Germain" },
    { no: 15, name: "Pedri", pos: "MF", club: "Barcelona" },
    { no: 16, name: "Gavi", pos: "MF", club: "Barcelona" },
    { no: 17, name: "Martín Zubimendi", pos: "MF", club: "Arsenal" },
    { no: 18, name: "Álex Baena", pos: "MF", club: "Atlético Madrid" },
    { no: 19, name: "Ferran Torres", pos: "FW", club: "Barcelona" },
    { no: 20, name: "Mikel Oyarzabal", pos: "FW", club: "Real Sociedad" },
    { no: 21, name: "Dani Olmo", pos: "FW", club: "Barcelona" },
    { no: 22, name: "Nico Williams", pos: "FW", club: "Athletic Bilbao" },
    { no: 23, name: "Lamine Yamal", pos: "FW", club: "Barcelona" },
    { no: 24, name: "Yéremy Pino", pos: "FW", club: "Crystal Palace" },
    { no: 25, name: "Borja Iglesias", pos: "FW", club: "Celta Vigo" },
    { no: 26, name: "Víctor Muñoz", pos: "FW", club: "Osasuna" },
  ],
  cpv: [
    { no: 1, name: "Vozinha", pos: "GK", club: "Chaves" },
    { no: 2, name: "Márcio Rosa", pos: "GK", club: "Montana" },
    { no: 3, name: "CJ dos Santos", pos: "GK", club: "San Diego FC" },
    { no: 4, name: "Stopira", pos: "DF", club: "Torreense" },
    { no: 5, name: "Roberto Lopes", pos: "DF", club: "Shamrock Rovers" },
    { no: 6, name: "João Paulo", pos: "DF", club: "FCSB" },
    { no: 7, name: "Diney", pos: "DF", club: "Al Bataeh" },
    { no: 8, name: "Logan Costa", pos: "DF", club: "Villarreal" },
    { no: 9, name: "Steven Moreira", pos: "DF", club: "Columbus Crew" },
    { no: 10, name: "Wagner Pina", pos: "DF", club: "Trabzonspor" },
    { no: 11, name: "Sidny Lopes Cabral", pos: "DF", club: "Benfica" },
    { no: 12, name: "Kelvin Pires", pos: "DF", club: "SJK" },
    { no: 13, name: "Jamiro Monteiro", pos: "MF", club: "PEC Zwolle" },
    { no: 14, name: "Kevin Pina", pos: "MF", club: "Krasnodar" },
    { no: 15, name: "Deroy Duarte", pos: "MF", club: "Ludogorets Razgrad" },
    { no: 16, name: "Telmo Arcanjo", pos: "MF", club: "Vitória de Guimarães" },
    { no: 17, name: "Laros Duarte", pos: "MF", club: "Puskás Akadémia" },
    { no: 18, name: "Yannick Semedo", pos: "MF", club: "Farense" },
    { no: 19, name: "Ryan Mendes", pos: "FW", club: "Iğdır", captain: true },
    { no: 20, name: "Garry Rodrigues", pos: "FW", club: "Apollon Limassol" },
    { no: 21, name: "Willy Semedo", pos: "FW", club: "Omonia" },
    { no: 22, name: "Jovane Cabral", pos: "FW", club: "Estrela Amadora" },
    { no: 23, name: "Gilson Benchimol", pos: "FW", club: "Akron Tolyatti" },
    { no: 24, name: "Dailon Livramento", pos: "FW", club: "Casa Pia" },
    { no: 25, name: "Hélio Varela", pos: "FW", club: "Maccabi Tel Aviv" },
    { no: 26, name: "Nuno da Costa", pos: "FW", club: "İstanbul Başakşehir" },
  ],
  fra: [
    { no: 1, name: "Mike Maignan", pos: "GK", club: "AC Milan" },
    { no: 5, name: "Jules Koundé", pos: "DF", club: "Barcelona" },
    { no: 13, name: "N'Golo Kanté", pos: "MF", club: "Fenerbahçe" },
    { no: 10, name: "Kylian Mbappé", pos: "FW", club: "Real Madrid", captain: true },
    { no: 11, name: "Ousmane Dembélé", pos: "FW", club: "Paris Saint-Germain" },
    { no: 7, name: "Michael Olise", pos: "FW", club: "Bayern Munich" },
  ],
  arg: [
    { no: 23, name: "Emiliano Martínez", pos: "GK", club: "Aston Villa" },
    { no: 13, name: "Cristian Romero", pos: "DF", club: "Tottenham" },
    { no: 20, name: "Alexis Mac Allister", pos: "MF", club: "Liverpool" },
    { no: 10, name: "Lionel Messi", pos: "FW", club: "Inter Miami", captain: true },
    { no: 22, name: "Lautaro Martínez", pos: "FW", club: "Inter Milan" },
    { no: 9, name: "Julián Alvarez", pos: "FW", club: "Atlético Madrid" },
  ],
  prt: [
    { no: 1, name: "Diogo Costa", pos: "GK", club: "Porto" },
    { no: 2, name: "José Sá", pos: "GK", club: "Wolverhampton Wanderers" },
    { no: 3, name: "Rui Silva", pos: "GK", club: "Sporting CP" },
    { no: 4, name: "Rúben Dias", pos: "DF", club: "Manchester City" },
    { no: 5, name: "João Cancelo", pos: "DF", club: "Barcelona" },
    { no: 6, name: "Nélson Semedo", pos: "DF", club: "Fenerbahçe" },
    { no: 7, name: "Nuno Mendes", pos: "DF", club: "Paris Saint-Germain" },
    { no: 8, name: "Diogo Dalot", pos: "DF", club: "Manchester United" },
    { no: 9, name: "Gonçalo Inácio", pos: "DF", club: "Sporting CP" },
    { no: 10, name: "Matheus Nunes", pos: "DF", club: "Manchester City" },
    { no: 11, name: "Renato Veiga", pos: "DF", club: "Villarreal" },
    { no: 12, name: "Tomás Araújo", pos: "DF", club: "Benfica" },
    { no: 13, name: "Bernardo Silva", pos: "MF", club: "Manchester City" },
    { no: 14, name: "Bruno Fernandes", pos: "MF", club: "Manchester United" },
    { no: 15, name: "Rúben Neves", pos: "MF", club: "Al-Hilal" },
    { no: 16, name: "Vitinha", pos: "MF", club: "Paris Saint-Germain" },
    { no: 17, name: "João Neves", pos: "MF", club: "Paris Saint-Germain" },
    { no: 18, name: "Samú Costa", pos: "MF", club: "Mallorca" },
    { no: 19, name: "Cristiano Ronaldo", pos: "FW", club: "Al-Nassr", captain: true },
    { no: 20, name: "João Félix", pos: "FW", club: "Al-Nassr" },
    { no: 21, name: "Rafael Leão", pos: "FW", club: "Milan" },
    { no: 22, name: "Gonçalo Guedes", pos: "FW", club: "Real Sociedad" },
    { no: 23, name: "Gonçalo Ramos", pos: "FW", club: "Paris Saint-Germain" },
    { no: 24, name: "Pedro Neto", pos: "FW", club: "Chelsea" },
    { no: 25, name: "Francisco Trincão", pos: "FW", club: "Sporting CP" },
    { no: 26, name: "Francisco Conceição", pos: "FW", club: "Juventus" },
  ],
  cod: [
    { no: 1, name: "Lionel Mpasi", pos: "GK", club: "Le Havre" },
    { no: 2, name: "Timothy Fayulu", pos: "GK", club: "Noah" },
    { no: 3, name: "Matthieu Epolo", pos: "GK", club: "Standard Liège" },
    { no: 4, name: "Chancel Mbemba", pos: "DF", club: "Lille", captain: true },
    { no: 5, name: "Arthur Masuaku", pos: "DF", club: "Lens" },
    { no: 6, name: "Gédéon Kalulu", pos: "DF", club: "Aris Limassol" },
    { no: 7, name: "Joris Kayembe", pos: "DF", club: "Genk" },
    { no: 8, name: "Dylan Batubinsika", pos: "DF", club: "AEL" },
    { no: 9, name: "Axel Tuanzebe", pos: "DF", club: "Burnley" },
    { no: 10, name: "Aaron Wan-Bissaka", pos: "DF", club: "West Ham United" },
    { no: 11, name: "Steve Kapuadi", pos: "DF", club: "Widzew Łódź" },
    { no: 12, name: "Samuel Moutoussamy", pos: "MF", club: "Atromitos" },
    { no: 13, name: "Edo Kayembe", pos: "MF", club: "Watford" },
    { no: 14, name: "Charles Pickel", pos: "MF", club: "Espanyol" },
    { no: 15, name: "Gaël Kakuta", pos: "MF", club: "AEL" },
    { no: 16, name: "Noah Sadiki", pos: "MF", club: "Sunderland" },
    { no: 17, name: "Aaron Tshibola", pos: "MF", club: "Kilmarnock" },
    { no: 18, name: "Ngal'ayel Mukau", pos: "MF", club: "Lille" },
    { no: 19, name: "Brian Cipenga", pos: "MF", club: "Castellón" },
    { no: 20, name: "Cédric Bakambu", pos: "FW", club: "Real Betis" },
    { no: 21, name: "Meschak Elia", pos: "FW", club: "Alanyaspor" },
    { no: 22, name: "Théo Bongonda", pos: "FW", club: "Spartak Moscow" },
    { no: 23, name: "Fiston Mayele", pos: "FW", club: "Pyramids" },
    { no: 24, name: "Yoane Wissa", pos: "FW", club: "Newcastle United" },
    { no: 25, name: "Nathanaël Mbuku", pos: "FW", club: "Montpellier" },
    { no: 26, name: "Simon Banza", pos: "FW", club: "Al Jazira" },
  ],
  col: [
    { no: 1, name: "David Ospina", pos: "GK", club: "Atlético Nacional" },
    { no: 2, name: "Camilo Vargas", pos: "GK", club: "Atlas" },
    { no: 3, name: "Álvaro Montero", pos: "GK", club: "Vélez Sarsfield" },
    { no: 4, name: "Davinson Sánchez", pos: "DF", club: "Galatasaray" },
    { no: 5, name: "Santiago Arias", pos: "DF", club: "Independiente" },
    { no: 6, name: "Yerry Mina", pos: "DF", club: "Cagliari" },
    { no: 7, name: "Daniel Muñoz", pos: "DF", club: "Crystal Palace" },
    { no: 8, name: "Johan Mojica", pos: "DF", club: "Mallorca" },
    { no: 9, name: "Jhon Lucumí", pos: "DF", club: "Bologna" },
    { no: 10, name: "Deiver Machado", pos: "DF", club: "Nantes" },
    { no: 11, name: "Willer Ditta", pos: "DF", club: "Cruz Azul" },
    { no: 12, name: "James Rodríguez", pos: "MF", club: "Minnesota United FC", captain: true },
    { no: 13, name: "Jefferson Lerma", pos: "MF", club: "Crystal Palace" },
    { no: 14, name: "Juan Fernando Quintero", pos: "MF", club: "River Plate" },
    { no: 15, name: "Jhon Arias", pos: "MF", club: "Palmeiras" },
    { no: 16, name: "Richard Ríos", pos: "MF", club: "Benfica" },
    { no: 17, name: "Kevin Castaño", pos: "MF", club: "River Plate" },
    { no: 18, name: "Jorge Carrascal", pos: "MF", club: "Flamengo" },
    { no: 19, name: "Jaminton Campaz", pos: "MF", club: "Rosario Central" },
    { no: 20, name: "Juan Portilla", pos: "MF", club: "Athletico Paranaense" },
    { no: 21, name: "Gustavo Puerta", pos: "MF", club: "Racing Santander" },
    { no: 22, name: "Luis Díaz", pos: "FW", club: "Bayern Munich" },
    { no: 23, name: "Jhon Córdoba", pos: "FW", club: "Krasnodar" },
    { no: 24, name: "Luis Suárez", pos: "FW", club: "Sporting CP" },
    { no: 25, name: "Cucho Hernández", pos: "FW", club: "Real Betis" },
    { no: 26, name: "Andrés Gómez", pos: "FW", club: "Vasco da Gama" },
  ],
  eng: [
    { no: 1, name: "Jordan Pickford", pos: "GK", club: "Everton" },
    { no: 2, name: "Dean Henderson", pos: "GK", club: "Crystal Palace" },
    { no: 3, name: "James Trafford", pos: "GK", club: "Manchester City" },
    { no: 4, name: "John Stones", pos: "DF", club: "Manchester City" },
    { no: 5, name: "Marc Guéhi", pos: "DF", club: "Manchester City" },
    { no: 6, name: "Reece James", pos: "DF", club: "Chelsea" },
    { no: 7, name: "Ezri Konsa", pos: "DF", club: "Aston Villa" },
    { no: 8, name: "Dan Burn", pos: "DF", club: "Newcastle United" },
    { no: 9, name: "Tino Livramento", pos: "DF", club: "Newcastle United" },
    { no: 10, name: "Djed Spence", pos: "DF", club: "Tottenham Hotspur" },
    { no: 11, name: "Nico O'Reilly", pos: "DF", club: "Manchester City" },
    { no: 12, name: "Jarell Quansah", pos: "DF", club: "Bayer Leverkusen" },
    { no: 13, name: "Jordan Henderson", pos: "MF", club: "Brentford" },
    { no: 14, name: "Declan Rice", pos: "MF", club: "Arsenal" },
    { no: 15, name: "Jude Bellingham", pos: "MF", club: "Real Madrid" },
    { no: 16, name: "Morgan Rogers", pos: "MF", club: "Aston Villa" },
    { no: 17, name: "Kobbie Mainoo", pos: "MF", club: "Manchester United" },
    { no: 18, name: "Elliot Anderson", pos: "MF", club: "Nottingham Forest" },
    { no: 19, name: "Harry Kane", pos: "FW", club: "Bayern Munich", captain: true },
    { no: 20, name: "Marcus Rashford", pos: "FW", club: "Barcelona" },
    { no: 21, name: "Bukayo Saka", pos: "FW", club: "Arsenal" },
    { no: 22, name: "Ollie Watkins", pos: "FW", club: "Aston Villa" },
    { no: 23, name: "Anthony Gordon", pos: "FW", club: "Newcastle United" },
    { no: 24, name: "Eberechi Eze", pos: "FW", club: "Arsenal" },
    { no: 25, name: "Noni Madueke", pos: "FW", club: "Arsenal" },
    { no: 26, name: "Ivan Toney", pos: "FW", club: "Al-Ahli" },
  ],
  hrv: [
    { no: 1, name: "Dominik Livaković", pos: "GK", club: "Dinamo Zagreb" },
    { no: 2, name: "Dominik Kotarski", pos: "GK", club: "Copenhagen" },
    { no: 3, name: "Ivor Pandur", pos: "GK", club: "Hull City" },
    { no: 4, name: "Joško Gvardiol", pos: "DF", club: "Manchester City" },
    { no: 5, name: "Duje Ćaleta-Car", pos: "DF", club: "Real Sociedad" },
    { no: 6, name: "Josip Šutalo", pos: "DF", club: "Ajax" },
    { no: 7, name: "Josip Stanišić", pos: "DF", club: "Bayern Munich" },
    { no: 8, name: "Marin Pongračić", pos: "DF", club: "Fiorentina" },
    { no: 9, name: "Martin Erlić", pos: "DF", club: "Midtjylland" },
    { no: 10, name: "Luka Vušković", pos: "DF", club: "Hamburger SV" },
    { no: 11, name: "Luka Modrić", pos: "MF", club: "Milan", captain: true },
    { no: 12, name: "Mateo Kovačić", pos: "MF", club: "Manchester City" },
    { no: 13, name: "Mario Pašalić", pos: "MF", club: "Atalanta" },
    { no: 14, name: "Nikola Vlašić", pos: "MF", club: "Torino" },
    { no: 15, name: "Luka Sučić", pos: "MF", club: "Real Sociedad" },
    { no: 16, name: "Martin Baturina", pos: "MF", club: "Como" },
    { no: 17, name: "Kristijan Jakić", pos: "MF", club: "FC Augsburg" },
    { no: 18, name: "Petar Sučić", pos: "MF", club: "Inter Milan" },
    { no: 19, name: "Nikola Moro", pos: "MF", club: "Bologna" },
    { no: 20, name: "Toni Fruk", pos: "MF", club: "Rijeka" },
    { no: 21, name: "Ivan Perišić", pos: "FW", club: "PSV Eindhoven" },
    { no: 22, name: "Andrej Kramarić", pos: "FW", club: "TSG Hoffenheim" },
    { no: 23, name: "Ante Budimir", pos: "FW", club: "Osasuna" },
    { no: 24, name: "Marco Pašalić", pos: "FW", club: "Orlando City" },
    { no: 25, name: "Petar Musa", pos: "FW", club: "FC Dallas" },
    { no: 26, name: "Igor Matanović", pos: "FW", club: "SC Freiburg" },
  ],
  pan: [
    { no: 1, name: "Luis Mejía", pos: "GK", club: "Nacional" },
    { no: 2, name: "Orlando Mosquera", pos: "GK", club: "Al-Fayha" },
    { no: 3, name: "César Samudio", pos: "GK", club: "Marathón" },
    { no: 4, name: "Eric Davis", pos: "DF", club: "Plaza Amador" },
    { no: 5, name: "Fidel Escobar", pos: "DF", club: "Saprissa" },
    { no: 6, name: "Michael Amir Murillo", pos: "DF", club: "Beşiktaş" },
    { no: 7, name: "Roderick Miller", pos: "DF", club: "Turan Tovuz" },
    { no: 8, name: "Andrés Andrade", pos: "DF", club: "LASK" },
    { no: 9, name: "César Blackman", pos: "DF", club: "Slovan Bratislava" },
    { no: 10, name: "José Córdoba", pos: "DF", club: "Norwich City" },
    { no: 11, name: "Jiovany Ramos", pos: "DF", club: "Puerto Cabello" },
    { no: 12, name: "Jorge Gutiérrez", pos: "DF", club: "Deportivo La Guaira" },
    { no: 13, name: "Edgardo Fariña", pos: "DF", club: "Pari Nizhny Novgorod" },
    { no: 14, name: "Aníbal Godoy", pos: "MF", club: "San Diego FC", captain: true },
    { no: 15, name: "Alberto Quintero", pos: "MF", club: "Plaza Amador" },
    { no: 16, name: "Yoel Bárcenas", pos: "MF", club: "Mazatlán" },
    { no: 17, name: "Adalberto Carrasquilla", pos: "MF", club: "UNAM" },
    { no: 18, name: "José Luis Rodríguez", pos: "MF", club: "Juárez" },
    { no: 19, name: "Cristian Martínez", pos: "MF", club: "Ironi Kiryat Shmona" },
    { no: 20, name: "César Yanis", pos: "MF", club: "Cobresal" },
    { no: 21, name: "Carlos Harvey", pos: "MF", club: "Minnesota United FC" },
    { no: 22, name: "Azarias Londoño", pos: "MF", club: "Universidad Católica" },
    { no: 23, name: "José Fajardo", pos: "FW", club: "Universidad Católica" },
    { no: 24, name: "Ismael Díaz", pos: "FW", club: "León" },
    { no: 25, name: "Cecilio Waterman", pos: "FW", club: "Universidad de Concepción" },
    { no: 26, name: "Tomás Rodríguez", pos: "FW", club: "Saprissa" },
  ],

};

export function getWcRoster(teamId: string | null | undefined): WcRosterPlayer[] {
  if (!teamId || !teamId.startsWith("wc-")) return [];
  const iso3 = teamId.slice(3).toLowerCase();
  return WC_ROSTERS[iso3] ?? [];
}
